-- +goose Up
ALTER TABLE task_executions
    MODIFY COLUMN status ENUM(
        'WAITING_PULL', 'PREPARE', 'RUNNING', 'FAILED_RETRYABLE',
        'FAILED_RESCHEDULED', 'FAILED', 'SUCCESS', 'CANCELLED'
    ) NOT NULL DEFAULT 'PREPARE'
    COMMENT '执行状态: PREPARE-初始化，RUNNING-执行中，FAILED_RETRYABLE-可重试失败，FAILED_RESCHEDULED-重调度失败，FAILED-失败，SUCCESS-成功，CANCELLED-强制终止';

-- +goose Down
UPDATE task_executions SET status = 'FAILED' WHERE status = 'CANCELLED';
ALTER TABLE task_executions
    MODIFY COLUMN status ENUM(
        'WAITING_PULL', 'PREPARE', 'RUNNING', 'FAILED_RETRYABLE',
        'FAILED_RESCHEDULED', 'FAILED', 'SUCCESS'
    ) NOT NULL DEFAULT 'PREPARE'
    COMMENT '执行状态';
