// Code generated by MockGen. DO NOT EDIT.
// Source: ./codec.go
//
// Generated by this command:
//
//	mockgen -source=./codec.go -package=archivemocks -destination=./mocks/codec.mock.go -typed
//

// Package archivemocks is a generated GoMock package.
package archivemocks

import (
	context "context"
	io "io"
	reflect "reflect"

	archive "github.com/Duke1616/etask/internal/artifact/archive"
	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIArchiveCodec is a mock of IArchiveCodec interface.
type MockIArchiveCodec struct {
	ctrl     *gomock.Controller
	recorder *MockIArchiveCodecMockRecorder
	isgomock struct{}
}

// MockIArchiveCodecMockRecorder is the mock recorder for MockIArchiveCodec.
type MockIArchiveCodecMockRecorder struct {
	mock *MockIArchiveCodec
}

// NewMockIArchiveCodec creates a new mock instance.
func NewMockIArchiveCodec(ctrl *gomock.Controller) *MockIArchiveCodec {
	mock := &MockIArchiveCodec{ctrl: ctrl}
	mock.recorder = &MockIArchiveCodecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIArchiveCodec) EXPECT() *MockIArchiveCodecMockRecorder {
	return m.recorder
}

// Extract mocks base method.
func (m *MockIArchiveCodec) Extract(source, target string, expected archive.Metadata, limits archive.ExtractLimits) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", source, target, expected, limits)
	ret0, _ := ret[0].(error)
	return ret0
}

// Extract indicates an expected call of Extract.
func (mr *MockIArchiveCodecMockRecorder) Extract(source, target, expected, limits any) *MockIArchiveCodecExtractCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockIArchiveCodec)(nil).Extract), source, target, expected, limits)
	return &MockIArchiveCodecExtractCall{Call: call}
}

// MockIArchiveCodecExtractCall wrap *gomock.Call
type MockIArchiveCodecExtractCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIArchiveCodecExtractCall) Return(arg0 error) *MockIArchiveCodecExtractCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIArchiveCodecExtractCall) Do(f func(string, string, archive.Metadata, archive.ExtractLimits) error) *MockIArchiveCodecExtractCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIArchiveCodecExtractCall) DoAndReturn(f func(string, string, archive.Metadata, archive.ExtractLimits) error) *MockIArchiveCodecExtractCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Pack mocks base method.
func (m *MockIArchiveCodec) Pack(files []domain.ArtifactFile) (archive.PackedArtifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pack", files)
	ret0, _ := ret[0].(archive.PackedArtifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pack indicates an expected call of Pack.
func (mr *MockIArchiveCodecMockRecorder) Pack(files any) *MockIArchiveCodecPackCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pack", reflect.TypeOf((*MockIArchiveCodec)(nil).Pack), files)
	return &MockIArchiveCodecPackCall{Call: call}
}

// MockIArchiveCodecPackCall wrap *gomock.Call
type MockIArchiveCodecPackCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIArchiveCodecPackCall) Return(arg0 archive.PackedArtifact, arg1 error) *MockIArchiveCodecPackCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIArchiveCodecPackCall) Do(f func([]domain.ArtifactFile) (archive.PackedArtifact, error)) *MockIArchiveCodecPackCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIArchiveCodecPackCall) DoAndReturn(f func([]domain.ArtifactFile) (archive.PackedArtifact, error)) *MockIArchiveCodecPackCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PackContext mocks base method.
func (m *MockIArchiveCodec) PackContext(ctx context.Context, files []domain.ArtifactFile, open archive.OpenFile) (archive.PackedArtifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PackContext", ctx, files, open)
	ret0, _ := ret[0].(archive.PackedArtifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PackContext indicates an expected call of PackContext.
func (mr *MockIArchiveCodecMockRecorder) PackContext(ctx, files, open any) *MockIArchiveCodecPackContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PackContext", reflect.TypeOf((*MockIArchiveCodec)(nil).PackContext), ctx, files, open)
	return &MockIArchiveCodecPackContextCall{Call: call}
}

// MockIArchiveCodecPackContextCall wrap *gomock.Call
type MockIArchiveCodecPackContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIArchiveCodecPackContextCall) Return(arg0 archive.PackedArtifact, arg1 error) *MockIArchiveCodecPackContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIArchiveCodecPackContextCall) Do(f func(context.Context, []domain.ArtifactFile, archive.OpenFile) (archive.PackedArtifact, error)) *MockIArchiveCodecPackContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIArchiveCodecPackContextCall) DoAndReturn(f func(context.Context, []domain.ArtifactFile, archive.OpenFile) (archive.PackedArtifact, error)) *MockIArchiveCodecPackContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadFile mocks base method.
func (m *MockIArchiveCodec) ReadFile(reader io.Reader, expectedDigest, filePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", reader, expectedDigest, filePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockIArchiveCodecMockRecorder) ReadFile(reader, expectedDigest, filePath any) *MockIArchiveCodecReadFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockIArchiveCodec)(nil).ReadFile), reader, expectedDigest, filePath)
	return &MockIArchiveCodecReadFileCall{Call: call}
}

// MockIArchiveCodecReadFileCall wrap *gomock.Call
type MockIArchiveCodecReadFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIArchiveCodecReadFileCall) Return(arg0 string, arg1 error) *MockIArchiveCodecReadFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIArchiveCodecReadFileCall) Do(f func(io.Reader, string, string) (string, error)) *MockIArchiveCodecReadFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIArchiveCodecReadFileCall) DoAndReturn(f func(io.Reader, string, string) (string, error)) *MockIArchiveCodecReadFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadManifest mocks base method.
func (m *MockIArchiveCodec) ReadManifest(reader io.Reader, expectedDigest string) (archive.Manifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadManifest", reader, expectedDigest)
	ret0, _ := ret[0].(archive.Manifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadManifest indicates an expected call of ReadManifest.
func (mr *MockIArchiveCodecMockRecorder) ReadManifest(reader, expectedDigest any) *MockIArchiveCodecReadManifestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadManifest", reflect.TypeOf((*MockIArchiveCodec)(nil).ReadManifest), reader, expectedDigest)
	return &MockIArchiveCodecReadManifestCall{Call: call}
}

// MockIArchiveCodecReadManifestCall wrap *gomock.Call
type MockIArchiveCodecReadManifestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIArchiveCodecReadManifestCall) Return(arg0 archive.Manifest, arg1 error) *MockIArchiveCodecReadManifestCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIArchiveCodecReadManifestCall) Do(f func(io.Reader, string) (archive.Manifest, error)) *MockIArchiveCodecReadManifestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIArchiveCodecReadManifestCall) DoAndReturn(f func(io.Reader, string) (archive.Manifest, error)) *MockIArchiveCodecReadManifestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
