// Code generated by MockGen. DO NOT EDIT.
// Source: ./artifact.go
//
// Generated by this command:
//
//	mockgen -source=./artifact.go -package=artifactmocks -destination=./mocks/artifact.mock.go -typed
//

// Package artifactmocks is a generated GoMock package.
package artifactmocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockService) Activate(ctx context.Context, target domain.ArtifactTarget, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", ctx, target, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockServiceMockRecorder) Activate(ctx, target, id any) *MockServiceActivateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockService)(nil).Activate), ctx, target, id)
	return &MockServiceActivateCall{Call: call}
}

// MockServiceActivateCall wrap *gomock.Call
type MockServiceActivateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceActivateCall) Return(arg0 error) *MockServiceActivateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceActivateCall) Do(f func(context.Context, domain.ArtifactTarget, int64) error) *MockServiceActivateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceActivateCall) DoAndReturn(f func(context.Context, domain.ArtifactTarget, int64) error) *MockServiceActivateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Active mocks base method.
func (m *MockService) Active(ctx context.Context, target domain.ArtifactTarget) (*domain.ArtifactRelease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Active", ctx, target)
	ret0, _ := ret[0].(*domain.ArtifactRelease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Active indicates an expected call of Active.
func (mr *MockServiceMockRecorder) Active(ctx, target any) *MockServiceActiveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Active", reflect.TypeOf((*MockService)(nil).Active), ctx, target)
	return &MockServiceActiveCall{Call: call}
}

// MockServiceActiveCall wrap *gomock.Call
type MockServiceActiveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceActiveCall) Return(arg0 *domain.ArtifactRelease, arg1 error) *MockServiceActiveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceActiveCall) Do(f func(context.Context, domain.ArtifactTarget) (*domain.ArtifactRelease, error)) *MockServiceActiveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceActiveCall) DoAndReturn(f func(context.Context, domain.ArtifactTarget) (*domain.ArtifactRelease, error)) *MockServiceActiveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ActiveContents mocks base method.
func (m *MockService) ActiveContents(ctx context.Context, sourceProjectID int64) ([]domain.ArtifactContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveContents", ctx, sourceProjectID)
	ret0, _ := ret[0].([]domain.ArtifactContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveContents indicates an expected call of ActiveContents.
func (mr *MockServiceMockRecorder) ActiveContents(ctx, sourceProjectID any) *MockServiceActiveContentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveContents", reflect.TypeOf((*MockService)(nil).ActiveContents), ctx, sourceProjectID)
	return &MockServiceActiveContentsCall{Call: call}
}

// MockServiceActiveContentsCall wrap *gomock.Call
type MockServiceActiveContentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceActiveContentsCall) Return(arg0 []domain.ArtifactContent, arg1 error) *MockServiceActiveContentsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceActiveContentsCall) Do(f func(context.Context, int64) ([]domain.ArtifactContent, error)) *MockServiceActiveContentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceActiveContentsCall) DoAndReturn(f func(context.Context, int64) ([]domain.ArtifactContent, error)) *MockServiceActiveContentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, target domain.ArtifactTarget, offset, limit int64) ([]domain.ArtifactRelease, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, target, offset, limit)
	ret0, _ := ret[0].([]domain.ArtifactRelease)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, target, offset, limit any) *MockServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, target, offset, limit)
	return &MockServiceListCall{Call: call}
}

// MockServiceListCall wrap *gomock.Call
type MockServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListCall) Return(arg0 []domain.ArtifactRelease, arg1 int64, arg2 error) *MockServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListCall) Do(f func(context.Context, domain.ArtifactTarget, int64, int64) ([]domain.ArtifactRelease, int64, error)) *MockServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListCall) DoAndReturn(f func(context.Context, domain.ArtifactTarget, int64, int64) ([]domain.ArtifactRelease, int64, error)) *MockServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Open mocks base method.
func (m *MockService) Open(ctx context.Context, releaseID int64, digest string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, releaseID, digest)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockServiceMockRecorder) Open(ctx, releaseID, digest any) *MockServiceOpenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockService)(nil).Open), ctx, releaseID, digest)
	return &MockServiceOpenCall{Call: call}
}

// MockServiceOpenCall wrap *gomock.Call
type MockServiceOpenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceOpenCall) Return(arg0 io.ReadCloser, arg1 error) *MockServiceOpenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceOpenCall) Do(f func(context.Context, int64, string) (io.ReadCloser, error)) *MockServiceOpenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceOpenCall) DoAndReturn(f func(context.Context, int64, string) (io.ReadCloser, error)) *MockServiceOpenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Publish mocks base method.
func (m *MockService) Publish(ctx context.Context, target domain.ArtifactTarget, message string) (domain.ArtifactRelease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, target, message)
	ret0, _ := ret[0].(domain.ArtifactRelease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockServiceMockRecorder) Publish(ctx, target, message any) *MockServicePublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockService)(nil).Publish), ctx, target, message)
	return &MockServicePublishCall{Call: call}
}

// MockServicePublishCall wrap *gomock.Call
type MockServicePublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServicePublishCall) Return(arg0 domain.ArtifactRelease, arg1 error) *MockServicePublishCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServicePublishCall) Do(f func(context.Context, domain.ArtifactTarget, string) (domain.ArtifactRelease, error)) *MockServicePublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServicePublishCall) DoAndReturn(f func(context.Context, domain.ArtifactTarget, string) (domain.ArtifactRelease, error)) *MockServicePublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadFile mocks base method.
func (m *MockService) ReadFile(ctx context.Context, releaseID int64, digest, filePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, releaseID, digest, filePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockServiceMockRecorder) ReadFile(ctx, releaseID, digest, filePath any) *MockServiceReadFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockService)(nil).ReadFile), ctx, releaseID, digest, filePath)
	return &MockServiceReadFileCall{Call: call}
}

// MockServiceReadFileCall wrap *gomock.Call
type MockServiceReadFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceReadFileCall) Return(arg0 string, arg1 error) *MockServiceReadFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceReadFileCall) Do(f func(context.Context, int64, string, string) (string, error)) *MockServiceReadFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceReadFileCall) DoAndReturn(f func(context.Context, int64, string, string) (string, error)) *MockServiceReadFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResolveExecution mocks base method.
func (m *MockService) ResolveExecution(ctx context.Context, sourceProjectID int64) ([]domain.ArtifactRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveExecution", ctx, sourceProjectID)
	ret0, _ := ret[0].([]domain.ArtifactRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveExecution indicates an expected call of ResolveExecution.
func (mr *MockServiceMockRecorder) ResolveExecution(ctx, sourceProjectID any) *MockServiceResolveExecutionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveExecution", reflect.TypeOf((*MockService)(nil).ResolveExecution), ctx, sourceProjectID)
	return &MockServiceResolveExecutionCall{Call: call}
}

// MockServiceResolveExecutionCall wrap *gomock.Call
type MockServiceResolveExecutionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceResolveExecutionCall) Return(arg0 []domain.ArtifactRef, arg1 error) *MockServiceResolveExecutionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceResolveExecutionCall) Do(f func(context.Context, int64) ([]domain.ArtifactRef, error)) *MockServiceResolveExecutionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceResolveExecutionCall) DoAndReturn(f func(context.Context, int64) ([]domain.ArtifactRef, error)) *MockServiceResolveExecutionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Status mocks base method.
func (m *MockService) Status(ctx context.Context, target domain.ArtifactTarget) (domain.ArtifactStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, target)
	ret0, _ := ret[0].(domain.ArtifactStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockServiceMockRecorder) Status(ctx, target any) *MockServiceStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockService)(nil).Status), ctx, target)
	return &MockServiceStatusCall{Call: call}
}

// MockServiceStatusCall wrap *gomock.Call
type MockServiceStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceStatusCall) Return(arg0 domain.ArtifactStatus, arg1 error) *MockServiceStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceStatusCall) Do(f func(context.Context, domain.ArtifactTarget) (domain.ArtifactStatus, error)) *MockServiceStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceStatusCall) DoAndReturn(f func(context.Context, domain.ArtifactTarget) (domain.ArtifactStatus, error)) *MockServiceStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
