// Code generated by MockGen. DO NOT EDIT.
// Source: ./execution_service.go
//
// Generated by this command:
//
//	mockgen -source=./execution_service.go -package=taskmocks -destination=./mocks/execution_service.mock.go -typed
//

// Package taskmocks is a generated GoMock package.
package taskmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutionService is a mock of ExecutionService interface.
type MockExecutionService struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionServiceMockRecorder
	isgomock struct{}
}

// MockExecutionServiceMockRecorder is the mock recorder for MockExecutionService.
type MockExecutionServiceMockRecorder struct {
	mock *MockExecutionService
}

// NewMockExecutionService creates a new mock instance.
func NewMockExecutionService(ctrl *gomock.Controller) *MockExecutionService {
	mock := &MockExecutionService{ctrl: ctrl}
	mock.recorder = &MockExecutionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionService) EXPECT() *MockExecutionServiceMockRecorder {
	return m.recorder
}

// AppendExecutionLogs mocks base method.
func (m *MockExecutionService) AppendExecutionLogs(ctx context.Context, executionID, taskID int64, logs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendExecutionLogs", ctx, executionID, taskID, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendExecutionLogs indicates an expected call of AppendExecutionLogs.
func (mr *MockExecutionServiceMockRecorder) AppendExecutionLogs(ctx, executionID, taskID, logs any) *MockExecutionServiceAppendExecutionLogsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendExecutionLogs", reflect.TypeOf((*MockExecutionService)(nil).AppendExecutionLogs), ctx, executionID, taskID, logs)
	return &MockExecutionServiceAppendExecutionLogsCall{Call: call}
}

// MockExecutionServiceAppendExecutionLogsCall wrap *gomock.Call
type MockExecutionServiceAppendExecutionLogsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceAppendExecutionLogsCall) Return(arg0 error) *MockExecutionServiceAppendExecutionLogsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceAppendExecutionLogsCall) Do(f func(context.Context, int64, int64, []string) error) *MockExecutionServiceAppendExecutionLogsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceAppendExecutionLogsCall) DoAndReturn(f func(context.Context, int64, int64, []string) error) *MockExecutionServiceAppendExecutionLogsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockExecutionService) Create(ctx context.Context, execution domain.TaskExecution) (domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, execution)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExecutionServiceMockRecorder) Create(ctx, execution any) *MockExecutionServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExecutionService)(nil).Create), ctx, execution)
	return &MockExecutionServiceCreateCall{Call: call}
}

// MockExecutionServiceCreateCall wrap *gomock.Call
type MockExecutionServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceCreateCall) Return(arg0 domain.TaskExecution, arg1 error) *MockExecutionServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceCreateCall) Do(f func(context.Context, domain.TaskExecution) (domain.TaskExecution, error)) *MockExecutionServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceCreateCall) DoAndReturn(f func(context.Context, domain.TaskExecution) (domain.TaskExecution, error)) *MockExecutionServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreatePreview mocks base method.
func (m *MockExecutionService) CreatePreview(ctx context.Context, execution domain.TaskExecution, sourceProjectID int64) (domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePreview", ctx, execution, sourceProjectID)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePreview indicates an expected call of CreatePreview.
func (mr *MockExecutionServiceMockRecorder) CreatePreview(ctx, execution, sourceProjectID any) *MockExecutionServiceCreatePreviewCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePreview", reflect.TypeOf((*MockExecutionService)(nil).CreatePreview), ctx, execution, sourceProjectID)
	return &MockExecutionServiceCreatePreviewCall{Call: call}
}

// MockExecutionServiceCreatePreviewCall wrap *gomock.Call
type MockExecutionServiceCreatePreviewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceCreatePreviewCall) Return(arg0 domain.TaskExecution, arg1 error) *MockExecutionServiceCreatePreviewCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceCreatePreviewCall) Do(f func(context.Context, domain.TaskExecution, int64) (domain.TaskExecution, error)) *MockExecutionServiceCreatePreviewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceCreatePreviewCall) DoAndReturn(f func(context.Context, domain.TaskExecution, int64) (domain.TaskExecution, error)) *MockExecutionServiceCreatePreviewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateWorkflow mocks base method.
func (m *MockExecutionService) CreateWorkflow(ctx context.Context, execution domain.TaskExecution, sourceProjectID int64) (domain.TaskExecution, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkflow", ctx, execution, sourceProjectID)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateWorkflow indicates an expected call of CreateWorkflow.
func (mr *MockExecutionServiceMockRecorder) CreateWorkflow(ctx, execution, sourceProjectID any) *MockExecutionServiceCreateWorkflowCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkflow", reflect.TypeOf((*MockExecutionService)(nil).CreateWorkflow), ctx, execution, sourceProjectID)
	return &MockExecutionServiceCreateWorkflowCall{Call: call}
}

// MockExecutionServiceCreateWorkflowCall wrap *gomock.Call
type MockExecutionServiceCreateWorkflowCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceCreateWorkflowCall) Return(arg0 domain.TaskExecution, arg1 bool, arg2 error) *MockExecutionServiceCreateWorkflowCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceCreateWorkflowCall) Do(f func(context.Context, domain.TaskExecution, int64) (domain.TaskExecution, bool, error)) *MockExecutionServiceCreateWorkflowCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceCreateWorkflowCall) DoAndReturn(f func(context.Context, domain.TaskExecution, int64) (domain.TaskExecution, bool, error)) *MockExecutionServiceCreateWorkflowCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByID mocks base method.
func (m *MockExecutionService) FindByID(ctx context.Context, id int64) (domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockExecutionServiceMockRecorder) FindByID(ctx, id any) *MockExecutionServiceFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockExecutionService)(nil).FindByID), ctx, id)
	return &MockExecutionServiceFindByIDCall{Call: call}
}

// MockExecutionServiceFindByIDCall wrap *gomock.Call
type MockExecutionServiceFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceFindByIDCall) Return(arg0 domain.TaskExecution, arg1 error) *MockExecutionServiceFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceFindByIDCall) Do(f func(context.Context, int64) (domain.TaskExecution, error)) *MockExecutionServiceFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceFindByIDCall) DoAndReturn(f func(context.Context, int64) (domain.TaskExecution, error)) *MockExecutionServiceFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindExecutionByTaskIDAndPlanExecID mocks base method.
func (m *MockExecutionService) FindExecutionByTaskIDAndPlanExecID(ctx context.Context, taskID, planExecID int64) (domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExecutionByTaskIDAndPlanExecID", ctx, taskID, planExecID)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExecutionByTaskIDAndPlanExecID indicates an expected call of FindExecutionByTaskIDAndPlanExecID.
func (mr *MockExecutionServiceMockRecorder) FindExecutionByTaskIDAndPlanExecID(ctx, taskID, planExecID any) *MockExecutionServiceFindExecutionByTaskIDAndPlanExecIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExecutionByTaskIDAndPlanExecID", reflect.TypeOf((*MockExecutionService)(nil).FindExecutionByTaskIDAndPlanExecID), ctx, taskID, planExecID)
	return &MockExecutionServiceFindExecutionByTaskIDAndPlanExecIDCall{Call: call}
}

// MockExecutionServiceFindExecutionByTaskIDAndPlanExecIDCall wrap *gomock.Call
type MockExecutionServiceFindExecutionByTaskIDAndPlanExecIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceFindExecutionByTaskIDAndPlanExecIDCall) Return(arg0 domain.TaskExecution, arg1 error) *MockExecutionServiceFindExecutionByTaskIDAndPlanExecIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceFindExecutionByTaskIDAndPlanExecIDCall) Do(f func(context.Context, int64, int64) (domain.TaskExecution, error)) *MockExecutionServiceFindExecutionByTaskIDAndPlanExecIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceFindExecutionByTaskIDAndPlanExecIDCall) DoAndReturn(f func(context.Context, int64, int64) (domain.TaskExecution, error)) *MockExecutionServiceFindExecutionByTaskIDAndPlanExecIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindReschedulableExecutions mocks base method.
func (m *MockExecutionService) FindReschedulableExecutions(ctx context.Context, limit int) ([]domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReschedulableExecutions", ctx, limit)
	ret0, _ := ret[0].([]domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindReschedulableExecutions indicates an expected call of FindReschedulableExecutions.
func (mr *MockExecutionServiceMockRecorder) FindReschedulableExecutions(ctx, limit any) *MockExecutionServiceFindReschedulableExecutionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReschedulableExecutions", reflect.TypeOf((*MockExecutionService)(nil).FindReschedulableExecutions), ctx, limit)
	return &MockExecutionServiceFindReschedulableExecutionsCall{Call: call}
}

// MockExecutionServiceFindReschedulableExecutionsCall wrap *gomock.Call
type MockExecutionServiceFindReschedulableExecutionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceFindReschedulableExecutionsCall) Return(arg0 []domain.TaskExecution, arg1 error) *MockExecutionServiceFindReschedulableExecutionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceFindReschedulableExecutionsCall) Do(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockExecutionServiceFindReschedulableExecutionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceFindReschedulableExecutionsCall) DoAndReturn(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockExecutionServiceFindReschedulableExecutionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindRetryableExecutions mocks base method.
func (m *MockExecutionService) FindRetryableExecutions(ctx context.Context, limit int) ([]domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRetryableExecutions", ctx, limit)
	ret0, _ := ret[0].([]domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRetryableExecutions indicates an expected call of FindRetryableExecutions.
func (mr *MockExecutionServiceMockRecorder) FindRetryableExecutions(ctx, limit any) *MockExecutionServiceFindRetryableExecutionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRetryableExecutions", reflect.TypeOf((*MockExecutionService)(nil).FindRetryableExecutions), ctx, limit)
	return &MockExecutionServiceFindRetryableExecutionsCall{Call: call}
}

// MockExecutionServiceFindRetryableExecutionsCall wrap *gomock.Call
type MockExecutionServiceFindRetryableExecutionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceFindRetryableExecutionsCall) Return(arg0 []domain.TaskExecution, arg1 error) *MockExecutionServiceFindRetryableExecutionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceFindRetryableExecutionsCall) Do(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockExecutionServiceFindRetryableExecutionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceFindRetryableExecutionsCall) DoAndReturn(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockExecutionServiceFindRetryableExecutionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindTimeoutExecutions mocks base method.
func (m *MockExecutionService) FindTimeoutExecutions(ctx context.Context, limit int) ([]domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTimeoutExecutions", ctx, limit)
	ret0, _ := ret[0].([]domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTimeoutExecutions indicates an expected call of FindTimeoutExecutions.
func (mr *MockExecutionServiceMockRecorder) FindTimeoutExecutions(ctx, limit any) *MockExecutionServiceFindTimeoutExecutionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTimeoutExecutions", reflect.TypeOf((*MockExecutionService)(nil).FindTimeoutExecutions), ctx, limit)
	return &MockExecutionServiceFindTimeoutExecutionsCall{Call: call}
}

// MockExecutionServiceFindTimeoutExecutionsCall wrap *gomock.Call
type MockExecutionServiceFindTimeoutExecutionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceFindTimeoutExecutionsCall) Return(arg0 []domain.TaskExecution, arg1 error) *MockExecutionServiceFindTimeoutExecutionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceFindTimeoutExecutionsCall) Do(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockExecutionServiceFindTimeoutExecutionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceFindTimeoutExecutionsCall) DoAndReturn(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockExecutionServiceFindTimeoutExecutionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindWorkflowByRequestID mocks base method.
func (m *MockExecutionService) FindWorkflowByRequestID(ctx context.Context, requestID string) (domain.TaskExecution, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWorkflowByRequestID", ctx, requestID)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindWorkflowByRequestID indicates an expected call of FindWorkflowByRequestID.
func (mr *MockExecutionServiceMockRecorder) FindWorkflowByRequestID(ctx, requestID any) *MockExecutionServiceFindWorkflowByRequestIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWorkflowByRequestID", reflect.TypeOf((*MockExecutionService)(nil).FindWorkflowByRequestID), ctx, requestID)
	return &MockExecutionServiceFindWorkflowByRequestIDCall{Call: call}
}

// MockExecutionServiceFindWorkflowByRequestIDCall wrap *gomock.Call
type MockExecutionServiceFindWorkflowByRequestIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceFindWorkflowByRequestIDCall) Return(arg0 domain.TaskExecution, arg1 bool, arg2 error) *MockExecutionServiceFindWorkflowByRequestIDCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceFindWorkflowByRequestIDCall) Do(f func(context.Context, string) (domain.TaskExecution, bool, error)) *MockExecutionServiceFindWorkflowByRequestIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceFindWorkflowByRequestIDCall) DoAndReturn(f func(context.Context, string) (domain.TaskExecution, bool, error)) *MockExecutionServiceFindWorkflowByRequestIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasNonTerminalByTaskID mocks base method.
func (m *MockExecutionService) HasNonTerminalByTaskID(ctx context.Context, taskID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNonTerminalByTaskID", ctx, taskID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasNonTerminalByTaskID indicates an expected call of HasNonTerminalByTaskID.
func (mr *MockExecutionServiceMockRecorder) HasNonTerminalByTaskID(ctx, taskID any) *MockExecutionServiceHasNonTerminalByTaskIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNonTerminalByTaskID", reflect.TypeOf((*MockExecutionService)(nil).HasNonTerminalByTaskID), ctx, taskID)
	return &MockExecutionServiceHasNonTerminalByTaskIDCall{Call: call}
}

// MockExecutionServiceHasNonTerminalByTaskIDCall wrap *gomock.Call
type MockExecutionServiceHasNonTerminalByTaskIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceHasNonTerminalByTaskIDCall) Return(arg0 bool, arg1 error) *MockExecutionServiceHasNonTerminalByTaskIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceHasNonTerminalByTaskIDCall) Do(f func(context.Context, int64) (bool, error)) *MockExecutionServiceHasNonTerminalByTaskIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceHasNonTerminalByTaskIDCall) DoAndReturn(f func(context.Context, int64) (bool, error)) *MockExecutionServiceHasNonTerminalByTaskIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByTaskID mocks base method.
func (m *MockExecutionService) ListByTaskID(ctx context.Context, taskID int64, offset, limit int) ([]domain.TaskExecution, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTaskID", ctx, taskID, offset, limit)
	ret0, _ := ret[0].([]domain.TaskExecution)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByTaskID indicates an expected call of ListByTaskID.
func (mr *MockExecutionServiceMockRecorder) ListByTaskID(ctx, taskID, offset, limit any) *MockExecutionServiceListByTaskIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTaskID", reflect.TypeOf((*MockExecutionService)(nil).ListByTaskID), ctx, taskID, offset, limit)
	return &MockExecutionServiceListByTaskIDCall{Call: call}
}

// MockExecutionServiceListByTaskIDCall wrap *gomock.Call
type MockExecutionServiceListByTaskIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceListByTaskIDCall) Return(arg0 []domain.TaskExecution, arg1 int64, arg2 error) *MockExecutionServiceListByTaskIDCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceListByTaskIDCall) Do(f func(context.Context, int64, int, int) ([]domain.TaskExecution, int64, error)) *MockExecutionServiceListByTaskIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceListByTaskIDCall) DoAndReturn(f func(context.Context, int64, int, int) ([]domain.TaskExecution, int64, error)) *MockExecutionServiceListByTaskIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RequeuePull mocks base method.
func (m *MockExecutionService) RequeuePull(ctx context.Context, executionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequeuePull", ctx, executionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequeuePull indicates an expected call of RequeuePull.
func (mr *MockExecutionServiceMockRecorder) RequeuePull(ctx, executionID any) *MockExecutionServiceRequeuePullCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequeuePull", reflect.TypeOf((*MockExecutionService)(nil).RequeuePull), ctx, executionID)
	return &MockExecutionServiceRequeuePullCall{Call: call}
}

// MockExecutionServiceRequeuePullCall wrap *gomock.Call
type MockExecutionServiceRequeuePullCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceRequeuePullCall) Return(arg0 error) *MockExecutionServiceRequeuePullCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceRequeuePullCall) Do(f func(context.Context, int64) error) *MockExecutionServiceRequeuePullCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceRequeuePullCall) DoAndReturn(f func(context.Context, int64) error) *MockExecutionServiceRequeuePullCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetRunningState mocks base method.
func (m *MockExecutionService) SetRunningState(ctx context.Context, id int64, progress int32, executorNodeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRunningState", ctx, id, progress, executorNodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRunningState indicates an expected call of SetRunningState.
func (mr *MockExecutionServiceMockRecorder) SetRunningState(ctx, id, progress, executorNodeID any) *MockExecutionServiceSetRunningStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRunningState", reflect.TypeOf((*MockExecutionService)(nil).SetRunningState), ctx, id, progress, executorNodeID)
	return &MockExecutionServiceSetRunningStateCall{Call: call}
}

// MockExecutionServiceSetRunningStateCall wrap *gomock.Call
type MockExecutionServiceSetRunningStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceSetRunningStateCall) Return(arg0 error) *MockExecutionServiceSetRunningStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceSetRunningStateCall) Do(f func(context.Context, int64, int32, string) error) *MockExecutionServiceSetRunningStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceSetRunningStateCall) DoAndReturn(f func(context.Context, int64, int32, string) error) *MockExecutionServiceSetRunningStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateRetryResult mocks base method.
func (m *MockExecutionService) UpdateRetryResult(ctx context.Context, id, retryCount, nextRetryTime int64, expectedStatus, status domain.TaskExecutionStatus, progress int32, endTime int64, scheduleParams map[string]string, executorNodeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRetryResult", ctx, id, retryCount, nextRetryTime, expectedStatus, status, progress, endTime, scheduleParams, executorNodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRetryResult indicates an expected call of UpdateRetryResult.
func (mr *MockExecutionServiceMockRecorder) UpdateRetryResult(ctx, id, retryCount, nextRetryTime, expectedStatus, status, progress, endTime, scheduleParams, executorNodeID any) *MockExecutionServiceUpdateRetryResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRetryResult", reflect.TypeOf((*MockExecutionService)(nil).UpdateRetryResult), ctx, id, retryCount, nextRetryTime, expectedStatus, status, progress, endTime, scheduleParams, executorNodeID)
	return &MockExecutionServiceUpdateRetryResultCall{Call: call}
}

// MockExecutionServiceUpdateRetryResultCall wrap *gomock.Call
type MockExecutionServiceUpdateRetryResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceUpdateRetryResultCall) Return(arg0 error) *MockExecutionServiceUpdateRetryResultCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceUpdateRetryResultCall) Do(f func(context.Context, int64, int64, int64, domain.TaskExecutionStatus, domain.TaskExecutionStatus, int32, int64, map[string]string, string) error) *MockExecutionServiceUpdateRetryResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceUpdateRetryResultCall) DoAndReturn(f func(context.Context, int64, int64, int64, domain.TaskExecutionStatus, domain.TaskExecutionStatus, int32, int64, map[string]string, string) error) *MockExecutionServiceUpdateRetryResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateRunningProgress mocks base method.
func (m *MockExecutionService) UpdateRunningProgress(ctx context.Context, id int64, progress int32, executorNodeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunningProgress", ctx, id, progress, executorNodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunningProgress indicates an expected call of UpdateRunningProgress.
func (mr *MockExecutionServiceMockRecorder) UpdateRunningProgress(ctx, id, progress, executorNodeID any) *MockExecutionServiceUpdateRunningProgressCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunningProgress", reflect.TypeOf((*MockExecutionService)(nil).UpdateRunningProgress), ctx, id, progress, executorNodeID)
	return &MockExecutionServiceUpdateRunningProgressCall{Call: call}
}

// MockExecutionServiceUpdateRunningProgressCall wrap *gomock.Call
type MockExecutionServiceUpdateRunningProgressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceUpdateRunningProgressCall) Return(arg0 error) *MockExecutionServiceUpdateRunningProgressCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceUpdateRunningProgressCall) Do(f func(context.Context, int64, int32, string) error) *MockExecutionServiceUpdateRunningProgressCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceUpdateRunningProgressCall) DoAndReturn(f func(context.Context, int64, int32, string) error) *MockExecutionServiceUpdateRunningProgressCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateScheduleResult mocks base method.
func (m *MockExecutionService) UpdateScheduleResult(ctx context.Context, id int64, expectedStatuses []domain.TaskExecutionStatus, status domain.TaskExecutionStatus, progress int32, endTime int64, scheduleParams map[string]string, executorNodeID, taskResult string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduleResult", ctx, id, expectedStatuses, status, progress, endTime, scheduleParams, executorNodeID, taskResult)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScheduleResult indicates an expected call of UpdateScheduleResult.
func (mr *MockExecutionServiceMockRecorder) UpdateScheduleResult(ctx, id, expectedStatuses, status, progress, endTime, scheduleParams, executorNodeID, taskResult any) *MockExecutionServiceUpdateScheduleResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduleResult", reflect.TypeOf((*MockExecutionService)(nil).UpdateScheduleResult), ctx, id, expectedStatuses, status, progress, endTime, scheduleParams, executorNodeID, taskResult)
	return &MockExecutionServiceUpdateScheduleResultCall{Call: call}
}

// MockExecutionServiceUpdateScheduleResultCall wrap *gomock.Call
type MockExecutionServiceUpdateScheduleResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceUpdateScheduleResultCall) Return(arg0 bool, arg1 error) *MockExecutionServiceUpdateScheduleResultCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceUpdateScheduleResultCall) Do(f func(context.Context, int64, []domain.TaskExecutionStatus, domain.TaskExecutionStatus, int32, int64, map[string]string, string, string) (bool, error)) *MockExecutionServiceUpdateScheduleResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceUpdateScheduleResultCall) DoAndReturn(f func(context.Context, int64, []domain.TaskExecutionStatus, domain.TaskExecutionStatus, int32, int64, map[string]string, string, string) (bool, error)) *MockExecutionServiceUpdateScheduleResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateState mocks base method.
func (m *MockExecutionService) UpdateState(ctx context.Context, state domain.ExecutionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateState indicates an expected call of UpdateState.
func (mr *MockExecutionServiceMockRecorder) UpdateState(ctx, state any) *MockExecutionServiceUpdateStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateState", reflect.TypeOf((*MockExecutionService)(nil).UpdateState), ctx, state)
	return &MockExecutionServiceUpdateStateCall{Call: call}
}

// MockExecutionServiceUpdateStateCall wrap *gomock.Call
type MockExecutionServiceUpdateStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionServiceUpdateStateCall) Return(arg0 error) *MockExecutionServiceUpdateStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionServiceUpdateStateCall) Do(f func(context.Context, domain.ExecutionState) error) *MockExecutionServiceUpdateStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionServiceUpdateStateCall) DoAndReturn(f func(context.Context, domain.ExecutionState) error) *MockExecutionServiceUpdateStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
