// Code generated by MockGen. DO NOT EDIT.
// Source: ./log_service.go
//
// Generated by this command:
//
//	mockgen -source=./log_service.go -package=taskmocks -destination=./mocks/log_service.mock.go -typed LogService
//

// Package taskmocks is a generated GoMock package.
package taskmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLogService is a mock of LogService interface.
type MockLogService struct {
	ctrl     *gomock.Controller
	recorder *MockLogServiceMockRecorder
	isgomock struct{}
}

// MockLogServiceMockRecorder is the mock recorder for MockLogService.
type MockLogServiceMockRecorder struct {
	mock *MockLogService
}

// NewMockLogService creates a new mock instance.
func NewMockLogService(ctrl *gomock.Controller) *MockLogService {
	mock := &MockLogService{ctrl: ctrl}
	mock.recorder = &MockLogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogService) EXPECT() *MockLogServiceMockRecorder {
	return m.recorder
}

// AddLog mocks base method.
func (m *MockLogService) AddLog(ctx context.Context, log domain.TaskExecutionLog) (domain.TaskExecutionLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLog", ctx, log)
	ret0, _ := ret[0].(domain.TaskExecutionLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLog indicates an expected call of AddLog.
func (mr *MockLogServiceMockRecorder) AddLog(ctx, log any) *MockLogServiceAddLogCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLog", reflect.TypeOf((*MockLogService)(nil).AddLog), ctx, log)
	return &MockLogServiceAddLogCall{Call: call}
}

// MockLogServiceAddLogCall wrap *gomock.Call
type MockLogServiceAddLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLogServiceAddLogCall) Return(arg0 domain.TaskExecutionLog, arg1 error) *MockLogServiceAddLogCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLogServiceAddLogCall) Do(f func(context.Context, domain.TaskExecutionLog) (domain.TaskExecutionLog, error)) *MockLogServiceAddLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLogServiceAddLogCall) DoAndReturn(f func(context.Context, domain.TaskExecutionLog) (domain.TaskExecutionLog, error)) *MockLogServiceAddLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BatchAddLogs mocks base method.
func (m *MockLogService) BatchAddLogs(ctx context.Context, logs []domain.TaskExecutionLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchAddLogs", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchAddLogs indicates an expected call of BatchAddLogs.
func (mr *MockLogServiceMockRecorder) BatchAddLogs(ctx, logs any) *MockLogServiceBatchAddLogsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchAddLogs", reflect.TypeOf((*MockLogService)(nil).BatchAddLogs), ctx, logs)
	return &MockLogServiceBatchAddLogsCall{Call: call}
}

// MockLogServiceBatchAddLogsCall wrap *gomock.Call
type MockLogServiceBatchAddLogsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLogServiceBatchAddLogsCall) Return(arg0 error) *MockLogServiceBatchAddLogsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLogServiceBatchAddLogsCall) Do(f func(context.Context, []domain.TaskExecutionLog) error) *MockLogServiceBatchAddLogsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLogServiceBatchAddLogsCall) DoAndReturn(f func(context.Context, []domain.TaskExecutionLog) error) *MockLogServiceBatchAddLogsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLogs mocks base method.
func (m *MockLogService) GetLogs(ctx context.Context, executionID, minID int64, limit int) ([]domain.TaskExecutionLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", ctx, executionID, minID, limit)
	ret0, _ := ret[0].([]domain.TaskExecutionLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockLogServiceMockRecorder) GetLogs(ctx, executionID, minID, limit any) *MockLogServiceGetLogsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockLogService)(nil).GetLogs), ctx, executionID, minID, limit)
	return &MockLogServiceGetLogsCall{Call: call}
}

// MockLogServiceGetLogsCall wrap *gomock.Call
type MockLogServiceGetLogsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLogServiceGetLogsCall) Return(arg0 []domain.TaskExecutionLog, arg1 int64, arg2 error) *MockLogServiceGetLogsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLogServiceGetLogsCall) Do(f func(context.Context, int64, int64, int) ([]domain.TaskExecutionLog, int64, error)) *MockLogServiceGetLogsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLogServiceGetLogsCall) DoAndReturn(f func(context.Context, int64, int64, int) ([]domain.TaskExecutionLog, int64, error)) *MockLogServiceGetLogsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
