// Code generated by MockGen. DO NOT EDIT.
// Source: ./routing.go
//
// Generated by this command:
//
//	mockgen -source=./routing.go -package=dispatchermocks -destination=./mocks/routing.mock.go -typed
//

// Package dispatchermocks is a generated GoMock package.
package dispatchermocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	dispatcher "github.com/Duke1616/etask/internal/service/dispatcher"
	gomock "go.uber.org/mock/gomock"
)

// MockRoutePlanner is a mock of RoutePlanner interface.
type MockRoutePlanner struct {
	ctrl     *gomock.Controller
	recorder *MockRoutePlannerMockRecorder
	isgomock struct{}
}

// MockRoutePlannerMockRecorder is the mock recorder for MockRoutePlanner.
type MockRoutePlannerMockRecorder struct {
	mock *MockRoutePlanner
}

// NewMockRoutePlanner creates a new mock instance.
func NewMockRoutePlanner(ctrl *gomock.Controller) *MockRoutePlanner {
	mock := &MockRoutePlanner{ctrl: ctrl}
	mock.recorder = &MockRoutePlannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoutePlanner) EXPECT() *MockRoutePlannerMockRecorder {
	return m.recorder
}

// Plan mocks base method.
func (m *MockRoutePlanner) Plan(ctx context.Context, task domain.Task) (dispatcher.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Plan", ctx, task)
	ret0, _ := ret[0].(dispatcher.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Plan indicates an expected call of Plan.
func (mr *MockRoutePlannerMockRecorder) Plan(ctx, task any) *MockRoutePlannerPlanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plan", reflect.TypeOf((*MockRoutePlanner)(nil).Plan), ctx, task)
	return &MockRoutePlannerPlanCall{Call: call}
}

// MockRoutePlannerPlanCall wrap *gomock.Call
type MockRoutePlannerPlanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoutePlannerPlanCall) Return(arg0 dispatcher.Route, arg1 error) *MockRoutePlannerPlanCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoutePlannerPlanCall) Do(f func(context.Context, domain.Task) (dispatcher.Route, error)) *MockRoutePlannerPlanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoutePlannerPlanCall) DoAndReturn(f func(context.Context, domain.Task) (dispatcher.Route, error)) *MockRoutePlannerPlanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockExecutionPoolReader is a mock of ExecutionPoolReader interface.
type MockExecutionPoolReader struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionPoolReaderMockRecorder
	isgomock struct{}
}

// MockExecutionPoolReaderMockRecorder is the mock recorder for MockExecutionPoolReader.
type MockExecutionPoolReaderMockRecorder struct {
	mock *MockExecutionPoolReader
}

// NewMockExecutionPoolReader creates a new mock instance.
func NewMockExecutionPoolReader(ctrl *gomock.Controller) *MockExecutionPoolReader {
	mock := &MockExecutionPoolReader{ctrl: ctrl}
	mock.recorder = &MockExecutionPoolReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionPoolReader) EXPECT() *MockExecutionPoolReaderMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockExecutionPoolReader) Find(ctx context.Context, name string) (domain.ExecutionPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, name)
	ret0, _ := ret[0].(domain.ExecutionPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockExecutionPoolReaderMockRecorder) Find(ctx, name any) *MockExecutionPoolReaderFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockExecutionPoolReader)(nil).Find), ctx, name)
	return &MockExecutionPoolReaderFindCall{Call: call}
}

// MockExecutionPoolReaderFindCall wrap *gomock.Call
type MockExecutionPoolReaderFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionPoolReaderFindCall) Return(arg0 domain.ExecutionPool, arg1 error) *MockExecutionPoolReaderFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionPoolReaderFindCall) Do(f func(context.Context, string) (domain.ExecutionPool, error)) *MockExecutionPoolReaderFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionPoolReaderFindCall) DoAndReturn(f func(context.Context, string) (domain.ExecutionPool, error)) *MockExecutionPoolReaderFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
