// Code generated by MockGen. DO NOT EDIT.
// Source: ./artifact.go
//
// Generated by this command:
//
//	mockgen -source=./artifact.go -package=repositorymocks -destination=./mocks/artifact.mock.go -typed
//

// Package repositorymocks is a generated GoMock package.
package repositorymocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockArtifactRepository is a mock of ArtifactRepository interface.
type MockArtifactRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArtifactRepositoryMockRecorder
	isgomock struct{}
}

// MockArtifactRepositoryMockRecorder is the mock recorder for MockArtifactRepository.
type MockArtifactRepositoryMockRecorder struct {
	mock *MockArtifactRepository
}

// NewMockArtifactRepository creates a new mock instance.
func NewMockArtifactRepository(ctrl *gomock.Controller) *MockArtifactRepository {
	mock := &MockArtifactRepository{ctrl: ctrl}
	mock.recorder = &MockArtifactRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtifactRepository) EXPECT() *MockArtifactRepositoryMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockArtifactRepository) Activate(ctx context.Context, target domain.ArtifactTarget, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", ctx, target, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockArtifactRepositoryMockRecorder) Activate(ctx, target, id any) *MockArtifactRepositoryActivateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockArtifactRepository)(nil).Activate), ctx, target, id)
	return &MockArtifactRepositoryActivateCall{Call: call}
}

// MockArtifactRepositoryActivateCall wrap *gomock.Call
type MockArtifactRepositoryActivateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockArtifactRepositoryActivateCall) Return(arg0 error) *MockArtifactRepositoryActivateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockArtifactRepositoryActivateCall) Do(f func(context.Context, domain.ArtifactTarget, int64) error) *MockArtifactRepositoryActivateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockArtifactRepositoryActivateCall) DoAndReturn(f func(context.Context, domain.ArtifactTarget, int64) error) *MockArtifactRepositoryActivateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateAndActivate mocks base method.
func (m *MockArtifactRepository) CreateAndActivate(ctx context.Context, release domain.ArtifactRelease) (domain.ArtifactRelease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAndActivate", ctx, release)
	ret0, _ := ret[0].(domain.ArtifactRelease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAndActivate indicates an expected call of CreateAndActivate.
func (mr *MockArtifactRepositoryMockRecorder) CreateAndActivate(ctx, release any) *MockArtifactRepositoryCreateAndActivateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAndActivate", reflect.TypeOf((*MockArtifactRepository)(nil).CreateAndActivate), ctx, release)
	return &MockArtifactRepositoryCreateAndActivateCall{Call: call}
}

// MockArtifactRepositoryCreateAndActivateCall wrap *gomock.Call
type MockArtifactRepositoryCreateAndActivateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockArtifactRepositoryCreateAndActivateCall) Return(arg0 domain.ArtifactRelease, arg1 error) *MockArtifactRepositoryCreateAndActivateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockArtifactRepositoryCreateAndActivateCall) Do(f func(context.Context, domain.ArtifactRelease) (domain.ArtifactRelease, error)) *MockArtifactRepositoryCreateAndActivateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockArtifactRepositoryCreateAndActivateCall) DoAndReturn(f func(context.Context, domain.ArtifactRelease) (domain.ArtifactRelease, error)) *MockArtifactRepositoryCreateAndActivateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindActive mocks base method.
func (m *MockArtifactRepository) FindActive(ctx context.Context, target domain.ArtifactTarget) (domain.ArtifactRelease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActive", ctx, target)
	ret0, _ := ret[0].(domain.ArtifactRelease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActive indicates an expected call of FindActive.
func (mr *MockArtifactRepositoryMockRecorder) FindActive(ctx, target any) *MockArtifactRepositoryFindActiveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActive", reflect.TypeOf((*MockArtifactRepository)(nil).FindActive), ctx, target)
	return &MockArtifactRepositoryFindActiveCall{Call: call}
}

// MockArtifactRepositoryFindActiveCall wrap *gomock.Call
type MockArtifactRepositoryFindActiveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockArtifactRepositoryFindActiveCall) Return(arg0 domain.ArtifactRelease, arg1 error) *MockArtifactRepositoryFindActiveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockArtifactRepositoryFindActiveCall) Do(f func(context.Context, domain.ArtifactTarget) (domain.ArtifactRelease, error)) *MockArtifactRepositoryFindActiveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockArtifactRepositoryFindActiveCall) DoAndReturn(f func(context.Context, domain.ArtifactTarget) (domain.ArtifactRelease, error)) *MockArtifactRepositoryFindActiveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByID mocks base method.
func (m *MockArtifactRepository) FindByID(ctx context.Context, id int64) (domain.ArtifactRelease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.ArtifactRelease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockArtifactRepositoryMockRecorder) FindByID(ctx, id any) *MockArtifactRepositoryFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockArtifactRepository)(nil).FindByID), ctx, id)
	return &MockArtifactRepositoryFindByIDCall{Call: call}
}

// MockArtifactRepositoryFindByIDCall wrap *gomock.Call
type MockArtifactRepositoryFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockArtifactRepositoryFindByIDCall) Return(arg0 domain.ArtifactRelease, arg1 error) *MockArtifactRepositoryFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockArtifactRepositoryFindByIDCall) Do(f func(context.Context, int64) (domain.ArtifactRelease, error)) *MockArtifactRepositoryFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockArtifactRepositoryFindByIDCall) DoAndReturn(f func(context.Context, int64) (domain.ArtifactRelease, error)) *MockArtifactRepositoryFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProject mocks base method.
func (m *MockArtifactRepository) GetProject(ctx context.Context, projectID int64) (domain.CodebookProject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, projectID)
	ret0, _ := ret[0].(domain.CodebookProject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockArtifactRepositoryMockRecorder) GetProject(ctx, projectID any) *MockArtifactRepositoryGetProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockArtifactRepository)(nil).GetProject), ctx, projectID)
	return &MockArtifactRepositoryGetProjectCall{Call: call}
}

// MockArtifactRepositoryGetProjectCall wrap *gomock.Call
type MockArtifactRepositoryGetProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockArtifactRepositoryGetProjectCall) Return(arg0 domain.CodebookProject, arg1 error) *MockArtifactRepositoryGetProjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockArtifactRepositoryGetProjectCall) Do(f func(context.Context, int64) (domain.CodebookProject, error)) *MockArtifactRepositoryGetProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockArtifactRepositoryGetProjectCall) DoAndReturn(f func(context.Context, int64) (domain.CodebookProject, error)) *MockArtifactRepositoryGetProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockArtifactRepository) List(ctx context.Context, target domain.ArtifactTarget, offset, limit int64) ([]domain.ArtifactRelease, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, target, offset, limit)
	ret0, _ := ret[0].([]domain.ArtifactRelease)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockArtifactRepositoryMockRecorder) List(ctx, target, offset, limit any) *MockArtifactRepositoryListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockArtifactRepository)(nil).List), ctx, target, offset, limit)
	return &MockArtifactRepositoryListCall{Call: call}
}

// MockArtifactRepositoryListCall wrap *gomock.Call
type MockArtifactRepositoryListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockArtifactRepositoryListCall) Return(arg0 []domain.ArtifactRelease, arg1 int64, arg2 error) *MockArtifactRepositoryListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockArtifactRepositoryListCall) Do(f func(context.Context, domain.ArtifactTarget, int64, int64) ([]domain.ArtifactRelease, int64, error)) *MockArtifactRepositoryListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockArtifactRepositoryListCall) DoAndReturn(f func(context.Context, domain.ArtifactTarget, int64, int64) ([]domain.ArtifactRelease, int64, error)) *MockArtifactRepositoryListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListActiveLibraries mocks base method.
func (m *MockArtifactRepository) ListActiveLibraries(ctx context.Context) ([]domain.ArtifactRelease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveLibraries", ctx)
	ret0, _ := ret[0].([]domain.ArtifactRelease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveLibraries indicates an expected call of ListActiveLibraries.
func (mr *MockArtifactRepositoryMockRecorder) ListActiveLibraries(ctx any) *MockArtifactRepositoryListActiveLibrariesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveLibraries", reflect.TypeOf((*MockArtifactRepository)(nil).ListActiveLibraries), ctx)
	return &MockArtifactRepositoryListActiveLibrariesCall{Call: call}
}

// MockArtifactRepositoryListActiveLibrariesCall wrap *gomock.Call
type MockArtifactRepositoryListActiveLibrariesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockArtifactRepositoryListActiveLibrariesCall) Return(arg0 []domain.ArtifactRelease, arg1 error) *MockArtifactRepositoryListActiveLibrariesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockArtifactRepositoryListActiveLibrariesCall) Do(f func(context.Context) ([]domain.ArtifactRelease, error)) *MockArtifactRepositoryListActiveLibrariesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockArtifactRepositoryListActiveLibrariesCall) DoAndReturn(f func(context.Context) ([]domain.ArtifactRelease, error)) *MockArtifactRepositoryListActiveLibrariesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SnapshotFiles mocks base method.
func (m *MockArtifactRepository) SnapshotFiles(ctx context.Context, target domain.ArtifactTarget) ([]domain.ArtifactFile, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotFiles", ctx, target)
	ret0, _ := ret[0].([]domain.ArtifactFile)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SnapshotFiles indicates an expected call of SnapshotFiles.
func (mr *MockArtifactRepositoryMockRecorder) SnapshotFiles(ctx, target any) *MockArtifactRepositorySnapshotFilesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotFiles", reflect.TypeOf((*MockArtifactRepository)(nil).SnapshotFiles), ctx, target)
	return &MockArtifactRepositorySnapshotFilesCall{Call: call}
}

// MockArtifactRepositorySnapshotFilesCall wrap *gomock.Call
type MockArtifactRepositorySnapshotFilesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockArtifactRepositorySnapshotFilesCall) Return(arg0 []domain.ArtifactFile, arg1 int64, arg2 error) *MockArtifactRepositorySnapshotFilesCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockArtifactRepositorySnapshotFilesCall) Do(f func(context.Context, domain.ArtifactTarget) ([]domain.ArtifactFile, int64, error)) *MockArtifactRepositorySnapshotFilesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockArtifactRepositorySnapshotFilesCall) DoAndReturn(f func(context.Context, domain.ArtifactTarget) ([]domain.ArtifactFile, int64, error)) *MockArtifactRepositorySnapshotFilesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
