// Code generated by MockGen. DO NOT EDIT.
// Source: ./execution_cancellation.go
//
// Generated by this command:
//
//	mockgen -source=./execution_cancellation.go -package=repositorymocks -destination=./mocks/execution_cancellation.mock.go -typed
//

// Package repositorymocks is a generated GoMock package.
package repositorymocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutionCancellationRepository is a mock of ExecutionCancellationRepository interface.
type MockExecutionCancellationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionCancellationRepositoryMockRecorder
	isgomock struct{}
}

// MockExecutionCancellationRepositoryMockRecorder is the mock recorder for MockExecutionCancellationRepository.
type MockExecutionCancellationRepositoryMockRecorder struct {
	mock *MockExecutionCancellationRepository
}

// NewMockExecutionCancellationRepository creates a new mock instance.
func NewMockExecutionCancellationRepository(ctrl *gomock.Controller) *MockExecutionCancellationRepository {
	mock := &MockExecutionCancellationRepository{ctrl: ctrl}
	mock.recorder = &MockExecutionCancellationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionCancellationRepository) EXPECT() *MockExecutionCancellationRepositoryMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockExecutionCancellationRepository) Attach(ctx context.Context, execution domain.TaskExecution) (domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, execution)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attach indicates an expected call of Attach.
func (mr *MockExecutionCancellationRepositoryMockRecorder) Attach(ctx, execution any) *MockExecutionCancellationRepositoryAttachCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockExecutionCancellationRepository)(nil).Attach), ctx, execution)
	return &MockExecutionCancellationRepositoryAttachCall{Call: call}
}

// MockExecutionCancellationRepositoryAttachCall wrap *gomock.Call
type MockExecutionCancellationRepositoryAttachCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionCancellationRepositoryAttachCall) Return(arg0 domain.TaskExecution, arg1 error) *MockExecutionCancellationRepositoryAttachCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionCancellationRepositoryAttachCall) Do(f func(context.Context, domain.TaskExecution) (domain.TaskExecution, error)) *MockExecutionCancellationRepositoryAttachCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionCancellationRepositoryAttachCall) DoAndReturn(f func(context.Context, domain.TaskExecution) (domain.TaskExecution, error)) *MockExecutionCancellationRepositoryAttachCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListPending mocks base method.
func (m *MockExecutionCancellationRepository) ListPending(ctx context.Context, limit int) ([]domain.ExecutionCancellation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, limit)
	ret0, _ := ret[0].([]domain.ExecutionCancellation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockExecutionCancellationRepositoryMockRecorder) ListPending(ctx, limit any) *MockExecutionCancellationRepositoryListPendingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockExecutionCancellationRepository)(nil).ListPending), ctx, limit)
	return &MockExecutionCancellationRepositoryListPendingCall{Call: call}
}

// MockExecutionCancellationRepositoryListPendingCall wrap *gomock.Call
type MockExecutionCancellationRepositoryListPendingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionCancellationRepositoryListPendingCall) Return(arg0 []domain.ExecutionCancellation, arg1 error) *MockExecutionCancellationRepositoryListPendingCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionCancellationRepositoryListPendingCall) Do(f func(context.Context, int) ([]domain.ExecutionCancellation, error)) *MockExecutionCancellationRepositoryListPendingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionCancellationRepositoryListPendingCall) DoAndReturn(f func(context.Context, int) ([]domain.ExecutionCancellation, error)) *MockExecutionCancellationRepositoryListPendingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarkFailed mocks base method.
func (m *MockExecutionCancellationRepository) MarkFailed(ctx context.Context, id int64, reason string, nextAttemptAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, reason, nextAttemptAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockExecutionCancellationRepositoryMockRecorder) MarkFailed(ctx, id, reason, nextAttemptAt any) *MockExecutionCancellationRepositoryMarkFailedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockExecutionCancellationRepository)(nil).MarkFailed), ctx, id, reason, nextAttemptAt)
	return &MockExecutionCancellationRepositoryMarkFailedCall{Call: call}
}

// MockExecutionCancellationRepositoryMarkFailedCall wrap *gomock.Call
type MockExecutionCancellationRepositoryMarkFailedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionCancellationRepositoryMarkFailedCall) Return(arg0 error) *MockExecutionCancellationRepositoryMarkFailedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionCancellationRepositoryMarkFailedCall) Do(f func(context.Context, int64, string, int64) error) *MockExecutionCancellationRepositoryMarkFailedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionCancellationRepositoryMarkFailedCall) DoAndReturn(f func(context.Context, int64, string, int64) error) *MockExecutionCancellationRepositoryMarkFailedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarkSent mocks base method.
func (m *MockExecutionCancellationRepository) MarkSent(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSent indicates an expected call of MarkSent.
func (mr *MockExecutionCancellationRepositoryMockRecorder) MarkSent(ctx, id any) *MockExecutionCancellationRepositoryMarkSentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSent", reflect.TypeOf((*MockExecutionCancellationRepository)(nil).MarkSent), ctx, id)
	return &MockExecutionCancellationRepositoryMarkSentCall{Call: call}
}

// MockExecutionCancellationRepositoryMarkSentCall wrap *gomock.Call
type MockExecutionCancellationRepositoryMarkSentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionCancellationRepositoryMarkSentCall) Return(arg0 error) *MockExecutionCancellationRepositoryMarkSentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionCancellationRepositoryMarkSentCall) Do(f func(context.Context, int64) error) *MockExecutionCancellationRepositoryMarkSentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionCancellationRepositoryMarkSentCall) DoAndReturn(f func(context.Context, int64) error) *MockExecutionCancellationRepositoryMarkSentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Request mocks base method.
func (m *MockExecutionCancellationRepository) Request(ctx context.Context, executionID int64, requestID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, executionID, requestID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockExecutionCancellationRepositoryMockRecorder) Request(ctx, executionID, requestID, reason any) *MockExecutionCancellationRepositoryRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockExecutionCancellationRepository)(nil).Request), ctx, executionID, requestID, reason)
	return &MockExecutionCancellationRepositoryRequestCall{Call: call}
}

// MockExecutionCancellationRepositoryRequestCall wrap *gomock.Call
type MockExecutionCancellationRepositoryRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionCancellationRepositoryRequestCall) Return(arg0 error) *MockExecutionCancellationRepositoryRequestCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionCancellationRepositoryRequestCall) Do(f func(context.Context, int64, string, string) error) *MockExecutionCancellationRepositoryRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionCancellationRepositoryRequestCall) DoAndReturn(f func(context.Context, int64, string, string) error) *MockExecutionCancellationRepositoryRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
