// Code generated by MockGen. DO NOT EDIT.
// Source: ./execution_pool.go
//
// Generated by this command:
//
//	mockgen -source=./execution_pool.go -package=repositorymocks -destination=./mocks/execution_pool.mock.go -exclude_interfaces=ExecutionPoolBindingRepository -typed
//

// Package repositorymocks is a generated GoMock package.
package repositorymocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutionPoolRepository is a mock of ExecutionPoolRepository interface.
type MockExecutionPoolRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionPoolRepositoryMockRecorder
	isgomock struct{}
}

// MockExecutionPoolRepositoryMockRecorder is the mock recorder for MockExecutionPoolRepository.
type MockExecutionPoolRepositoryMockRecorder struct {
	mock *MockExecutionPoolRepository
}

// NewMockExecutionPoolRepository creates a new mock instance.
func NewMockExecutionPoolRepository(ctrl *gomock.Controller) *MockExecutionPoolRepository {
	mock := &MockExecutionPoolRepository{ctrl: ctrl}
	mock.recorder = &MockExecutionPoolRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionPoolRepository) EXPECT() *MockExecutionPoolRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockExecutionPoolRepository) Count(ctx context.Context, keyword string, kind domain.ExecutionPoolKind, transport domain.ExecutionTransport, dispatchMode domain.ExecMode, status domain.ExecutionPoolStatus) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, keyword, kind, transport, dispatchMode, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockExecutionPoolRepositoryMockRecorder) Count(ctx, keyword, kind, transport, dispatchMode, status any) *MockExecutionPoolRepositoryCountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockExecutionPoolRepository)(nil).Count), ctx, keyword, kind, transport, dispatchMode, status)
	return &MockExecutionPoolRepositoryCountCall{Call: call}
}

// MockExecutionPoolRepositoryCountCall wrap *gomock.Call
type MockExecutionPoolRepositoryCountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionPoolRepositoryCountCall) Return(arg0 int64, arg1 error) *MockExecutionPoolRepositoryCountCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionPoolRepositoryCountCall) Do(f func(context.Context, string, domain.ExecutionPoolKind, domain.ExecutionTransport, domain.ExecMode, domain.ExecutionPoolStatus) (int64, error)) *MockExecutionPoolRepositoryCountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionPoolRepositoryCountCall) DoAndReturn(f func(context.Context, string, domain.ExecutionPoolKind, domain.ExecutionTransport, domain.ExecMode, domain.ExecutionPoolStatus) (int64, error)) *MockExecutionPoolRepositoryCountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Disable mocks base method.
func (m *MockExecutionPoolRepository) Disable(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockExecutionPoolRepositoryMockRecorder) Disable(ctx, name any) *MockExecutionPoolRepositoryDisableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockExecutionPoolRepository)(nil).Disable), ctx, name)
	return &MockExecutionPoolRepositoryDisableCall{Call: call}
}

// MockExecutionPoolRepositoryDisableCall wrap *gomock.Call
type MockExecutionPoolRepositoryDisableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionPoolRepositoryDisableCall) Return(arg0 error) *MockExecutionPoolRepositoryDisableCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionPoolRepositoryDisableCall) Do(f func(context.Context, string) error) *MockExecutionPoolRepositoryDisableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionPoolRepositoryDisableCall) DoAndReturn(f func(context.Context, string) error) *MockExecutionPoolRepositoryDisableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Find mocks base method.
func (m *MockExecutionPoolRepository) Find(ctx context.Context, name string) (domain.ExecutionPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, name)
	ret0, _ := ret[0].(domain.ExecutionPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockExecutionPoolRepositoryMockRecorder) Find(ctx, name any) *MockExecutionPoolRepositoryFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockExecutionPoolRepository)(nil).Find), ctx, name)
	return &MockExecutionPoolRepositoryFindCall{Call: call}
}

// MockExecutionPoolRepositoryFindCall wrap *gomock.Call
type MockExecutionPoolRepositoryFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionPoolRepositoryFindCall) Return(arg0 domain.ExecutionPool, arg1 error) *MockExecutionPoolRepositoryFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionPoolRepositoryFindCall) Do(f func(context.Context, string) (domain.ExecutionPool, error)) *MockExecutionPoolRepositoryFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionPoolRepositoryFindCall) DoAndReturn(f func(context.Context, string) (domain.ExecutionPool, error)) *MockExecutionPoolRepositoryFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockExecutionPoolRepository) List(ctx context.Context, offset, limit int64, keyword string, kind domain.ExecutionPoolKind, transport domain.ExecutionTransport, dispatchMode domain.ExecMode, status domain.ExecutionPoolStatus) ([]domain.ExecutionPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, keyword, kind, transport, dispatchMode, status)
	ret0, _ := ret[0].([]domain.ExecutionPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockExecutionPoolRepositoryMockRecorder) List(ctx, offset, limit, keyword, kind, transport, dispatchMode, status any) *MockExecutionPoolRepositoryListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExecutionPoolRepository)(nil).List), ctx, offset, limit, keyword, kind, transport, dispatchMode, status)
	return &MockExecutionPoolRepositoryListCall{Call: call}
}

// MockExecutionPoolRepositoryListCall wrap *gomock.Call
type MockExecutionPoolRepositoryListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionPoolRepositoryListCall) Return(arg0 []domain.ExecutionPool, arg1 error) *MockExecutionPoolRepositoryListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionPoolRepositoryListCall) Do(f func(context.Context, int64, int64, string, domain.ExecutionPoolKind, domain.ExecutionTransport, domain.ExecMode, domain.ExecutionPoolStatus) ([]domain.ExecutionPool, error)) *MockExecutionPoolRepositoryListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionPoolRepositoryListCall) DoAndReturn(f func(context.Context, int64, int64, string, domain.ExecutionPoolKind, domain.ExecutionTransport, domain.ExecMode, domain.ExecutionPoolStatus) ([]domain.ExecutionPool, error)) *MockExecutionPoolRepositoryListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByKind mocks base method.
func (m *MockExecutionPoolRepository) ListByKind(ctx context.Context, kind domain.ExecutionPoolKind) ([]domain.ExecutionPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByKind", ctx, kind)
	ret0, _ := ret[0].([]domain.ExecutionPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByKind indicates an expected call of ListByKind.
func (mr *MockExecutionPoolRepositoryMockRecorder) ListByKind(ctx, kind any) *MockExecutionPoolRepositoryListByKindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByKind", reflect.TypeOf((*MockExecutionPoolRepository)(nil).ListByKind), ctx, kind)
	return &MockExecutionPoolRepositoryListByKindCall{Call: call}
}

// MockExecutionPoolRepositoryListByKindCall wrap *gomock.Call
type MockExecutionPoolRepositoryListByKindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionPoolRepositoryListByKindCall) Return(arg0 []domain.ExecutionPool, arg1 error) *MockExecutionPoolRepositoryListByKindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionPoolRepositoryListByKindCall) Do(f func(context.Context, domain.ExecutionPoolKind) ([]domain.ExecutionPool, error)) *MockExecutionPoolRepositoryListByKindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionPoolRepositoryListByKindCall) DoAndReturn(f func(context.Context, domain.ExecutionPoolKind) ([]domain.ExecutionPool, error)) *MockExecutionPoolRepositoryListByKindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByNames mocks base method.
func (m *MockExecutionPoolRepository) ListByNames(ctx context.Context, names []string, kind domain.ExecutionPoolKind, status domain.ExecutionPoolStatus, keyword string) ([]domain.ExecutionPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByNames", ctx, names, kind, status, keyword)
	ret0, _ := ret[0].([]domain.ExecutionPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByNames indicates an expected call of ListByNames.
func (mr *MockExecutionPoolRepositoryMockRecorder) ListByNames(ctx, names, kind, status, keyword any) *MockExecutionPoolRepositoryListByNamesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByNames", reflect.TypeOf((*MockExecutionPoolRepository)(nil).ListByNames), ctx, names, kind, status, keyword)
	return &MockExecutionPoolRepositoryListByNamesCall{Call: call}
}

// MockExecutionPoolRepositoryListByNamesCall wrap *gomock.Call
type MockExecutionPoolRepositoryListByNamesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionPoolRepositoryListByNamesCall) Return(arg0 []domain.ExecutionPool, arg1 error) *MockExecutionPoolRepositoryListByNamesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionPoolRepositoryListByNamesCall) Do(f func(context.Context, []string, domain.ExecutionPoolKind, domain.ExecutionPoolStatus, string) ([]domain.ExecutionPool, error)) *MockExecutionPoolRepositoryListByNamesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionPoolRepositoryListByNamesCall) DoAndReturn(f func(context.Context, []string, domain.ExecutionPoolKind, domain.ExecutionPoolStatus, string) ([]domain.ExecutionPool, error)) *MockExecutionPoolRepositoryListByNamesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Upsert mocks base method.
func (m *MockExecutionPoolRepository) Upsert(ctx context.Context, pool domain.ExecutionPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockExecutionPoolRepositoryMockRecorder) Upsert(ctx, pool any) *MockExecutionPoolRepositoryUpsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockExecutionPoolRepository)(nil).Upsert), ctx, pool)
	return &MockExecutionPoolRepositoryUpsertCall{Call: call}
}

// MockExecutionPoolRepositoryUpsertCall wrap *gomock.Call
type MockExecutionPoolRepositoryUpsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionPoolRepositoryUpsertCall) Return(arg0 error) *MockExecutionPoolRepositoryUpsertCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionPoolRepositoryUpsertCall) Do(f func(context.Context, domain.ExecutionPool) error) *MockExecutionPoolRepositoryUpsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionPoolRepositoryUpsertCall) DoAndReturn(f func(context.Context, domain.ExecutionPool) error) *MockExecutionPoolRepositoryUpsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
