// Code generated by MockGen. DO NOT EDIT.
// Source: ./project_source.go
//
// Generated by this command:
//
//	mockgen -source=./project_source.go -package=repositorymocks -destination=./mocks/project_source.mock.go -typed
//

// Package repositorymocks is a generated GoMock package.
package repositorymocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectSourceRepository is a mock of ProjectSourceRepository interface.
type MockProjectSourceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectSourceRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectSourceRepositoryMockRecorder is the mock recorder for MockProjectSourceRepository.
type MockProjectSourceRepositoryMockRecorder struct {
	mock *MockProjectSourceRepository
}

// NewMockProjectSourceRepository creates a new mock instance.
func NewMockProjectSourceRepository(ctrl *gomock.Controller) *MockProjectSourceRepository {
	mock := &MockProjectSourceRepository{ctrl: ctrl}
	mock.recorder = &MockProjectSourceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectSourceRepository) EXPECT() *MockProjectSourceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectSourceRepository) Create(ctx context.Context, source domain.ProjectSource) (domain.ProjectSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, source)
	ret0, _ := ret[0].(domain.ProjectSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProjectSourceRepositoryMockRecorder) Create(ctx, source any) *MockProjectSourceRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectSourceRepository)(nil).Create), ctx, source)
	return &MockProjectSourceRepositoryCreateCall{Call: call}
}

// MockProjectSourceRepositoryCreateCall wrap *gomock.Call
type MockProjectSourceRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectSourceRepositoryCreateCall) Return(arg0 domain.ProjectSource, arg1 error) *MockProjectSourceRepositoryCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectSourceRepositoryCreateCall) Do(f func(context.Context, domain.ProjectSource) (domain.ProjectSource, error)) *MockProjectSourceRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectSourceRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.ProjectSource) (domain.ProjectSource, error)) *MockProjectSourceRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByID mocks base method.
func (m *MockProjectSourceRepository) FindByID(ctx context.Context, id int64) (domain.ProjectSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.ProjectSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProjectSourceRepositoryMockRecorder) FindByID(ctx, id any) *MockProjectSourceRepositoryFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProjectSourceRepository)(nil).FindByID), ctx, id)
	return &MockProjectSourceRepositoryFindByIDCall{Call: call}
}

// MockProjectSourceRepositoryFindByIDCall wrap *gomock.Call
type MockProjectSourceRepositoryFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectSourceRepositoryFindByIDCall) Return(arg0 domain.ProjectSource, arg1 error) *MockProjectSourceRepositoryFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectSourceRepositoryFindByIDCall) Do(f func(context.Context, int64) (domain.ProjectSource, error)) *MockProjectSourceRepositoryFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectSourceRepositoryFindByIDCall) DoAndReturn(f func(context.Context, int64) (domain.ProjectSource, error)) *MockProjectSourceRepositoryFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByRevision mocks base method.
func (m *MockProjectSourceRepository) FindByRevision(ctx context.Context, projectID, sourceRevision int64) (domain.ProjectSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRevision", ctx, projectID, sourceRevision)
	ret0, _ := ret[0].(domain.ProjectSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRevision indicates an expected call of FindByRevision.
func (mr *MockProjectSourceRepositoryMockRecorder) FindByRevision(ctx, projectID, sourceRevision any) *MockProjectSourceRepositoryFindByRevisionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRevision", reflect.TypeOf((*MockProjectSourceRepository)(nil).FindByRevision), ctx, projectID, sourceRevision)
	return &MockProjectSourceRepositoryFindByRevisionCall{Call: call}
}

// MockProjectSourceRepositoryFindByRevisionCall wrap *gomock.Call
type MockProjectSourceRepositoryFindByRevisionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectSourceRepositoryFindByRevisionCall) Return(arg0 domain.ProjectSource, arg1 error) *MockProjectSourceRepositoryFindByRevisionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectSourceRepositoryFindByRevisionCall) Do(f func(context.Context, int64, int64) (domain.ProjectSource, error)) *MockProjectSourceRepositoryFindByRevisionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectSourceRepositoryFindByRevisionCall) DoAndReturn(f func(context.Context, int64, int64) (domain.ProjectSource, error)) *MockProjectSourceRepositoryFindByRevisionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProject mocks base method.
func (m *MockProjectSourceRepository) GetProject(ctx context.Context, projectID int64) (domain.CodebookProject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, projectID)
	ret0, _ := ret[0].(domain.CodebookProject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockProjectSourceRepositoryMockRecorder) GetProject(ctx, projectID any) *MockProjectSourceRepositoryGetProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockProjectSourceRepository)(nil).GetProject), ctx, projectID)
	return &MockProjectSourceRepositoryGetProjectCall{Call: call}
}

// MockProjectSourceRepositoryGetProjectCall wrap *gomock.Call
type MockProjectSourceRepositoryGetProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectSourceRepositoryGetProjectCall) Return(arg0 domain.CodebookProject, arg1 error) *MockProjectSourceRepositoryGetProjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectSourceRepositoryGetProjectCall) Do(f func(context.Context, int64) (domain.CodebookProject, error)) *MockProjectSourceRepositoryGetProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectSourceRepositoryGetProjectCall) DoAndReturn(f func(context.Context, int64) (domain.CodebookProject, error)) *MockProjectSourceRepositoryGetProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SourceFiles mocks base method.
func (m *MockProjectSourceRepository) SourceFiles(ctx context.Context, target domain.ArtifactTarget) ([]domain.ArtifactFile, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SourceFiles", ctx, target)
	ret0, _ := ret[0].([]domain.ArtifactFile)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SourceFiles indicates an expected call of SourceFiles.
func (mr *MockProjectSourceRepositoryMockRecorder) SourceFiles(ctx, target any) *MockProjectSourceRepositorySourceFilesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceFiles", reflect.TypeOf((*MockProjectSourceRepository)(nil).SourceFiles), ctx, target)
	return &MockProjectSourceRepositorySourceFilesCall{Call: call}
}

// MockProjectSourceRepositorySourceFilesCall wrap *gomock.Call
type MockProjectSourceRepositorySourceFilesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectSourceRepositorySourceFilesCall) Return(arg0 []domain.ArtifactFile, arg1 int64, arg2 error) *MockProjectSourceRepositorySourceFilesCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectSourceRepositorySourceFilesCall) Do(f func(context.Context, domain.ArtifactTarget) ([]domain.ArtifactFile, int64, error)) *MockProjectSourceRepositorySourceFilesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectSourceRepositorySourceFilesCall) DoAndReturn(f func(context.Context, domain.ArtifactTarget) ([]domain.ArtifactFile, int64, error)) *MockProjectSourceRepositorySourceFilesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
