// Code generated by MockGen. DO NOT EDIT.
// Source: ./project_deletion.go
//
// Generated by this command:
//
//	mockgen -source=./project_deletion.go -package=repositorymocks -destination=./mocks/project_deletion.mock.go -typed
//

// Package repositorymocks is a generated GoMock package.
package repositorymocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectDeletionRepository is a mock of ProjectDeletionRepository interface.
type MockProjectDeletionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectDeletionRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectDeletionRepositoryMockRecorder is the mock recorder for MockProjectDeletionRepository.
type MockProjectDeletionRepositoryMockRecorder struct {
	mock *MockProjectDeletionRepository
}

// NewMockProjectDeletionRepository creates a new mock instance.
func NewMockProjectDeletionRepository(ctrl *gomock.Controller) *MockProjectDeletionRepository {
	mock := &MockProjectDeletionRepository{ctrl: ctrl}
	mock.recorder = &MockProjectDeletionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectDeletionRepository) EXPECT() *MockProjectDeletionRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockProjectDeletionRepository) Delete(ctx context.Context, projectID int64, projectName string) (domain.ProjectDeleteCleanup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, projectID, projectName)
	ret0, _ := ret[0].(domain.ProjectDeleteCleanup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectDeletionRepositoryMockRecorder) Delete(ctx, projectID, projectName any) *MockProjectDeletionRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectDeletionRepository)(nil).Delete), ctx, projectID, projectName)
	return &MockProjectDeletionRepositoryDeleteCall{Call: call}
}

// MockProjectDeletionRepositoryDeleteCall wrap *gomock.Call
type MockProjectDeletionRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectDeletionRepositoryDeleteCall) Return(arg0 domain.ProjectDeleteCleanup, arg1 error) *MockProjectDeletionRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectDeletionRepositoryDeleteCall) Do(f func(context.Context, int64, string) (domain.ProjectDeleteCleanup, error)) *MockProjectDeletionRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectDeletionRepositoryDeleteCall) DoAndReturn(f func(context.Context, int64, string) (domain.ProjectDeleteCleanup, error)) *MockProjectDeletionRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Preview mocks base method.
func (m *MockProjectDeletionRepository) Preview(ctx context.Context, projectID int64) (domain.ProjectDeleteImpact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview", ctx, projectID)
	ret0, _ := ret[0].(domain.ProjectDeleteImpact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preview indicates an expected call of Preview.
func (mr *MockProjectDeletionRepositoryMockRecorder) Preview(ctx, projectID any) *MockProjectDeletionRepositoryPreviewCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockProjectDeletionRepository)(nil).Preview), ctx, projectID)
	return &MockProjectDeletionRepositoryPreviewCall{Call: call}
}

// MockProjectDeletionRepositoryPreviewCall wrap *gomock.Call
type MockProjectDeletionRepositoryPreviewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectDeletionRepositoryPreviewCall) Return(arg0 domain.ProjectDeleteImpact, arg1 error) *MockProjectDeletionRepositoryPreviewCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectDeletionRepositoryPreviewCall) Do(f func(context.Context, int64) (domain.ProjectDeleteImpact, error)) *MockProjectDeletionRepositoryPreviewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectDeletionRepositoryPreviewCall) DoAndReturn(f func(context.Context, int64) (domain.ProjectDeleteImpact, error)) *MockProjectDeletionRepositoryPreviewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
