// Code generated by MockGen. DO NOT EDIT.
// Source: ./runner.go
//
// Generated by this command:
//
//	mockgen -source=./runner.go -package=repositorymocks -destination=./mocks/runner.mock.go -typed
//

// Package repositorymocks is a generated GoMock package.
package repositorymocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRunnerRepository is a mock of RunnerRepository interface.
type MockRunnerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerRepositoryMockRecorder
	isgomock struct{}
}

// MockRunnerRepositoryMockRecorder is the mock recorder for MockRunnerRepository.
type MockRunnerRepositoryMockRecorder struct {
	mock *MockRunnerRepository
}

// NewMockRunnerRepository creates a new mock instance.
func NewMockRunnerRepository(ctrl *gomock.Controller) *MockRunnerRepository {
	mock := &MockRunnerRepository{ctrl: ctrl}
	mock.recorder = &MockRunnerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunnerRepository) EXPECT() *MockRunnerRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRunnerRepository) Count(ctx context.Context, keyword, kind string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, keyword, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRunnerRepositoryMockRecorder) Count(ctx, keyword, kind any) *MockRunnerRepositoryCountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRunnerRepository)(nil).Count), ctx, keyword, kind)
	return &MockRunnerRepositoryCountCall{Call: call}
}

// MockRunnerRepositoryCountCall wrap *gomock.Call
type MockRunnerRepositoryCountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryCountCall) Return(arg0 int64, arg1 error) *MockRunnerRepositoryCountCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryCountCall) Do(f func(context.Context, string, string) (int64, error)) *MockRunnerRepositoryCountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryCountCall) DoAndReturn(f func(context.Context, string, string) (int64, error)) *MockRunnerRepositoryCountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CountExcludeCodebookID mocks base method.
func (m *MockRunnerRepository) CountExcludeCodebookID(ctx context.Context, codebookID int64, keyword, kind string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountExcludeCodebookID", ctx, codebookID, keyword, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountExcludeCodebookID indicates an expected call of CountExcludeCodebookID.
func (mr *MockRunnerRepositoryMockRecorder) CountExcludeCodebookID(ctx, codebookID, keyword, kind any) *MockRunnerRepositoryCountExcludeCodebookIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountExcludeCodebookID", reflect.TypeOf((*MockRunnerRepository)(nil).CountExcludeCodebookID), ctx, codebookID, keyword, kind)
	return &MockRunnerRepositoryCountExcludeCodebookIDCall{Call: call}
}

// MockRunnerRepositoryCountExcludeCodebookIDCall wrap *gomock.Call
type MockRunnerRepositoryCountExcludeCodebookIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryCountExcludeCodebookIDCall) Return(arg0 int64, arg1 error) *MockRunnerRepositoryCountExcludeCodebookIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryCountExcludeCodebookIDCall) Do(f func(context.Context, int64, string, string) (int64, error)) *MockRunnerRepositoryCountExcludeCodebookIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryCountExcludeCodebookIDCall) DoAndReturn(f func(context.Context, int64, string, string) (int64, error)) *MockRunnerRepositoryCountExcludeCodebookIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockRunnerRepository) Create(ctx context.Context, req domain.Runner) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRunnerRepositoryMockRecorder) Create(ctx, req any) *MockRunnerRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRunnerRepository)(nil).Create), ctx, req)
	return &MockRunnerRepositoryCreateCall{Call: call}
}

// MockRunnerRepositoryCreateCall wrap *gomock.Call
type MockRunnerRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryCreateCall) Return(arg0 int64, arg1 error) *MockRunnerRepositoryCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryCreateCall) Do(f func(context.Context, domain.Runner) (int64, error)) *MockRunnerRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.Runner) (int64, error)) *MockRunnerRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockRunnerRepository) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRunnerRepositoryMockRecorder) Delete(ctx, id any) *MockRunnerRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRunnerRepository)(nil).Delete), ctx, id)
	return &MockRunnerRepositoryDeleteCall{Call: call}
}

// MockRunnerRepositoryDeleteCall wrap *gomock.Call
type MockRunnerRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryDeleteCall) Return(arg0 int64, arg1 error) *MockRunnerRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryDeleteCall) Do(f func(context.Context, int64) (int64, error)) *MockRunnerRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryDeleteCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockRunnerRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByID mocks base method.
func (m *MockRunnerRepository) FindByID(ctx context.Context, id int64) (domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRunnerRepositoryMockRecorder) FindByID(ctx, id any) *MockRunnerRepositoryFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRunnerRepository)(nil).FindByID), ctx, id)
	return &MockRunnerRepositoryFindByIDCall{Call: call}
}

// MockRunnerRepositoryFindByIDCall wrap *gomock.Call
type MockRunnerRepositoryFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryFindByIDCall) Return(arg0 domain.Runner, arg1 error) *MockRunnerRepositoryFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryFindByIDCall) Do(f func(context.Context, int64) (domain.Runner, error)) *MockRunnerRepositoryFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryFindByIDCall) DoAndReturn(f func(context.Context, int64) (domain.Runner, error)) *MockRunnerRepositoryFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindForExecution mocks base method.
func (m *MockRunnerRepository) FindForExecution(ctx context.Context, id int64) (domain.RunnerExecutionSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindForExecution", ctx, id)
	ret0, _ := ret[0].(domain.RunnerExecutionSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindForExecution indicates an expected call of FindForExecution.
func (mr *MockRunnerRepositoryMockRecorder) FindForExecution(ctx, id any) *MockRunnerRepositoryFindForExecutionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindForExecution", reflect.TypeOf((*MockRunnerRepository)(nil).FindForExecution), ctx, id)
	return &MockRunnerRepositoryFindForExecutionCall{Call: call}
}

// MockRunnerRepositoryFindForExecutionCall wrap *gomock.Call
type MockRunnerRepositoryFindForExecutionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryFindForExecutionCall) Return(arg0 domain.RunnerExecutionSpec, arg1 error) *MockRunnerRepositoryFindForExecutionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryFindForExecutionCall) Do(f func(context.Context, int64) (domain.RunnerExecutionSpec, error)) *MockRunnerRepositoryFindForExecutionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryFindForExecutionCall) DoAndReturn(f func(context.Context, int64) (domain.RunnerExecutionSpec, error)) *MockRunnerRepositoryFindForExecutionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockRunnerRepository) List(ctx context.Context, offset, limit int64, keyword, kind string) ([]domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, keyword, kind)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRunnerRepositoryMockRecorder) List(ctx, offset, limit, keyword, kind any) *MockRunnerRepositoryListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRunnerRepository)(nil).List), ctx, offset, limit, keyword, kind)
	return &MockRunnerRepositoryListCall{Call: call}
}

// MockRunnerRepositoryListCall wrap *gomock.Call
type MockRunnerRepositoryListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryListCall) Return(arg0 []domain.Runner, arg1 error) *MockRunnerRepositoryListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryListCall) Do(f func(context.Context, int64, int64, string, string) ([]domain.Runner, error)) *MockRunnerRepositoryListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryListCall) DoAndReturn(f func(context.Context, int64, int64, string, string) ([]domain.Runner, error)) *MockRunnerRepositoryListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByCodebookID mocks base method.
func (m *MockRunnerRepository) ListByCodebookID(ctx context.Context, codebookID int64) ([]domain.RunnerExecutionSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCodebookID", ctx, codebookID)
	ret0, _ := ret[0].([]domain.RunnerExecutionSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCodebookID indicates an expected call of ListByCodebookID.
func (mr *MockRunnerRepositoryMockRecorder) ListByCodebookID(ctx, codebookID any) *MockRunnerRepositoryListByCodebookIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCodebookID", reflect.TypeOf((*MockRunnerRepository)(nil).ListByCodebookID), ctx, codebookID)
	return &MockRunnerRepositoryListByCodebookIDCall{Call: call}
}

// MockRunnerRepositoryListByCodebookIDCall wrap *gomock.Call
type MockRunnerRepositoryListByCodebookIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryListByCodebookIDCall) Return(arg0 []domain.RunnerExecutionSpec, arg1 error) *MockRunnerRepositoryListByCodebookIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryListByCodebookIDCall) Do(f func(context.Context, int64) ([]domain.RunnerExecutionSpec, error)) *MockRunnerRepositoryListByCodebookIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryListByCodebookIDCall) DoAndReturn(f func(context.Context, int64) ([]domain.RunnerExecutionSpec, error)) *MockRunnerRepositoryListByCodebookIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByCodebookIDs mocks base method.
func (m *MockRunnerRepository) ListByCodebookIDs(ctx context.Context, codebookIDs []int64) ([]domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCodebookIDs", ctx, codebookIDs)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCodebookIDs indicates an expected call of ListByCodebookIDs.
func (mr *MockRunnerRepositoryMockRecorder) ListByCodebookIDs(ctx, codebookIDs any) *MockRunnerRepositoryListByCodebookIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCodebookIDs", reflect.TypeOf((*MockRunnerRepository)(nil).ListByCodebookIDs), ctx, codebookIDs)
	return &MockRunnerRepositoryListByCodebookIDsCall{Call: call}
}

// MockRunnerRepositoryListByCodebookIDsCall wrap *gomock.Call
type MockRunnerRepositoryListByCodebookIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryListByCodebookIDsCall) Return(arg0 []domain.Runner, arg1 error) *MockRunnerRepositoryListByCodebookIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryListByCodebookIDsCall) Do(f func(context.Context, []int64) ([]domain.Runner, error)) *MockRunnerRepositoryListByCodebookIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryListByCodebookIDsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Runner, error)) *MockRunnerRepositoryListByCodebookIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByIDs mocks base method.
func (m *MockRunnerRepository) ListByIDs(ctx context.Context, ids []int64) ([]domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockRunnerRepositoryMockRecorder) ListByIDs(ctx, ids any) *MockRunnerRepositoryListByIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockRunnerRepository)(nil).ListByIDs), ctx, ids)
	return &MockRunnerRepositoryListByIDsCall{Call: call}
}

// MockRunnerRepositoryListByIDsCall wrap *gomock.Call
type MockRunnerRepositoryListByIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryListByIDsCall) Return(arg0 []domain.Runner, arg1 error) *MockRunnerRepositoryListByIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryListByIDsCall) Do(f func(context.Context, []int64) ([]domain.Runner, error)) *MockRunnerRepositoryListByIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryListByIDsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Runner, error)) *MockRunnerRepositoryListByIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListExcludeCodebookID mocks base method.
func (m *MockRunnerRepository) ListExcludeCodebookID(ctx context.Context, offset, limit, codebookID int64, keyword, kind string) ([]domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExcludeCodebookID", ctx, offset, limit, codebookID, keyword, kind)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExcludeCodebookID indicates an expected call of ListExcludeCodebookID.
func (mr *MockRunnerRepositoryMockRecorder) ListExcludeCodebookID(ctx, offset, limit, codebookID, keyword, kind any) *MockRunnerRepositoryListExcludeCodebookIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExcludeCodebookID", reflect.TypeOf((*MockRunnerRepository)(nil).ListExcludeCodebookID), ctx, offset, limit, codebookID, keyword, kind)
	return &MockRunnerRepositoryListExcludeCodebookIDCall{Call: call}
}

// MockRunnerRepositoryListExcludeCodebookIDCall wrap *gomock.Call
type MockRunnerRepositoryListExcludeCodebookIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryListExcludeCodebookIDCall) Return(arg0 []domain.Runner, arg1 error) *MockRunnerRepositoryListExcludeCodebookIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryListExcludeCodebookIDCall) Do(f func(context.Context, int64, int64, int64, string, string) ([]domain.Runner, error)) *MockRunnerRepositoryListExcludeCodebookIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryListExcludeCodebookIDCall) DoAndReturn(f func(context.Context, int64, int64, int64, string, string) ([]domain.Runner, error)) *MockRunnerRepositoryListExcludeCodebookIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListMergedVariables mocks base method.
func (m *MockRunnerRepository) ListMergedVariables(ctx context.Context, runnerID int64) ([]domain.RunnerVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMergedVariables", ctx, runnerID)
	ret0, _ := ret[0].([]domain.RunnerVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMergedVariables indicates an expected call of ListMergedVariables.
func (mr *MockRunnerRepositoryMockRecorder) ListMergedVariables(ctx, runnerID any) *MockRunnerRepositoryListMergedVariablesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMergedVariables", reflect.TypeOf((*MockRunnerRepository)(nil).ListMergedVariables), ctx, runnerID)
	return &MockRunnerRepositoryListMergedVariablesCall{Call: call}
}

// MockRunnerRepositoryListMergedVariablesCall wrap *gomock.Call
type MockRunnerRepositoryListMergedVariablesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryListMergedVariablesCall) Return(arg0 []domain.RunnerVariable, arg1 error) *MockRunnerRepositoryListMergedVariablesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryListMergedVariablesCall) Do(f func(context.Context, int64) ([]domain.RunnerVariable, error)) *MockRunnerRepositoryListMergedVariablesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryListMergedVariablesCall) DoAndReturn(f func(context.Context, int64) ([]domain.RunnerVariable, error)) *MockRunnerRepositoryListMergedVariablesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockRunnerRepository) Update(ctx context.Context, req domain.Runner) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRunnerRepositoryMockRecorder) Update(ctx, req any) *MockRunnerRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRunnerRepository)(nil).Update), ctx, req)
	return &MockRunnerRepositoryUpdateCall{Call: call}
}

// MockRunnerRepositoryUpdateCall wrap *gomock.Call
type MockRunnerRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerRepositoryUpdateCall) Return(arg0 int64, arg1 error) *MockRunnerRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerRepositoryUpdateCall) Do(f func(context.Context, domain.Runner) (int64, error)) *MockRunnerRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerRepositoryUpdateCall) DoAndReturn(f func(context.Context, domain.Runner) (int64, error)) *MockRunnerRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
