// Code generated by MockGen. DO NOT EDIT.
// Source: ./task_execution.go
//
// Generated by this command:
//
//	mockgen -source=./task_execution.go -package=repositorymocks -destination=./mocks/task_execution.mock.go -typed
//

// Package repositorymocks is a generated GoMock package.
package repositorymocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskExecutionRepository is a mock of TaskExecutionRepository interface.
type MockTaskExecutionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskExecutionRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskExecutionRepositoryMockRecorder is the mock recorder for MockTaskExecutionRepository.
type MockTaskExecutionRepositoryMockRecorder struct {
	mock *MockTaskExecutionRepository
}

// NewMockTaskExecutionRepository creates a new mock instance.
func NewMockTaskExecutionRepository(ctrl *gomock.Controller) *MockTaskExecutionRepository {
	mock := &MockTaskExecutionRepository{ctrl: ctrl}
	mock.recorder = &MockTaskExecutionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskExecutionRepository) EXPECT() *MockTaskExecutionRepositoryMockRecorder {
	return m.recorder
}

// ClaimPullTask mocks base method.
func (m *MockTaskExecutionRepository) ClaimPullTask(ctx context.Context, serviceName, executorNodeID string, handlerNames []string) (domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPullTask", ctx, serviceName, executorNodeID, handlerNames)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPullTask indicates an expected call of ClaimPullTask.
func (mr *MockTaskExecutionRepositoryMockRecorder) ClaimPullTask(ctx, serviceName, executorNodeID, handlerNames any) *MockTaskExecutionRepositoryClaimPullTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPullTask", reflect.TypeOf((*MockTaskExecutionRepository)(nil).ClaimPullTask), ctx, serviceName, executorNodeID, handlerNames)
	return &MockTaskExecutionRepositoryClaimPullTaskCall{Call: call}
}

// MockTaskExecutionRepositoryClaimPullTaskCall wrap *gomock.Call
type MockTaskExecutionRepositoryClaimPullTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryClaimPullTaskCall) Return(arg0 domain.TaskExecution, arg1 error) *MockTaskExecutionRepositoryClaimPullTaskCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryClaimPullTaskCall) Do(f func(context.Context, string, string, []string) (domain.TaskExecution, error)) *MockTaskExecutionRepositoryClaimPullTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryClaimPullTaskCall) DoAndReturn(f func(context.Context, string, string, []string) (domain.TaskExecution, error)) *MockTaskExecutionRepositoryClaimPullTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockTaskExecutionRepository) Create(ctx context.Context, execution domain.TaskExecution) (domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, execution)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskExecutionRepositoryMockRecorder) Create(ctx, execution any) *MockTaskExecutionRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskExecutionRepository)(nil).Create), ctx, execution)
	return &MockTaskExecutionRepositoryCreateCall{Call: call}
}

// MockTaskExecutionRepositoryCreateCall wrap *gomock.Call
type MockTaskExecutionRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryCreateCall) Return(arg0 domain.TaskExecution, arg1 error) *MockTaskExecutionRepositoryCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryCreateCall) Do(f func(context.Context, domain.TaskExecution) (domain.TaskExecution, error)) *MockTaskExecutionRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.TaskExecution) (domain.TaskExecution, error)) *MockTaskExecutionRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByRequestID mocks base method.
func (m *MockTaskExecutionRepository) FindByRequestID(ctx context.Context, source domain.TaskExecutionSource, requestID string) (domain.TaskExecution, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRequestID", ctx, source, requestID)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByRequestID indicates an expected call of FindByRequestID.
func (mr *MockTaskExecutionRepositoryMockRecorder) FindByRequestID(ctx, source, requestID any) *MockTaskExecutionRepositoryFindByRequestIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRequestID", reflect.TypeOf((*MockTaskExecutionRepository)(nil).FindByRequestID), ctx, source, requestID)
	return &MockTaskExecutionRepositoryFindByRequestIDCall{Call: call}
}

// MockTaskExecutionRepositoryFindByRequestIDCall wrap *gomock.Call
type MockTaskExecutionRepositoryFindByRequestIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryFindByRequestIDCall) Return(arg0 domain.TaskExecution, arg1 bool, arg2 error) *MockTaskExecutionRepositoryFindByRequestIDCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryFindByRequestIDCall) Do(f func(context.Context, domain.TaskExecutionSource, string) (domain.TaskExecution, bool, error)) *MockTaskExecutionRepositoryFindByRequestIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryFindByRequestIDCall) DoAndReturn(f func(context.Context, domain.TaskExecutionSource, string) (domain.TaskExecution, bool, error)) *MockTaskExecutionRepositoryFindByRequestIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByTaskID mocks base method.
func (m *MockTaskExecutionRepository) FindByTaskID(ctx context.Context, taskID int64) ([]domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTaskID", ctx, taskID)
	ret0, _ := ret[0].([]domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTaskID indicates an expected call of FindByTaskID.
func (mr *MockTaskExecutionRepositoryMockRecorder) FindByTaskID(ctx, taskID any) *MockTaskExecutionRepositoryFindByTaskIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTaskID", reflect.TypeOf((*MockTaskExecutionRepository)(nil).FindByTaskID), ctx, taskID)
	return &MockTaskExecutionRepositoryFindByTaskIDCall{Call: call}
}

// MockTaskExecutionRepositoryFindByTaskIDCall wrap *gomock.Call
type MockTaskExecutionRepositoryFindByTaskIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryFindByTaskIDCall) Return(arg0 []domain.TaskExecution, arg1 error) *MockTaskExecutionRepositoryFindByTaskIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryFindByTaskIDCall) Do(f func(context.Context, int64) ([]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindByTaskIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryFindByTaskIDCall) DoAndReturn(f func(context.Context, int64) ([]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindByTaskIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByTaskIDs mocks base method.
func (m *MockTaskExecutionRepository) FindByTaskIDs(ctx context.Context, taskIDs []int64) ([]domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTaskIDs", ctx, taskIDs)
	ret0, _ := ret[0].([]domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTaskIDs indicates an expected call of FindByTaskIDs.
func (mr *MockTaskExecutionRepositoryMockRecorder) FindByTaskIDs(ctx, taskIDs any) *MockTaskExecutionRepositoryFindByTaskIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTaskIDs", reflect.TypeOf((*MockTaskExecutionRepository)(nil).FindByTaskIDs), ctx, taskIDs)
	return &MockTaskExecutionRepositoryFindByTaskIDsCall{Call: call}
}

// MockTaskExecutionRepositoryFindByTaskIDsCall wrap *gomock.Call
type MockTaskExecutionRepositoryFindByTaskIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryFindByTaskIDsCall) Return(arg0 []domain.TaskExecution, arg1 error) *MockTaskExecutionRepositoryFindByTaskIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryFindByTaskIDsCall) Do(f func(context.Context, []int64) ([]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindByTaskIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryFindByTaskIDsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindByTaskIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindExecutionByTaskIDAndPlanExecID mocks base method.
func (m *MockTaskExecutionRepository) FindExecutionByTaskIDAndPlanExecID(ctx context.Context, taskID, planExecID int64) (domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExecutionByTaskIDAndPlanExecID", ctx, taskID, planExecID)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExecutionByTaskIDAndPlanExecID indicates an expected call of FindExecutionByTaskIDAndPlanExecID.
func (mr *MockTaskExecutionRepositoryMockRecorder) FindExecutionByTaskIDAndPlanExecID(ctx, taskID, planExecID any) *MockTaskExecutionRepositoryFindExecutionByTaskIDAndPlanExecIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExecutionByTaskIDAndPlanExecID", reflect.TypeOf((*MockTaskExecutionRepository)(nil).FindExecutionByTaskIDAndPlanExecID), ctx, taskID, planExecID)
	return &MockTaskExecutionRepositoryFindExecutionByTaskIDAndPlanExecIDCall{Call: call}
}

// MockTaskExecutionRepositoryFindExecutionByTaskIDAndPlanExecIDCall wrap *gomock.Call
type MockTaskExecutionRepositoryFindExecutionByTaskIDAndPlanExecIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryFindExecutionByTaskIDAndPlanExecIDCall) Return(arg0 domain.TaskExecution, arg1 error) *MockTaskExecutionRepositoryFindExecutionByTaskIDAndPlanExecIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryFindExecutionByTaskIDAndPlanExecIDCall) Do(f func(context.Context, int64, int64) (domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindExecutionByTaskIDAndPlanExecIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryFindExecutionByTaskIDAndPlanExecIDCall) DoAndReturn(f func(context.Context, int64, int64) (domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindExecutionByTaskIDAndPlanExecIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindExecutionsByPlanExecID mocks base method.
func (m *MockTaskExecutionRepository) FindExecutionsByPlanExecID(ctx context.Context, planExecID int64) (map[int64]domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExecutionsByPlanExecID", ctx, planExecID)
	ret0, _ := ret[0].(map[int64]domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExecutionsByPlanExecID indicates an expected call of FindExecutionsByPlanExecID.
func (mr *MockTaskExecutionRepositoryMockRecorder) FindExecutionsByPlanExecID(ctx, planExecID any) *MockTaskExecutionRepositoryFindExecutionsByPlanExecIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExecutionsByPlanExecID", reflect.TypeOf((*MockTaskExecutionRepository)(nil).FindExecutionsByPlanExecID), ctx, planExecID)
	return &MockTaskExecutionRepositoryFindExecutionsByPlanExecIDCall{Call: call}
}

// MockTaskExecutionRepositoryFindExecutionsByPlanExecIDCall wrap *gomock.Call
type MockTaskExecutionRepositoryFindExecutionsByPlanExecIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryFindExecutionsByPlanExecIDCall) Return(arg0 map[int64]domain.TaskExecution, arg1 error) *MockTaskExecutionRepositoryFindExecutionsByPlanExecIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryFindExecutionsByPlanExecIDCall) Do(f func(context.Context, int64) (map[int64]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindExecutionsByPlanExecIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryFindExecutionsByPlanExecIDCall) DoAndReturn(f func(context.Context, int64) (map[int64]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindExecutionsByPlanExecIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindReschedulableExecutions mocks base method.
func (m *MockTaskExecutionRepository) FindReschedulableExecutions(ctx context.Context, limit int) ([]domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReschedulableExecutions", ctx, limit)
	ret0, _ := ret[0].([]domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindReschedulableExecutions indicates an expected call of FindReschedulableExecutions.
func (mr *MockTaskExecutionRepositoryMockRecorder) FindReschedulableExecutions(ctx, limit any) *MockTaskExecutionRepositoryFindReschedulableExecutionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReschedulableExecutions", reflect.TypeOf((*MockTaskExecutionRepository)(nil).FindReschedulableExecutions), ctx, limit)
	return &MockTaskExecutionRepositoryFindReschedulableExecutionsCall{Call: call}
}

// MockTaskExecutionRepositoryFindReschedulableExecutionsCall wrap *gomock.Call
type MockTaskExecutionRepositoryFindReschedulableExecutionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryFindReschedulableExecutionsCall) Return(arg0 []domain.TaskExecution, arg1 error) *MockTaskExecutionRepositoryFindReschedulableExecutionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryFindReschedulableExecutionsCall) Do(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindReschedulableExecutionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryFindReschedulableExecutionsCall) DoAndReturn(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindReschedulableExecutionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindRetryableExecutions mocks base method.
func (m *MockTaskExecutionRepository) FindRetryableExecutions(ctx context.Context, limit int) ([]domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRetryableExecutions", ctx, limit)
	ret0, _ := ret[0].([]domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRetryableExecutions indicates an expected call of FindRetryableExecutions.
func (mr *MockTaskExecutionRepositoryMockRecorder) FindRetryableExecutions(ctx, limit any) *MockTaskExecutionRepositoryFindRetryableExecutionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRetryableExecutions", reflect.TypeOf((*MockTaskExecutionRepository)(nil).FindRetryableExecutions), ctx, limit)
	return &MockTaskExecutionRepositoryFindRetryableExecutionsCall{Call: call}
}

// MockTaskExecutionRepositoryFindRetryableExecutionsCall wrap *gomock.Call
type MockTaskExecutionRepositoryFindRetryableExecutionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryFindRetryableExecutionsCall) Return(arg0 []domain.TaskExecution, arg1 error) *MockTaskExecutionRepositoryFindRetryableExecutionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryFindRetryableExecutionsCall) Do(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindRetryableExecutionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryFindRetryableExecutionsCall) DoAndReturn(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindRetryableExecutionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindTimeoutExecutions mocks base method.
func (m *MockTaskExecutionRepository) FindTimeoutExecutions(ctx context.Context, limit int) ([]domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTimeoutExecutions", ctx, limit)
	ret0, _ := ret[0].([]domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTimeoutExecutions indicates an expected call of FindTimeoutExecutions.
func (mr *MockTaskExecutionRepositoryMockRecorder) FindTimeoutExecutions(ctx, limit any) *MockTaskExecutionRepositoryFindTimeoutExecutionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTimeoutExecutions", reflect.TypeOf((*MockTaskExecutionRepository)(nil).FindTimeoutExecutions), ctx, limit)
	return &MockTaskExecutionRepositoryFindTimeoutExecutionsCall{Call: call}
}

// MockTaskExecutionRepositoryFindTimeoutExecutionsCall wrap *gomock.Call
type MockTaskExecutionRepositoryFindTimeoutExecutionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryFindTimeoutExecutionsCall) Return(arg0 []domain.TaskExecution, arg1 error) *MockTaskExecutionRepositoryFindTimeoutExecutionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryFindTimeoutExecutionsCall) Do(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindTimeoutExecutionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryFindTimeoutExecutionsCall) DoAndReturn(f func(context.Context, int) ([]domain.TaskExecution, error)) *MockTaskExecutionRepositoryFindTimeoutExecutionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockTaskExecutionRepository) GetByID(ctx context.Context, id int64) (domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskExecutionRepositoryMockRecorder) GetByID(ctx, id any) *MockTaskExecutionRepositoryGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskExecutionRepository)(nil).GetByID), ctx, id)
	return &MockTaskExecutionRepositoryGetByIDCall{Call: call}
}

// MockTaskExecutionRepositoryGetByIDCall wrap *gomock.Call
type MockTaskExecutionRepositoryGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryGetByIDCall) Return(arg0 domain.TaskExecution, arg1 error) *MockTaskExecutionRepositoryGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryGetByIDCall) Do(f func(context.Context, int64) (domain.TaskExecution, error)) *MockTaskExecutionRepositoryGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryGetByIDCall) DoAndReturn(f func(context.Context, int64) (domain.TaskExecution, error)) *MockTaskExecutionRepositoryGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByTaskID mocks base method.
func (m *MockTaskExecutionRepository) ListByTaskID(ctx context.Context, taskID int64, offset, limit int) ([]domain.TaskExecution, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTaskID", ctx, taskID, offset, limit)
	ret0, _ := ret[0].([]domain.TaskExecution)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByTaskID indicates an expected call of ListByTaskID.
func (mr *MockTaskExecutionRepositoryMockRecorder) ListByTaskID(ctx, taskID, offset, limit any) *MockTaskExecutionRepositoryListByTaskIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTaskID", reflect.TypeOf((*MockTaskExecutionRepository)(nil).ListByTaskID), ctx, taskID, offset, limit)
	return &MockTaskExecutionRepositoryListByTaskIDCall{Call: call}
}

// MockTaskExecutionRepositoryListByTaskIDCall wrap *gomock.Call
type MockTaskExecutionRepositoryListByTaskIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryListByTaskIDCall) Return(arg0 []domain.TaskExecution, arg1 int64, arg2 error) *MockTaskExecutionRepositoryListByTaskIDCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryListByTaskIDCall) Do(f func(context.Context, int64, int, int) ([]domain.TaskExecution, int64, error)) *MockTaskExecutionRepositoryListByTaskIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryListByTaskIDCall) DoAndReturn(f func(context.Context, int64, int, int) ([]domain.TaskExecution, int64, error)) *MockTaskExecutionRepositoryListByTaskIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetRunningState mocks base method.
func (m *MockTaskExecutionRepository) SetRunningState(ctx context.Context, id int64, progress int32, executorNodeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRunningState", ctx, id, progress, executorNodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRunningState indicates an expected call of SetRunningState.
func (mr *MockTaskExecutionRepositoryMockRecorder) SetRunningState(ctx, id, progress, executorNodeID any) *MockTaskExecutionRepositorySetRunningStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRunningState", reflect.TypeOf((*MockTaskExecutionRepository)(nil).SetRunningState), ctx, id, progress, executorNodeID)
	return &MockTaskExecutionRepositorySetRunningStateCall{Call: call}
}

// MockTaskExecutionRepositorySetRunningStateCall wrap *gomock.Call
type MockTaskExecutionRepositorySetRunningStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositorySetRunningStateCall) Return(arg0 error) *MockTaskExecutionRepositorySetRunningStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositorySetRunningStateCall) Do(f func(context.Context, int64, int32, string) error) *MockTaskExecutionRepositorySetRunningStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositorySetRunningStateCall) DoAndReturn(f func(context.Context, int64, int32, string) error) *MockTaskExecutionRepositorySetRunningStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateRetryResult mocks base method.
func (m *MockTaskExecutionRepository) UpdateRetryResult(ctx context.Context, id, retryCount, nextRetryTime int64, expectedStatus, status domain.TaskExecutionStatus, progress int32, endTime int64, scheduleParams map[string]string, executorNodeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRetryResult", ctx, id, retryCount, nextRetryTime, expectedStatus, status, progress, endTime, scheduleParams, executorNodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRetryResult indicates an expected call of UpdateRetryResult.
func (mr *MockTaskExecutionRepositoryMockRecorder) UpdateRetryResult(ctx, id, retryCount, nextRetryTime, expectedStatus, status, progress, endTime, scheduleParams, executorNodeID any) *MockTaskExecutionRepositoryUpdateRetryResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRetryResult", reflect.TypeOf((*MockTaskExecutionRepository)(nil).UpdateRetryResult), ctx, id, retryCount, nextRetryTime, expectedStatus, status, progress, endTime, scheduleParams, executorNodeID)
	return &MockTaskExecutionRepositoryUpdateRetryResultCall{Call: call}
}

// MockTaskExecutionRepositoryUpdateRetryResultCall wrap *gomock.Call
type MockTaskExecutionRepositoryUpdateRetryResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryUpdateRetryResultCall) Return(arg0 error) *MockTaskExecutionRepositoryUpdateRetryResultCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryUpdateRetryResultCall) Do(f func(context.Context, int64, int64, int64, domain.TaskExecutionStatus, domain.TaskExecutionStatus, int32, int64, map[string]string, string) error) *MockTaskExecutionRepositoryUpdateRetryResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryUpdateRetryResultCall) DoAndReturn(f func(context.Context, int64, int64, int64, domain.TaskExecutionStatus, domain.TaskExecutionStatus, int32, int64, map[string]string, string) error) *MockTaskExecutionRepositoryUpdateRetryResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateRunningProgress mocks base method.
func (m *MockTaskExecutionRepository) UpdateRunningProgress(ctx context.Context, id int64, progress int32, executorNodeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunningProgress", ctx, id, progress, executorNodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunningProgress indicates an expected call of UpdateRunningProgress.
func (mr *MockTaskExecutionRepositoryMockRecorder) UpdateRunningProgress(ctx, id, progress, executorNodeID any) *MockTaskExecutionRepositoryUpdateRunningProgressCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunningProgress", reflect.TypeOf((*MockTaskExecutionRepository)(nil).UpdateRunningProgress), ctx, id, progress, executorNodeID)
	return &MockTaskExecutionRepositoryUpdateRunningProgressCall{Call: call}
}

// MockTaskExecutionRepositoryUpdateRunningProgressCall wrap *gomock.Call
type MockTaskExecutionRepositoryUpdateRunningProgressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryUpdateRunningProgressCall) Return(arg0 error) *MockTaskExecutionRepositoryUpdateRunningProgressCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryUpdateRunningProgressCall) Do(f func(context.Context, int64, int32, string) error) *MockTaskExecutionRepositoryUpdateRunningProgressCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryUpdateRunningProgressCall) DoAndReturn(f func(context.Context, int64, int32, string) error) *MockTaskExecutionRepositoryUpdateRunningProgressCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateScheduleResult mocks base method.
func (m *MockTaskExecutionRepository) UpdateScheduleResult(ctx context.Context, id int64, expectedStatuses []domain.TaskExecutionStatus, status domain.TaskExecutionStatus, progress int32, endTime int64, scheduleParams map[string]string, executorNodeID, taskResult string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduleResult", ctx, id, expectedStatuses, status, progress, endTime, scheduleParams, executorNodeID, taskResult)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScheduleResult indicates an expected call of UpdateScheduleResult.
func (mr *MockTaskExecutionRepositoryMockRecorder) UpdateScheduleResult(ctx, id, expectedStatuses, status, progress, endTime, scheduleParams, executorNodeID, taskResult any) *MockTaskExecutionRepositoryUpdateScheduleResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduleResult", reflect.TypeOf((*MockTaskExecutionRepository)(nil).UpdateScheduleResult), ctx, id, expectedStatuses, status, progress, endTime, scheduleParams, executorNodeID, taskResult)
	return &MockTaskExecutionRepositoryUpdateScheduleResultCall{Call: call}
}

// MockTaskExecutionRepositoryUpdateScheduleResultCall wrap *gomock.Call
type MockTaskExecutionRepositoryUpdateScheduleResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryUpdateScheduleResultCall) Return(arg0 bool, arg1 error) *MockTaskExecutionRepositoryUpdateScheduleResultCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryUpdateScheduleResultCall) Do(f func(context.Context, int64, []domain.TaskExecutionStatus, domain.TaskExecutionStatus, int32, int64, map[string]string, string, string) (bool, error)) *MockTaskExecutionRepositoryUpdateScheduleResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryUpdateScheduleResultCall) DoAndReturn(f func(context.Context, int64, []domain.TaskExecutionStatus, domain.TaskExecutionStatus, int32, int64, map[string]string, string, string) (bool, error)) *MockTaskExecutionRepositoryUpdateScheduleResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateStatus mocks base method.
func (m *MockTaskExecutionRepository) UpdateStatus(ctx context.Context, id int64, expectedStatuses []domain.TaskExecutionStatus, status domain.TaskExecutionStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, expectedStatuses, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTaskExecutionRepositoryMockRecorder) UpdateStatus(ctx, id, expectedStatuses, status any) *MockTaskExecutionRepositoryUpdateStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTaskExecutionRepository)(nil).UpdateStatus), ctx, id, expectedStatuses, status)
	return &MockTaskExecutionRepositoryUpdateStatusCall{Call: call}
}

// MockTaskExecutionRepositoryUpdateStatusCall wrap *gomock.Call
type MockTaskExecutionRepositoryUpdateStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskExecutionRepositoryUpdateStatusCall) Return(arg0 error) *MockTaskExecutionRepositoryUpdateStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskExecutionRepositoryUpdateStatusCall) Do(f func(context.Context, int64, []domain.TaskExecutionStatus, domain.TaskExecutionStatus) error) *MockTaskExecutionRepositoryUpdateStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskExecutionRepositoryUpdateStatusCall) DoAndReturn(f func(context.Context, int64, []domain.TaskExecutionStatus, domain.TaskExecutionStatus) error) *MockTaskExecutionRepositoryUpdateStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
