// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go
//
// Generated by this command:
//
//	mockgen -source=./types.go -package=pickermocks -destination=./mocks/picker.mock.go -typed
//

// Package pickermocks is a generated GoMock package.
package pickermocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutorNodePicker is a mock of ExecutorNodePicker interface.
type MockExecutorNodePicker struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorNodePickerMockRecorder
	isgomock struct{}
}

// MockExecutorNodePickerMockRecorder is the mock recorder for MockExecutorNodePicker.
type MockExecutorNodePickerMockRecorder struct {
	mock *MockExecutorNodePicker
}

// NewMockExecutorNodePicker creates a new mock instance.
func NewMockExecutorNodePicker(ctrl *gomock.Controller) *MockExecutorNodePicker {
	mock := &MockExecutorNodePicker{ctrl: ctrl}
	mock.recorder = &MockExecutorNodePickerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutorNodePicker) EXPECT() *MockExecutorNodePickerMockRecorder {
	return m.recorder
}

// Pick mocks base method.
func (m *MockExecutorNodePicker) Pick(ctx context.Context, task domain.Task) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pick", ctx, task)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pick indicates an expected call of Pick.
func (mr *MockExecutorNodePickerMockRecorder) Pick(ctx, task any) *MockExecutorNodePickerPickCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pick", reflect.TypeOf((*MockExecutorNodePicker)(nil).Pick), ctx, task)
	return &MockExecutorNodePickerPickCall{Call: call}
}

// MockExecutorNodePickerPickCall wrap *gomock.Call
type MockExecutorNodePickerPickCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutorNodePickerPickCall) Return(arg0 string, arg1 error) *MockExecutorNodePickerPickCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutorNodePickerPickCall) Do(f func(context.Context, domain.Task) (string, error)) *MockExecutorNodePickerPickCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutorNodePickerPickCall) DoAndReturn(f func(context.Context, domain.Task) (string, error)) *MockExecutorNodePickerPickCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
