// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/etask/sdk/executor (interfaces: ExecutionLogger)
//
// Generated by this command:
//
//	mockgen -package=servicemocks -destination=./mocks/execution_logger.mock.go -typed github.com/Duke1616/etask/sdk/executor ExecutionLogger
//

// Package servicemocks is a generated GoMock package.
package servicemocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExecutionLogger is a mock of ExecutionLogger interface.
type MockExecutionLogger struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionLoggerMockRecorder
	isgomock struct{}
}

// MockExecutionLoggerMockRecorder is the mock recorder for MockExecutionLogger.
type MockExecutionLoggerMockRecorder struct {
	mock *MockExecutionLogger
}

// NewMockExecutionLogger creates a new mock instance.
func NewMockExecutionLogger(ctrl *gomock.Controller) *MockExecutionLogger {
	mock := &MockExecutionLogger{ctrl: ctrl}
	mock.recorder = &MockExecutionLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionLogger) EXPECT() *MockExecutionLoggerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockExecutionLogger) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockExecutionLoggerMockRecorder) Close() *MockExecutionLoggerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockExecutionLogger)(nil).Close))
	return &MockExecutionLoggerCloseCall{Call: call}
}

// MockExecutionLoggerCloseCall wrap *gomock.Call
type MockExecutionLoggerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionLoggerCloseCall) Return() *MockExecutionLoggerCloseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionLoggerCloseCall) Do(f func()) *MockExecutionLoggerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionLoggerCloseCall) DoAndReturn(f func()) *MockExecutionLoggerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Log mocks base method.
func (m *MockExecutionLogger) Log(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Log", varargs...)
}

// Log indicates an expected call of Log.
func (mr *MockExecutionLoggerMockRecorder) Log(format any, args ...any) *MockExecutionLoggerLogCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockExecutionLogger)(nil).Log), varargs...)
	return &MockExecutionLoggerLogCall{Call: call}
}

// MockExecutionLoggerLogCall wrap *gomock.Call
type MockExecutionLoggerLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionLoggerLogCall) Return() *MockExecutionLoggerLogCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionLoggerLogCall) Do(f func(string, ...any)) *MockExecutionLoggerLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionLoggerLogCall) DoAndReturn(f func(string, ...any)) *MockExecutionLoggerLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
