// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/etask/sdk/executor (interfaces: TaskLogger)
//
// Generated by this command:
//
//	mockgen -package=servicemocks -destination=./mocks/task_logger.mock.go -typed github.com/Duke1616/etask/sdk/executor TaskLogger
//

// Package servicemocks is a generated GoMock package.
package servicemocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskLogger is a mock of TaskLogger interface.
type MockTaskLogger struct {
	ctrl     *gomock.Controller
	recorder *MockTaskLoggerMockRecorder
	isgomock struct{}
}

// MockTaskLoggerMockRecorder is the mock recorder for MockTaskLogger.
type MockTaskLoggerMockRecorder struct {
	mock *MockTaskLogger
}

// NewMockTaskLogger creates a new mock instance.
func NewMockTaskLogger(ctrl *gomock.Controller) *MockTaskLogger {
	mock := &MockTaskLogger{ctrl: ctrl}
	mock.recorder = &MockTaskLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskLogger) EXPECT() *MockTaskLoggerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTaskLogger) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockTaskLoggerMockRecorder) Close() *MockTaskLoggerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTaskLogger)(nil).Close))
	return &MockTaskLoggerCloseCall{Call: call}
}

// MockTaskLoggerCloseCall wrap *gomock.Call
type MockTaskLoggerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskLoggerCloseCall) Return() *MockTaskLoggerCloseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskLoggerCloseCall) Do(f func()) *MockTaskLoggerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskLoggerCloseCall) DoAndReturn(f func()) *MockTaskLoggerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Log mocks base method.
func (m *MockTaskLogger) Log(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Log", varargs...)
}

// Log indicates an expected call of Log.
func (mr *MockTaskLoggerMockRecorder) Log(format any, args ...any) *MockTaskLoggerLogCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockTaskLogger)(nil).Log), varargs...)
	return &MockTaskLoggerLogCall{Call: call}
}

// MockTaskLoggerLogCall wrap *gomock.Call
type MockTaskLoggerLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskLoggerLogCall) Return() *MockTaskLoggerLogCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskLoggerLogCall) Do(f func(string, ...any)) *MockTaskLoggerLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskLoggerLogCall) DoAndReturn(f func(string, ...any)) *MockTaskLoggerLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
