// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=submissionmocks -destination=./mocks/service.mock.go -typed
//

// Package submissionmocks is a generated GoMock package.
package submissionmocks

import (
	context "context"
	reflect "reflect"

	submission "github.com/Duke1616/etask/internal/service/submission"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// RunRunner mocks base method.
func (m *MockService) RunRunner(ctx context.Context, command submission.RunRunnerCommand) (submission.RunResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunRunner", ctx, command)
	ret0, _ := ret[0].(submission.RunResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunRunner indicates an expected call of RunRunner.
func (mr *MockServiceMockRecorder) RunRunner(ctx, command any) *MockServiceRunRunnerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRunner", reflect.TypeOf((*MockService)(nil).RunRunner), ctx, command)
	return &MockServiceRunRunnerCall{Call: call}
}

// MockServiceRunRunnerCall wrap *gomock.Call
type MockServiceRunRunnerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceRunRunnerCall) Return(arg0 submission.RunResult, arg1 error) *MockServiceRunRunnerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceRunRunnerCall) Do(f func(context.Context, submission.RunRunnerCommand) (submission.RunResult, error)) *MockServiceRunRunnerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceRunRunnerCall) DoAndReturn(f func(context.Context, submission.RunRunnerCommand) (submission.RunResult, error)) *MockServiceRunRunnerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TerminateExecution mocks base method.
func (m *MockService) TerminateExecution(ctx context.Context, command submission.TerminateExecutionCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateExecution", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateExecution indicates an expected call of TerminateExecution.
func (mr *MockServiceMockRecorder) TerminateExecution(ctx, command any) *MockServiceTerminateExecutionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateExecution", reflect.TypeOf((*MockService)(nil).TerminateExecution), ctx, command)
	return &MockServiceTerminateExecutionCall{Call: call}
}

// MockServiceTerminateExecutionCall wrap *gomock.Call
type MockServiceTerminateExecutionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTerminateExecutionCall) Return(arg0 error) *MockServiceTerminateExecutionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTerminateExecutionCall) Do(f func(context.Context, submission.TerminateExecutionCommand) error) *MockServiceTerminateExecutionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTerminateExecutionCall) DoAndReturn(f func(context.Context, submission.TerminateExecutionCommand) error) *MockServiceTerminateExecutionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
