// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package runner

import (
	"github.com/Duke1616/ecmdb/internal/runner/internal/service"
	"github.com/ecodeclub/mq-api"
)

// Injectors from wire.go:

func InitModule(q mq.MQ) (*Module, error) {
	serviceService := service.NewService()
	module := &Module{
		Svc: serviceService,
	}
	return module, nil
}
