// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package runner

import (
	"github.com/Duke1616/ecmdb/internal/runner/internal/event"
	"github.com/Duke1616/ecmdb/internal/runner/internal/service"
	"github.com/Duke1616/ecmdb/internal/runner/internal/web"
	"github.com/ecodeclub/mq-api"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(q mq.MQ) (*Module, error) {
	taskRunnerEventProducer, err := event.NewTaskRunnerEventProducer(q)
	if err != nil {
		return nil, err
	}
	serviceService := service.NewService(taskRunnerEventProducer)
	module := &Module{
		Svc: serviceService,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(service.NewService, web.NewHandler)
