// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/ecmdb/internal/execute"
	"github.com/Duke1616/ecmdb/internal/runner"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	v := InitGinMiddlewares()
	mq := InitMQ()
	module, err := runner.InitModule(mq)
	if err != nil {
		return nil, err
	}
	executeModule, err := execute.InitModule(mq, module)
	if err != nil {
		return nil, err
	}
	handler := executeModule.Hdl
	webHandler := module.Hdl
	engine := InitWebServer(v, handler, webHandler)
	service := executeModule.Svc
	client := InitEtcdClient()
	app := &App{
		Web:        engine,
		WorkerSvc:  service,
		EtcdClient: client,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(InitMQ, InitEtcdClient)
