// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/ecmdb/internal/runner"
	"github.com/Duke1616/ecmdb/internal/worker"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	v := InitGinMiddlewares()
	viper := InitViper()
	mq := InitMQ(viper)
	module, err := runner.InitModule(mq)
	if err != nil {
		return nil, err
	}
	workerModule, err := worker.InitModule(mq, module)
	if err != nil {
		return nil, err
	}
	handler := workerModule.Hdl
	engine := InitWebServer(v, handler)
	service := workerModule.Svc
	client := InitEtcdClient(viper)
	app := &App{
		Web:        engine,
		WorkerSvc:  service,
		Viper:      viper,
		EtcdClient: client,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(InitViper, InitMQ, InitEtcdClient)
