// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/ecmdb/internal/worker"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	v := InitGinMiddlewares()
	viper := InitViper()
	mq := InitMQ(viper)
	module, err := worker.InitModule(mq)
	if err != nil {
		return nil, err
	}
	handler := module.Hdl
	engine := InitWebServer(v, handler)
	app := &App{
		Web: engine,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(InitViper, InitMQ)
