// Code generated by MockGen. DO NOT EDIT.
// Source: ./runner.go
//
// Generated by this command:
//
//	mockgen -source=./runner.go -package=runnermocks -destination=./mocks/runner.mock.go -typed
//

// Package runnermocks is a generated GoMock package.
package runnermocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, req domain.Runner) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, req any) *MockServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, req)
	return &MockServiceCreateCall{Call: call}
}

// MockServiceCreateCall wrap *gomock.Call
type MockServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateCall) Return(arg0 int64, arg1 error) *MockServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateCall) Do(f func(context.Context, domain.Runner) (int64, error)) *MockServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateCall) DoAndReturn(f func(context.Context, domain.Runner) (int64, error)) *MockServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id any) *MockServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
	return &MockServiceDeleteCall{Call: call}
}

// MockServiceDeleteCall wrap *gomock.Call
type MockServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeleteCall) Return(arg0 int64, arg1 error) *MockServiceDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeleteCall) Do(f func(context.Context, int64) (int64, error)) *MockServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeleteCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByCodebookIDAndTag mocks base method.
func (m *MockService) FindByCodebookIDAndTag(ctx context.Context, codebookID int64, tag string) (domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCodebookIDAndTag", ctx, codebookID, tag)
	ret0, _ := ret[0].(domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCodebookIDAndTag indicates an expected call of FindByCodebookIDAndTag.
func (mr *MockServiceMockRecorder) FindByCodebookIDAndTag(ctx, codebookID, tag any) *MockServiceFindByCodebookIDAndTagCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCodebookIDAndTag", reflect.TypeOf((*MockService)(nil).FindByCodebookIDAndTag), ctx, codebookID, tag)
	return &MockServiceFindByCodebookIDAndTagCall{Call: call}
}

// MockServiceFindByCodebookIDAndTagCall wrap *gomock.Call
type MockServiceFindByCodebookIDAndTagCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindByCodebookIDAndTagCall) Return(arg0 domain.Runner, arg1 error) *MockServiceFindByCodebookIDAndTagCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindByCodebookIDAndTagCall) Do(f func(context.Context, int64, string) (domain.Runner, error)) *MockServiceFindByCodebookIDAndTagCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindByCodebookIDAndTagCall) DoAndReturn(f func(context.Context, int64, string) (domain.Runner, error)) *MockServiceFindByCodebookIDAndTagCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByID mocks base method.
func (m *MockService) FindByID(ctx context.Context, id int64) (domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockServiceMockRecorder) FindByID(ctx, id any) *MockServiceFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockService)(nil).FindByID), ctx, id)
	return &MockServiceFindByIDCall{Call: call}
}

// MockServiceFindByIDCall wrap *gomock.Call
type MockServiceFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindByIDCall) Return(arg0 domain.Runner, arg1 error) *MockServiceFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindByIDCall) Do(f func(context.Context, int64) (domain.Runner, error)) *MockServiceFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindByIDCall) DoAndReturn(f func(context.Context, int64) (domain.Runner, error)) *MockServiceFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, offset, limit int64, keyword, kind string) ([]domain.Runner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, keyword, kind)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, offset, limit, keyword, kind any) *MockServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, offset, limit, keyword, kind)
	return &MockServiceListCall{Call: call}
}

// MockServiceListCall wrap *gomock.Call
type MockServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListCall) Return(arg0 []domain.Runner, arg1 int64, arg2 error) *MockServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListCall) Do(f func(context.Context, int64, int64, string, string) ([]domain.Runner, int64, error)) *MockServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListCall) DoAndReturn(f func(context.Context, int64, int64, string, string) ([]domain.Runner, int64, error)) *MockServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByCodebookID mocks base method.
func (m *MockService) ListByCodebookID(ctx context.Context, codebookID int64) ([]domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCodebookID", ctx, codebookID)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCodebookID indicates an expected call of ListByCodebookID.
func (mr *MockServiceMockRecorder) ListByCodebookID(ctx, codebookID any) *MockServiceListByCodebookIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCodebookID", reflect.TypeOf((*MockService)(nil).ListByCodebookID), ctx, codebookID)
	return &MockServiceListByCodebookIDCall{Call: call}
}

// MockServiceListByCodebookIDCall wrap *gomock.Call
type MockServiceListByCodebookIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListByCodebookIDCall) Return(arg0 []domain.Runner, arg1 error) *MockServiceListByCodebookIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListByCodebookIDCall) Do(f func(context.Context, int64) ([]domain.Runner, error)) *MockServiceListByCodebookIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListByCodebookIDCall) DoAndReturn(f func(context.Context, int64) ([]domain.Runner, error)) *MockServiceListByCodebookIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByCodebookIDs mocks base method.
func (m *MockService) ListByCodebookIDs(ctx context.Context, codebookIDs []int64) ([]domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCodebookIDs", ctx, codebookIDs)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCodebookIDs indicates an expected call of ListByCodebookIDs.
func (mr *MockServiceMockRecorder) ListByCodebookIDs(ctx, codebookIDs any) *MockServiceListByCodebookIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCodebookIDs", reflect.TypeOf((*MockService)(nil).ListByCodebookIDs), ctx, codebookIDs)
	return &MockServiceListByCodebookIDsCall{Call: call}
}

// MockServiceListByCodebookIDsCall wrap *gomock.Call
type MockServiceListByCodebookIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListByCodebookIDsCall) Return(arg0 []domain.Runner, arg1 error) *MockServiceListByCodebookIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListByCodebookIDsCall) Do(f func(context.Context, []int64) ([]domain.Runner, error)) *MockServiceListByCodebookIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListByCodebookIDsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Runner, error)) *MockServiceListByCodebookIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByIDs mocks base method.
func (m *MockService) ListByIDs(ctx context.Context, ids []int64) ([]domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockServiceMockRecorder) ListByIDs(ctx, ids any) *MockServiceListByIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockService)(nil).ListByIDs), ctx, ids)
	return &MockServiceListByIDsCall{Call: call}
}

// MockServiceListByIDsCall wrap *gomock.Call
type MockServiceListByIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListByIDsCall) Return(arg0 []domain.Runner, arg1 error) *MockServiceListByIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListByIDsCall) Do(f func(context.Context, []int64) ([]domain.Runner, error)) *MockServiceListByIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListByIDsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Runner, error)) *MockServiceListByIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListExcludeCodebookID mocks base method.
func (m *MockService) ListExcludeCodebookID(ctx context.Context, offset, limit, codebookID int64, keyword, kind string) ([]domain.Runner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExcludeCodebookID", ctx, offset, limit, codebookID, keyword, kind)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListExcludeCodebookID indicates an expected call of ListExcludeCodebookID.
func (mr *MockServiceMockRecorder) ListExcludeCodebookID(ctx, offset, limit, codebookID, keyword, kind any) *MockServiceListExcludeCodebookIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExcludeCodebookID", reflect.TypeOf((*MockService)(nil).ListExcludeCodebookID), ctx, offset, limit, codebookID, keyword, kind)
	return &MockServiceListExcludeCodebookIDCall{Call: call}
}

// MockServiceListExcludeCodebookIDCall wrap *gomock.Call
type MockServiceListExcludeCodebookIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListExcludeCodebookIDCall) Return(arg0 []domain.Runner, arg1 int64, arg2 error) *MockServiceListExcludeCodebookIDCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListExcludeCodebookIDCall) Do(f func(context.Context, int64, int64, int64, string, string) ([]domain.Runner, int64, error)) *MockServiceListExcludeCodebookIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListExcludeCodebookIDCall) DoAndReturn(f func(context.Context, int64, int64, int64, string, string) ([]domain.Runner, int64, error)) *MockServiceListExcludeCodebookIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListMergedVariables mocks base method.
func (m *MockService) ListMergedVariables(ctx context.Context, id int64) ([]domain.RunnerVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMergedVariables", ctx, id)
	ret0, _ := ret[0].([]domain.RunnerVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMergedVariables indicates an expected call of ListMergedVariables.
func (mr *MockServiceMockRecorder) ListMergedVariables(ctx, id any) *MockServiceListMergedVariablesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMergedVariables", reflect.TypeOf((*MockService)(nil).ListMergedVariables), ctx, id)
	return &MockServiceListMergedVariablesCall{Call: call}
}

// MockServiceListMergedVariablesCall wrap *gomock.Call
type MockServiceListMergedVariablesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListMergedVariablesCall) Return(arg0 []domain.RunnerVariable, arg1 error) *MockServiceListMergedVariablesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListMergedVariablesCall) Do(f func(context.Context, int64) ([]domain.RunnerVariable, error)) *MockServiceListMergedVariablesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListMergedVariablesCall) DoAndReturn(f func(context.Context, int64) ([]domain.RunnerVariable, error)) *MockServiceListMergedVariablesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, req domain.Runner) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, req any) *MockServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, req)
	return &MockServiceUpdateCall{Call: call}
}

// MockServiceUpdateCall wrap *gomock.Call
type MockServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateCall) Return(arg0 int64, arg1 error) *MockServiceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateCall) Do(f func(context.Context, domain.Runner) (int64, error)) *MockServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateCall) DoAndReturn(f func(context.Context, domain.Runner) (int64, error)) *MockServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
