// Code generated by MockGen. DO NOT EDIT.
// Source: ./reporter.go
//
// Generated by this command:
//
//	mockgen -source=./reporter.go -package=grpcmocks -destination=./mocks/reporter.mock.go -typed ExecutionReportHandler
//

// Package grpcmocks is a generated GoMock package.
package grpcmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutionReportHandler is a mock of ExecutionReportHandler interface.
type MockExecutionReportHandler struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionReportHandlerMockRecorder
	isgomock struct{}
}

// MockExecutionReportHandlerMockRecorder is the mock recorder for MockExecutionReportHandler.
type MockExecutionReportHandlerMockRecorder struct {
	mock *MockExecutionReportHandler
}

// NewMockExecutionReportHandler creates a new mock instance.
func NewMockExecutionReportHandler(ctrl *gomock.Controller) *MockExecutionReportHandler {
	mock := &MockExecutionReportHandler{ctrl: ctrl}
	mock.recorder = &MockExecutionReportHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionReportHandler) EXPECT() *MockExecutionReportHandlerMockRecorder {
	return m.recorder
}

// AppendExecutionLogs mocks base method.
func (m *MockExecutionReportHandler) AppendExecutionLogs(ctx context.Context, executionID, taskID int64, logs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendExecutionLogs", ctx, executionID, taskID, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendExecutionLogs indicates an expected call of AppendExecutionLogs.
func (mr *MockExecutionReportHandlerMockRecorder) AppendExecutionLogs(ctx, executionID, taskID, logs any) *MockExecutionReportHandlerAppendExecutionLogsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendExecutionLogs", reflect.TypeOf((*MockExecutionReportHandler)(nil).AppendExecutionLogs), ctx, executionID, taskID, logs)
	return &MockExecutionReportHandlerAppendExecutionLogsCall{Call: call}
}

// MockExecutionReportHandlerAppendExecutionLogsCall wrap *gomock.Call
type MockExecutionReportHandlerAppendExecutionLogsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionReportHandlerAppendExecutionLogsCall) Return(arg0 error) *MockExecutionReportHandlerAppendExecutionLogsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionReportHandlerAppendExecutionLogsCall) Do(f func(context.Context, int64, int64, []string) error) *MockExecutionReportHandlerAppendExecutionLogsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionReportHandlerAppendExecutionLogsCall) DoAndReturn(f func(context.Context, int64, int64, []string) error) *MockExecutionReportHandlerAppendExecutionLogsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateState mocks base method.
func (m *MockExecutionReportHandler) UpdateState(ctx context.Context, state domain.ExecutionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateState indicates an expected call of UpdateState.
func (mr *MockExecutionReportHandlerMockRecorder) UpdateState(ctx, state any) *MockExecutionReportHandlerUpdateStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateState", reflect.TypeOf((*MockExecutionReportHandler)(nil).UpdateState), ctx, state)
	return &MockExecutionReportHandlerUpdateStateCall{Call: call}
}

// MockExecutionReportHandlerUpdateStateCall wrap *gomock.Call
type MockExecutionReportHandlerUpdateStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionReportHandlerUpdateStateCall) Return(arg0 error) *MockExecutionReportHandlerUpdateStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionReportHandlerUpdateStateCall) Do(f func(context.Context, domain.ExecutionState) error) *MockExecutionReportHandlerUpdateStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionReportHandlerUpdateStateCall) DoAndReturn(f func(context.Context, domain.ExecutionState) error) *MockExecutionReportHandlerUpdateStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
