// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go
//
// Generated by this command:
//
//	mockgen -source=./types.go -package=invokermocks -destination=./mocks/invoker.mock.go -typed
//

// Package invokermocks is a generated GoMock package.
package invokermocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockInvoker is a mock of Invoker interface.
type MockInvoker struct {
	ctrl     *gomock.Controller
	recorder *MockInvokerMockRecorder
	isgomock struct{}
}

// MockInvokerMockRecorder is the mock recorder for MockInvoker.
type MockInvokerMockRecorder struct {
	mock *MockInvoker
}

// NewMockInvoker creates a new mock instance.
func NewMockInvoker(ctrl *gomock.Controller) *MockInvoker {
	mock := &MockInvoker{ctrl: ctrl}
	mock.recorder = &MockInvokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoker) EXPECT() *MockInvokerMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockInvoker) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockInvokerMockRecorder) Name() *MockInvokerNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockInvoker)(nil).Name))
	return &MockInvokerNameCall{Call: call}
}

// MockInvokerNameCall wrap *gomock.Call
type MockInvokerNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInvokerNameCall) Return(arg0 string) *MockInvokerNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInvokerNameCall) Do(f func() string) *MockInvokerNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInvokerNameCall) DoAndReturn(f func() string) *MockInvokerNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Run mocks base method.
func (m *MockInvoker) Run(ctx context.Context, execution domain.TaskExecution) (domain.ExecutionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, execution)
	ret0, _ := ret[0].(domain.ExecutionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockInvokerMockRecorder) Run(ctx, execution any) *MockInvokerRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockInvoker)(nil).Run), ctx, execution)
	return &MockInvokerRunCall{Call: call}
}

// MockInvokerRunCall wrap *gomock.Call
type MockInvokerRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInvokerRunCall) Return(arg0 domain.ExecutionState, arg1 error) *MockInvokerRunCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInvokerRunCall) Do(f func(context.Context, domain.TaskExecution) (domain.ExecutionState, error)) *MockInvokerRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInvokerRunCall) DoAndReturn(f func(context.Context, domain.TaskExecution) (domain.ExecutionState, error)) *MockInvokerRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Terminate mocks base method.
func (m *MockInvoker) Terminate(ctx context.Context, execution domain.TaskExecution, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Terminate", ctx, execution, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Terminate indicates an expected call of Terminate.
func (mr *MockInvokerMockRecorder) Terminate(ctx, execution, reason any) *MockInvokerTerminateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockInvoker)(nil).Terminate), ctx, execution, reason)
	return &MockInvokerTerminateCall{Call: call}
}

// MockInvokerTerminateCall wrap *gomock.Call
type MockInvokerTerminateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInvokerTerminateCall) Return(arg0 error) *MockInvokerTerminateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInvokerTerminateCall) Do(f func(context.Context, domain.TaskExecution, string) error) *MockInvokerTerminateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInvokerTerminateCall) DoAndReturn(f func(context.Context, domain.TaskExecution, string) error) *MockInvokerTerminateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
