// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package execute

import (
	"context"
	"github.com/Duke1616/ecmdb/internal/execute/internal/event"
	"github.com/Duke1616/ecmdb/internal/execute/internal/service"
	"github.com/Duke1616/ecmdb/internal/execute/internal/web"
	"github.com/Duke1616/ecmdb/internal/runner"
	"github.com/Duke1616/ecmdb/pkg/registry"
	"github.com/ecodeclub/mq-api"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func InitModule(q mq.MQ, runnerSvc *runner.Module) (*Module, error) {
	serviceService := runnerSvc.Svc
	service2 := service.NewService(q, serviceService)
	handler := web.NewHandler(service2)
	executeConsumer := initExecuteConsumer(q, service2)
	module := &Module{
		Hdl: handler,
		Svc: service2,
		c:   executeConsumer,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(service.NewService, web.NewHandler)

func initExecuteConsumer(q mq.MQ, svc service.Service) *event.ExecuteConsumer {
	var cfg registry.Instance
	err := viper.UnmarshalKey("worker", &cfg)

	consumer, err := event.NewExecuteConsumer(q, svc, cfg.Topic)
	if err != nil {
		panic(err)
	}

	consumer.Start(context.Background())
	return consumer
}
