// Code generated by MockGen. DO NOT EDIT.
// Source: ./task_acquirer.go
//
// Generated by this command:
//
//	mockgen -source=./task_acquirer.go -package=acquirermocks -destination=./mocks/task_acquirer.mock.go -typed
//

// Package acquirermocks is a generated GoMock package.
package acquirermocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskAcquirer is a mock of TaskAcquirer interface.
type MockTaskAcquirer struct {
	ctrl     *gomock.Controller
	recorder *MockTaskAcquirerMockRecorder
	isgomock struct{}
}

// MockTaskAcquirerMockRecorder is the mock recorder for MockTaskAcquirer.
type MockTaskAcquirerMockRecorder struct {
	mock *MockTaskAcquirer
}

// NewMockTaskAcquirer creates a new mock instance.
func NewMockTaskAcquirer(ctrl *gomock.Controller) *MockTaskAcquirer {
	mock := &MockTaskAcquirer{ctrl: ctrl}
	mock.recorder = &MockTaskAcquirerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskAcquirer) EXPECT() *MockTaskAcquirerMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockTaskAcquirer) Acquire(ctx context.Context, taskID, version int64, scheduleNodeID string) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, taskID, version, scheduleNodeID)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockTaskAcquirerMockRecorder) Acquire(ctx, taskID, version, scheduleNodeID any) *MockTaskAcquirerAcquireCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockTaskAcquirer)(nil).Acquire), ctx, taskID, version, scheduleNodeID)
	return &MockTaskAcquirerAcquireCall{Call: call}
}

// MockTaskAcquirerAcquireCall wrap *gomock.Call
type MockTaskAcquirerAcquireCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskAcquirerAcquireCall) Return(arg0 domain.Task, arg1 error) *MockTaskAcquirerAcquireCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskAcquirerAcquireCall) Do(f func(context.Context, int64, int64, string) (domain.Task, error)) *MockTaskAcquirerAcquireCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskAcquirerAcquireCall) DoAndReturn(f func(context.Context, int64, int64, string) (domain.Task, error)) *MockTaskAcquirerAcquireCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Release mocks base method.
func (m *MockTaskAcquirer) Release(ctx context.Context, taskID int64, scheduleNodeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, taskID, scheduleNodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockTaskAcquirerMockRecorder) Release(ctx, taskID, scheduleNodeID any) *MockTaskAcquirerReleaseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockTaskAcquirer)(nil).Release), ctx, taskID, scheduleNodeID)
	return &MockTaskAcquirerReleaseCall{Call: call}
}

// MockTaskAcquirerReleaseCall wrap *gomock.Call
type MockTaskAcquirerReleaseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskAcquirerReleaseCall) Return(arg0 error) *MockTaskAcquirerReleaseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskAcquirerReleaseCall) Do(f func(context.Context, int64, string) error) *MockTaskAcquirerReleaseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskAcquirerReleaseCall) DoAndReturn(f func(context.Context, int64, string) error) *MockTaskAcquirerReleaseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Renew mocks base method.
func (m *MockTaskAcquirer) Renew(ctx context.Context, scheduleNodeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Renew", ctx, scheduleNodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Renew indicates an expected call of Renew.
func (mr *MockTaskAcquirerMockRecorder) Renew(ctx, scheduleNodeID any) *MockTaskAcquirerRenewCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Renew", reflect.TypeOf((*MockTaskAcquirer)(nil).Renew), ctx, scheduleNodeID)
	return &MockTaskAcquirerRenewCall{Call: call}
}

// MockTaskAcquirerRenewCall wrap *gomock.Call
type MockTaskAcquirerRenewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaskAcquirerRenewCall) Return(arg0 error) *MockTaskAcquirerRenewCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaskAcquirerRenewCall) Do(f func(context.Context, string) error) *MockTaskAcquirerRenewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaskAcquirerRenewCall) DoAndReturn(f func(context.Context, string) error) *MockTaskAcquirerRenewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
