// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=programmocks -destination=./mocks/service.mock.go -typed
//

// Package programmocks is a generated GoMock package.
package programmocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	program "github.com/Duke1616/etask/internal/service/program"
	gomock "go.uber.org/mock/gomock"
)

// MockCodebookReader is a mock of CodebookReader interface.
type MockCodebookReader struct {
	ctrl     *gomock.Controller
	recorder *MockCodebookReaderMockRecorder
	isgomock struct{}
}

// MockCodebookReaderMockRecorder is the mock recorder for MockCodebookReader.
type MockCodebookReaderMockRecorder struct {
	mock *MockCodebookReader
}

// NewMockCodebookReader creates a new mock instance.
func NewMockCodebookReader(ctrl *gomock.Controller) *MockCodebookReader {
	mock := &MockCodebookReader{ctrl: ctrl}
	mock.recorder = &MockCodebookReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodebookReader) EXPECT() *MockCodebookReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockCodebookReader) GetByID(ctx context.Context, id int64) (domain.Codebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Codebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCodebookReaderMockRecorder) GetByID(ctx, id any) *MockCodebookReaderGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCodebookReader)(nil).GetByID), ctx, id)
	return &MockCodebookReaderGetByIDCall{Call: call}
}

// MockCodebookReaderGetByIDCall wrap *gomock.Call
type MockCodebookReaderGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodebookReaderGetByIDCall) Return(arg0 domain.Codebook, arg1 error) *MockCodebookReaderGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodebookReaderGetByIDCall) Do(f func(context.Context, int64) (domain.Codebook, error)) *MockCodebookReaderGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodebookReaderGetByIDCall) DoAndReturn(f func(context.Context, int64) (domain.Codebook, error)) *MockCodebookReaderGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// OpenSource mocks base method.
func (m *MockService) OpenSource(ctx context.Context, sourceID int64, digest string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenSource", ctx, sourceID, digest)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenSource indicates an expected call of OpenSource.
func (mr *MockServiceMockRecorder) OpenSource(ctx, sourceID, digest any) *MockServiceOpenSourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenSource", reflect.TypeOf((*MockService)(nil).OpenSource), ctx, sourceID, digest)
	return &MockServiceOpenSourceCall{Call: call}
}

// MockServiceOpenSourceCall wrap *gomock.Call
type MockServiceOpenSourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceOpenSourceCall) Return(arg0 io.ReadCloser, arg1 error) *MockServiceOpenSourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceOpenSourceCall) Do(f func(context.Context, int64, string) (io.ReadCloser, error)) *MockServiceOpenSourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceOpenSourceCall) DoAndReturn(f func(context.Context, int64, string) (io.ReadCloser, error)) *MockServiceOpenSourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Resolve mocks base method.
func (m *MockService) Resolve(ctx context.Context, spec *domain.ProgramSpec) (program.Resolution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, spec)
	ret0, _ := ret[0].(program.Resolution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockServiceMockRecorder) Resolve(ctx, spec any) *MockServiceResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockService)(nil).Resolve), ctx, spec)
	return &MockServiceResolveCall{Call: call}
}

// MockServiceResolveCall wrap *gomock.Call
type MockServiceResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceResolveCall) Return(arg0 program.Resolution, arg1 error) *MockServiceResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceResolveCall) Do(f func(context.Context, *domain.ProgramSpec) (program.Resolution, error)) *MockServiceResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceResolveCall) DoAndReturn(f func(context.Context, *domain.ProgramSpec) (program.Resolution, error)) *MockServiceResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
