// Code generated by MockGen. DO NOT EDIT.
// Source: ./blobstore.go
//
// Generated by this command:
//
//	mockgen -source=./blobstore.go -package=blobstoremocks -destination=./mocks/blobstore.mock.go -typed
//

// Package blobstoremocks is a generated GoMock package.
package blobstoremocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockStore) Open(ctx context.Context, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockStoreMockRecorder) Open(ctx, key any) *MockStoreOpenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockStore)(nil).Open), ctx, key)
	return &MockStoreOpenCall{Call: call}
}

// MockStoreOpenCall wrap *gomock.Call
type MockStoreOpenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreOpenCall) Return(arg0 io.ReadCloser, arg1 error) *MockStoreOpenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreOpenCall) Do(f func(context.Context, string) (io.ReadCloser, error)) *MockStoreOpenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreOpenCall) DoAndReturn(f func(context.Context, string) (io.ReadCloser, error)) *MockStoreOpenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Put mocks base method.
func (m *MockStore) Put(ctx context.Context, key string, src io.Reader, size int64, checksum string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, src, size, checksum)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockStoreMockRecorder) Put(ctx, key, src, size, checksum any) *MockStorePutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockStore)(nil).Put), ctx, key, src, size, checksum)
	return &MockStorePutCall{Call: call}
}

// MockStorePutCall wrap *gomock.Call
type MockStorePutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorePutCall) Return(arg0 error) *MockStorePutCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorePutCall) Do(f func(context.Context, string, io.Reader, int64, string) error) *MockStorePutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorePutCall) DoAndReturn(f func(context.Context, string, io.Reader, int64, string) error) *MockStorePutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
