// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"fmt"
	"github.com/Duke1616/ecmdb/api/proto/gen/executor/v1"
	"github.com/Duke1616/ecmdb/internal/grpc"
	"github.com/Duke1616/ecmdb/ioc"
	"github.com/Duke1616/ecmdb/pkg/grpc/registry"
	"github.com/Duke1616/ecmdb/pkg/grpc/registry/etcd"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"go.etcd.io/etcd/client/v3"
)

// Injectors from wire.go:

func InitExecuteApp() *ExecuteApp {
	client := ioc.InitEtcdClient()
	registry := InitRegistry(client)
	server := InitExecutorGRPCServer(registry)
	executeApp := &ExecuteApp{
		Server: server,
	}
	return executeApp
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitEtcdClient, InitRegistry)

	grpcServerSet = wire.NewSet(
		InitExecutorGRPCServer,
	)
)

// InitRegistry 初始化注册中心
func InitRegistry(client *clientv3.Client) registry.Registry {
	reg, err := etcd.NewRegistry(client)
	if err != nil {
		panic(err)
	}
	return reg
}

// InitExecutorGRPCServer 初始化 Executor gRPC 服务器
func InitExecutorGRPCServer(reg registry.Registry) *grpc.Server {
	var cfg ServerConfig
	err := viper.UnmarshalKey("server.executor.grpc", &cfg)
	if err != nil {
		panic(err)
	}

	server := grpc.NewServer(cfg.Id, cfg.Name, cfg.Addr(), reg)

	executor := grpc.NewExecutor()
	executorv1.RegisterExecutorServiceServer(server.Server, executor)

	return server
}

type ServerConfig struct {
	Id   string `mapstructure:"id"`
	Name string `mapstructure:"name"`
	Host string `mapstructure:"host"`
	Port int    `mapstructure:"port"`
}

// Addr 返回服务器地址
func (c *ServerConfig) Addr() string {
	return fmt.Sprintf("%s:%d", c.Host, c.Port)
}

type ExecuteApp struct {
	Server *grpc.Server
}
