// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/ework-runner/internal/grpc"
	"github.com/Duke1616/ework-runner/internal/grpc/scripts"
	"github.com/Duke1616/ework-runner/ioc"
	grpc2 "github.com/Duke1616/ework-runner/pkg/grpc"
	"github.com/Duke1616/ework-runner/pkg/grpc/registry"
	"github.com/Duke1616/ework-runner/pkg/grpc/registry/etcd"
	"github.com/Duke1616/ework-runner/pkg/netx"
	"github.com/Duke1616/ework-runner/sdk/executor"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"go.etcd.io/etcd/client/v3"
)

// Injectors from wire.go:

func InitExecuteApp() *ExecuteApp {
	config := InitConfig()
	client := ioc.InitEtcdClient()
	registry := InitRegistry(client)
	executor := InitExecutor(config, registry)
	server := InitExecutorServer(executor)
	executeApp := &ExecuteApp{
		Server: server,
	}
	return executeApp
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitEtcdClient, InitRegistry)

	ExecutorSet = wire.NewSet(
		InitConfig,
		InitExecutor,
		InitExecutorServer,
	)
)

// InitRegistry 初始化注册中心
func InitRegistry(client *clientv3.Client) registry.Registry {

	reg, err := etcd.NewRegistryWithPrefix(client, "service")
	if err != nil {
		panic(err)
	}
	return reg
}

// InitConfig 初始化配置
func InitConfig() *executor.Config {
	host := viper.GetString("server.executor.grpc.host")
	if host == "0.0.0.0" || host == "" {
		host = netx.GetOutboundIP()
	}

	return &executor.Config{
		NodeID:              viper.GetString("server.executor.grpc.id"),
		ServiceName:         viper.GetString("server.executor.grpc.name"),
		Addr:                host + ":" + viper.GetString("server.executor.grpc.port"),
		ReporterServiceName: "scheduler",
	}
}

// InitExecutor 初始化 SDK Executor 实例
func InitExecutor(cfg *executor.Config, reg registry.Registry) *executor.Executor {
	exec, err := executor.NewExecutor(cfg, reg)
	if err != nil {
		panic(err)
	}

	exec.RegisterHandler(&grpc.DemoTaskHandler{})
	exec.RegisterHandler(scripts.NewShellTaskHandler())
	exec.RegisterHandler(scripts.NewPythonTaskHandler())

	if err = exec.InitComponents(); err != nil {
		panic(err)
	}

	return exec
}

// InitExecutorServer 从 Executor 中提取 ego Server
func InitExecutorServer(exec *executor.Executor) *grpc2.Server {
	return exec.Server()
}

type ExecuteApp struct {
	Server *grpc2.Server
}
