// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package worker

import (
	"github.com/Duke1616/ecmdb/internal/worker/internal/event"
	"github.com/Duke1616/ecmdb/internal/worker/internal/service"
	"github.com/Duke1616/ecmdb/internal/worker/internal/web"
	"github.com/ecodeclub/mq-api"
)

// Injectors from wire.go:

func InitModule(q mq.MQ) (*Module, error) {
	taskWorkerEventProducer, err := event.NewTaskWorkerEventProducer(q)
	if err != nil {
		return nil, err
	}
	serviceService := service.NewService(q, taskWorkerEventProducer)
	handler := web.NewHandler(serviceService)
	module := &Module{
		Hdl:   handler,
		Svc:   serviceService,
		Event: taskWorkerEventProducer,
	}
	return module, nil
}
