// Code generated by MockGen. DO NOT EDIT.
// Source: ./logger.go
//
// Generated by this command:
//
//	mockgen -source=./logger.go -package=tasklogmocks -destination=./mocks/logger.mock.go -typed Sink
//

// Package tasklogmocks is a generated GoMock package.
package tasklogmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSink is a mock of Sink interface.
type MockSink struct {
	ctrl     *gomock.Controller
	recorder *MockSinkMockRecorder
	isgomock struct{}
}

// MockSinkMockRecorder is the mock recorder for MockSink.
type MockSinkMockRecorder struct {
	mock *MockSink
}

// NewMockSink creates a new mock instance.
func NewMockSink(ctrl *gomock.Controller) *MockSink {
	mock := &MockSink{ctrl: ctrl}
	mock.recorder = &MockSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSink) EXPECT() *MockSinkMockRecorder {
	return m.recorder
}

// WriteBatch mocks base method.
func (m *MockSink) WriteBatch(ctx context.Context, logs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBatch", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteBatch indicates an expected call of WriteBatch.
func (mr *MockSinkMockRecorder) WriteBatch(ctx, logs any) *MockSinkWriteBatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBatch", reflect.TypeOf((*MockSink)(nil).WriteBatch), ctx, logs)
	return &MockSinkWriteBatchCall{Call: call}
}

// MockSinkWriteBatchCall wrap *gomock.Call
type MockSinkWriteBatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSinkWriteBatchCall) Return(arg0 error) *MockSinkWriteBatchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSinkWriteBatchCall) Do(f func(context.Context, []string) error) *MockSinkWriteBatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSinkWriteBatchCall) DoAndReturn(f func(context.Context, []string) error) *MockSinkWriteBatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
