// Code generated by eiam permgen. DO NOT EDIT.

package perm

// Artifact 脚本引擎/制品仓库
var Artifact = struct {
	Module   string
	Activate string // 切换制品 [租户级]
	Publish  string // 发布制品 [租户级]
	Status   string // 制品状态 [租户级 · 静默]
	View     string // 制品发布记录 [租户级]
}{
	Module:   "task:artifact",
	Activate: "task:artifact:activate",
	Publish:  "task:artifact:publish",
	Status:   "task:artifact:status",
	View:     "task:artifact:view",
}

// CodeAssist 脚本引擎/AI 助手
var CodeAssist = struct {
	Module          string
	AddConversation string // 创建 AI 会话 [租户级]
	ApplyChangeSet  string // 应用 AI 项目变更 [租户级]
	Chat            string // 发送 AI 消息 [租户级]
	GetConversation string // AI 会话详情 [租户级 · 静默]
	View            string // AI 会话列表 [租户级]
}{
	Module:          "task:code_assist",
	AddConversation: "task:code_assist:add_conversation",
	ApplyChangeSet:  "task:code_assist:apply_change_set",
	Chat:            "task:code_assist:chat",
	GetConversation: "task:code_assist:get_conversation",
	View:            "task:code_assist:view",
}

// Codebook 脚本引擎/脚本模板
var Codebook = struct {
	Module              string
	Add                 string // 创建模板 [租户级]
	AddProject          string // 创建项目 [租户级]
	AddVersion          string // 创建版本 [租户级]
	Children            string // 代码资源子节点 [租户级 · 静默]
	Delete              string // 删除脚本模板 [租户级]
	DeleteProject       string // 归档项目 [租户级]
	Download            string // 下载项目文件 [租户级 · 静默]
	Edit                string // 更新模板 [租户级]
	EditProject         string // 更新项目 [租户级]
	Get                 string // 模板详情 [租户级]
	GetProject          string // 项目详情 [租户级 · 静默]
	GetVersion          string // 版本详情 [租户级]
	Import              string // 导入项目文件 [租户级 · 静默]
	ProjectDeleteImpact string // 项目删除影响 [租户级 · 静默]
	PurgeProject        string // 删除项目 [租户级]
	ReferenceProjects   string // 可引用项目列表 [租户级 · 静默]
	Rename              string // 重命名模板 [租户级]
	RestoreProject      string // 恢复项目 [租户级]
	Sort                string // 模板排序 [租户级]
	UseVersion          string // 使用版本 [租户级]
	ViewProject         string // 项目列表 [租户级]
	ViewRunners         string // 当前绑定执行单元 [租户级 · 跨域: runner · 静默]
	ViewTree            string // 代码资源树 [租户级]
	ViewVersion         string // 版本列表 [租户级]
	ViewWorkspaceTree   string // 读取制品文件 [租户级]
}{
	Module:              "task:codebook",
	Add:                 "task:codebook:add",
	AddProject:          "task:codebook:add_project",
	AddVersion:          "task:codebook:add_version",
	Children:            "task:codebook:children",
	Delete:              "task:codebook:delete",
	DeleteProject:       "task:codebook:delete_project",
	Download:            "task:codebook:download",
	Edit:                "task:codebook:edit",
	EditProject:         "task:codebook:edit_project",
	Get:                 "task:codebook:get",
	GetProject:          "task:codebook:get_project",
	GetVersion:          "task:codebook:get_version",
	Import:              "task:codebook:import",
	ProjectDeleteImpact: "task:codebook:project_delete_impact",
	PurgeProject:        "task:codebook:purge_project",
	ReferenceProjects:   "task:codebook:reference_projects",
	Rename:              "task:codebook:rename",
	RestoreProject:      "task:codebook:restore_project",
	Sort:                "task:codebook:sort",
	UseVersion:          "task:codebook:use_version",
	ViewProject:         "task:codebook:view_project",
	ViewRunners:         "task:codebook:view_runners",
	ViewTree:            "task:codebook:view_tree",
	ViewVersion:         "task:codebook:view_version",
	ViewWorkspaceTree:   "task:codebook:view_workspace_tree",
}

// ExecutionPool 资源池管理
var ExecutionPool = struct {
	Module            string
	AdminBind         string // 管理绑定资源池 [系统级]
	AdminBindingsView string // 资源池绑定管理列表 [系统级]
	AdminDisable      string // 管理禁用资源池绑定 [系统级]
	AdminEnable       string // 管理启用资源池绑定 [系统级]
	AdminUnbind       string // 管理解绑资源池 [系统级]
	AdminView         string // 资源池管理列表 [系统级]
}{
	Module:            "task:execution-pool",
	AdminBind:         "task:execution-pool:admin_bind",
	AdminBindingsView: "task:execution-pool:admin_bindings_view",
	AdminDisable:      "task:execution-pool:admin_disable",
	AdminEnable:       "task:execution-pool:admin_enable",
	AdminUnbind:       "task:execution-pool:admin_unbind",
	AdminView:         "task:execution-pool:admin_view",
}

// Manager 任务管理
var Manager = struct {
	Module              string
	Add                 string // 创建任务 [租户级]
	Delete              string // 删除任务 [租户级]
	Edit                string // 更新任务 [租户级]
	ExecutionEvents     string // 订阅任务执行事件 [租户级 · 静默]
	ExecutionLogs       string // 查看执行日志流 [租户级 · 静默]
	ExecutionParameters string // 执行参数 [租户级]
	Executions          string // 执行记录 [租户级]
	Get                 string // 任务详情 [租户级]
	Logs                string // 任务日志 [租户级]
	Start               string // 运行任务 [租户级]
	Stop                string // 停止任务 [租户级]
	TaskEvents          string // 订阅任务状态事件 [租户级 · 静默]
	Terminate           string // 终止执行 [租户级]
	View                string // 任务列表 [租户级]
}{
	Module:              "task:manager",
	Add:                 "task:manager:add",
	Delete:              "task:manager:delete",
	Edit:                "task:manager:edit",
	ExecutionEvents:     "task:manager:execution_events",
	ExecutionLogs:       "task:manager:execution_logs",
	ExecutionParameters: "task:manager:execution_parameters",
	Executions:          "task:manager:executions",
	Get:                 "task:manager:get",
	Logs:                "task:manager:logs",
	Start:               "task:manager:start",
	Stop:                "task:manager:stop",
	TaskEvents:          "task:manager:task_events",
	Terminate:           "task:manager:terminate",
	View:                "task:manager:view",
}

// Preview 脚本引擎/试运行
var Preview = struct {
	Module   string
	Run      string // 执行脚本试运行 [租户级]
	View     string // 查看试运行 [租户级]
	ViewLogs string // 查看试运行日志 [租户级 · 静默]
}{
	Module:   "task:preview",
	Run:      "task:preview:run",
	View:     "task:preview:view",
	ViewLogs: "task:preview:view_logs",
}

// Resource 执行资源
var Resource = struct {
	Module string
	View   string // 执行资源列表 [租户级]
}{
	Module: "task:resource",
	View:   "task:resource:view",
}

// Runner 执行单元
var Runner = struct {
	Module                string
	Add                   string // 注册执行单元 [租户级]
	Delete                string // 删除执行单元 [租户级]
	Edit                  string // 更新执行单元 [租户级]
	Get                   string // 执行单元详情 [租户级]
	Ids                   string // 批量查询执行单元 [租户级 · 静默]
	View                  string // 执行单元列表 [租户级]
	ViewExcludeCodebookId string // 复用执行单元 [租户级 · 静默]
}{
	Module:                "task:runner",
	Add:                   "task:runner:add",
	Delete:                "task:runner:delete",
	Edit:                  "task:runner:edit",
	Get:                   "task:runner:get",
	Ids:                   "task:runner:ids",
	View:                  "task:runner:view",
	ViewExcludeCodebookId: "task:runner:view_exclude_codebook_id",
}

// Variable 全局变量
var Variable = struct {
	Module string
	Add    string // 创建全局变量 [租户级]
	Delete string // 删除全局变量 [租户级]
	Edit   string // 更新全局变量 [租户级]
	Get    string // 全局变量详情 [租户级]
	View   string // 全局变量列表 [租户级]
}{
	Module: "task:variable",
	Add:    "task:variable:add",
	Delete: "task:variable:delete",
	Edit:   "task:variable:edit",
	Get:    "task:variable:get",
	View:   "task:variable:view",
}
