// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/ecmdb/internal/repository"
	"github.com/Duke1616/ecmdb/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/service/task"
	"github.com/Duke1616/ecmdb/ioc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitSchedulerApp() *ioc.SchedulerApp {
	string2 := ioc.InitNodeID()
	db := ioc.InitDB()
	taskDAO := dao.NewGORMTaskDAO(db)
	taskRepository := repository.NewTaskRepository(taskDAO)
	service := task.NewService(taskRepository)
	taskExecutionDAO := dao.NewGORMTaskExecutionDAO(db)
	taskExecutionRepository := repository.NewTaskExecutionRepository(taskExecutionDAO, taskRepository)
	taskAcquirer := ioc.InitMySQLTaskAcquirer(taskRepository)
	mq := ioc.InitMQ()
	completeProducer := ioc.InitCompleteProducer(mq)
	client := ioc.InitEtcdClient()
	registry := ioc.InitRegistry(client)
	executionService := task.NewExecutionService(string2, taskExecutionRepository, service, taskAcquirer, completeProducer, registry)
	clients := ioc.InitExecutorServiceGRPCClients(registry)
	invoker := ioc.InitInvoker(clients)
	runner := ioc.InitRunner(string2, service, executionService, taskAcquirer, invoker, completeProducer)
	executorNodePicker := ioc.InitExecutorNodePicker()
	scheduler := ioc.InitScheduler(string2, runner, service, executionService, taskAcquirer, executorNodePicker)
	retryCompensator := ioc.InitRetryCompensator(runner, executionService)
	rescheduleCompensator := ioc.InitRescheduleCompensator(runner, executionService)
	interruptCompensator := ioc.InitInterruptCompensator(clients, executionService)
	v := ioc.InitTasks(retryCompensator, rescheduleCompensator, interruptCompensator)
	schedulerApp := &ioc.SchedulerApp{
		Scheduler: scheduler,
		Tasks:     v,
	}
	return schedulerApp
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitDistributedLock, ioc.InitEtcdClient, ioc.InitMQ, ioc.InitRunner, ioc.InitInvoker, ioc.InitRegistry)

	taskSet = wire.NewSet(dao.NewGORMTaskDAO, repository.NewTaskRepository, task.NewService)

	taskExecutionSet = wire.NewSet(dao.NewGORMTaskExecutionDAO, repository.NewTaskExecutionRepository, task.NewExecutionService)

	schedulerSet = wire.NewSet(ioc.InitNodeID, ioc.InitScheduler, ioc.InitMySQLTaskAcquirer, ioc.InitExecutorNodePicker)

	compensatorSet = wire.NewSet(ioc.InitRetryCompensator, ioc.InitRescheduleCompensator, ioc.InitInterruptCompensator)

	producerSet = wire.NewSet(ioc.InitCompleteProducer)

	grpcSet = wire.NewSet(ioc.InitExecutorServiceGRPCClients)
)
