// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/ework-runner/internal/grpc"
	"github.com/Duke1616/ework-runner/internal/repository"
	"github.com/Duke1616/ework-runner/internal/repository/dao"
	"github.com/Duke1616/ework-runner/internal/service/task"
	task2 "github.com/Duke1616/ework-runner/internal/web/task"
	"github.com/Duke1616/ework-runner/ioc"
	"github.com/Duke1616/ework-runner/pkg/ginx/middleware"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitSchedulerApp() *ioc.SchedulerApp {
	v := ioc.InitGinMiddlewares()
	client := ioc.InitEtcdClient()
	clientConnInterface := ioc.InitECMDBGrpcClient(client)
	policyServiceClient := ioc.InitPolicyServiceClient(clientConnInterface)
	cmdable := ioc.InitRedis()
	provider := ioc.InitSession(cmdable)
	checkPolicyMiddlewareBuilder := middleware.NewCheckPolicyMiddlewareBuilder(policyServiceClient, provider)
	db := ioc.InitDB()
	taskDAO := dao.NewGORMTaskDAO(db)
	taskRepository := repository.NewTaskRepository(taskDAO)
	service := task.NewService(taskRepository)
	handler := task2.NewHandler(service)
	component := ioc.InitGinWebServer(v, checkPolicyMiddlewareBuilder, provider, handler)
	registry := ioc.InitRegistry(client)
	string2 := ioc.InitNodeID()
	taskExecutionDAO := dao.NewGORMTaskExecutionDAO(db)
	taskExecutionRepository := repository.NewTaskExecutionRepository(taskExecutionDAO, taskRepository)
	taskAcquirer := ioc.InitMySQLTaskAcquirer(taskRepository)
	mq := ioc.InitMQ()
	completeProducer := ioc.InitCompleteProducer(mq)
	executionService := task.NewExecutionService(string2, taskExecutionRepository, service, taskAcquirer, completeProducer, registry)
	reporterServer := grpc.NewReporterServer(executionService)
	server := ioc.InitSchedulerNodeGRPCServer(registry, reporterServer)
	clients := ioc.InitExecutorServiceGRPCClients(registry)
	invoker := ioc.InitInvoker(clients)
	runner := ioc.InitRunner(string2, service, executionService, taskAcquirer, invoker, completeProducer)
	executorNodePicker := ioc.InitExecutorNodePicker(registry)
	scheduler := ioc.InitScheduler(string2, runner, service, executionService, taskAcquirer, executorNodePicker)
	retryCompensator := ioc.InitRetryCompensator(runner, executionService)
	rescheduleCompensator := ioc.InitRescheduleCompensator(runner, executionService)
	interruptCompensator := ioc.InitInterruptCompensator(clients, executionService)
	completeConsumer := ioc.InitCompleteEventConsumer(mq, service, executionService, taskAcquirer)
	v2 := ioc.InitTasks(retryCompensator, rescheduleCompensator, interruptCompensator, completeConsumer)
	schedulerApp := &ioc.SchedulerApp{
		Web:       component,
		Server:    server,
		Scheduler: scheduler,
		Tasks:     v2,
	}
	return schedulerApp
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitDistributedLock, ioc.InitEtcdClient, ioc.InitMQ, ioc.InitRunner, ioc.InitInvoker, ioc.InitRegistry)

	webSetup = wire.NewSet(ioc.InitECMDBGrpcClient, ioc.InitPolicyServiceClient, middleware.NewCheckPolicyMiddlewareBuilder, ioc.InitSession, ioc.InitGinMiddlewares, ioc.InitGinWebServer)

	taskSet = wire.NewSet(dao.NewGORMTaskDAO, repository.NewTaskRepository, task.NewService, task2.NewHandler)

	taskExecutionSet = wire.NewSet(dao.NewGORMTaskExecutionDAO, repository.NewTaskExecutionRepository, task.NewExecutionService)

	schedulerSet = wire.NewSet(ioc.InitNodeID, ioc.InitScheduler, ioc.InitMySQLTaskAcquirer, ioc.InitExecutorNodePicker)

	compensatorSet = wire.NewSet(ioc.InitRetryCompensator, ioc.InitRescheduleCompensator, ioc.InitInterruptCompensator)

	producerSet = wire.NewSet(ioc.InitCompleteProducer)

	grpcSet = wire.NewSet(ioc.InitExecutorServiceGRPCClients)

	consumerSet = wire.NewSet(ioc.InitCompleteEventConsumer)
)
