syntax = "proto3";

package etask.runner.v1;

option go_package = "etask/runner/v1;runner";

message Variable {
  string key = 1;
  string value = 2;
  bool secret = 3;
}

message Runner {
  int64 id = 1;
  string name = 2;
  int64 codebook_id = 3;
  string codebook_secret = 4;
  string kind = 5;
  string target = 6;
  string handler = 7;
  repeated string tags = 8;
  uint32 action = 9;
  string desc = 10;
  repeated Variable variables = 11;
  int64 ctime = 12;
  int64 utime = 13;
  string program_kind = 14;
}

message FindRunnerByIDRequest {
  int64 id = 1;
}

message FindRunnerByIDResponse {
  Runner runner = 1;
}

message ListRunnersByCodebookIDRequest {
  int64 codebook_id = 1;
}

message ListRunnersByCodebookIDResponse {
  repeated Runner runners = 1;
}

service RunnerService {
  rpc FindRunnerByID(FindRunnerByIDRequest) returns (FindRunnerByIDResponse);
  rpc ListRunnersByCodebookID(ListRunnersByCodebookIDRequest) returns (ListRunnersByCodebookIDResponse);
}
