// Code generated by MockGen. DO NOT EDIT.
// Source: ./consumer.go
//
// Generated by this command:
//
//	mockgen -source=./consumer.go -package=executionmocks -destination=./mocks/consumer.mock.go -typed EventHandler
//

// Package executionmocks is a generated GoMock package.
package executionmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventHandler is a mock of EventHandler interface.
type MockEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockEventHandlerMockRecorder
	isgomock struct{}
}

// MockEventHandlerMockRecorder is the mock recorder for MockEventHandler.
type MockEventHandlerMockRecorder struct {
	mock *MockEventHandler
}

// NewMockEventHandler creates a new mock instance.
func NewMockEventHandler(ctrl *gomock.Controller) *MockEventHandler {
	mock := &MockEventHandler{ctrl: ctrl}
	mock.recorder = &MockEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventHandler) EXPECT() *MockEventHandlerMockRecorder {
	return m.recorder
}

// AppendExecutionLogs mocks base method.
func (m *MockEventHandler) AppendExecutionLogs(ctx context.Context, executionID, taskID int64, logs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendExecutionLogs", ctx, executionID, taskID, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendExecutionLogs indicates an expected call of AppendExecutionLogs.
func (mr *MockEventHandlerMockRecorder) AppendExecutionLogs(ctx, executionID, taskID, logs any) *MockEventHandlerAppendExecutionLogsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendExecutionLogs", reflect.TypeOf((*MockEventHandler)(nil).AppendExecutionLogs), ctx, executionID, taskID, logs)
	return &MockEventHandlerAppendExecutionLogsCall{Call: call}
}

// MockEventHandlerAppendExecutionLogsCall wrap *gomock.Call
type MockEventHandlerAppendExecutionLogsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventHandlerAppendExecutionLogsCall) Return(arg0 error) *MockEventHandlerAppendExecutionLogsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventHandlerAppendExecutionLogsCall) Do(f func(context.Context, int64, int64, []string) error) *MockEventHandlerAppendExecutionLogsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventHandlerAppendExecutionLogsCall) DoAndReturn(f func(context.Context, int64, int64, []string) error) *MockEventHandlerAppendExecutionLogsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByID mocks base method.
func (m *MockEventHandler) FindByID(ctx context.Context, id int64) (domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockEventHandlerMockRecorder) FindByID(ctx, id any) *MockEventHandlerFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockEventHandler)(nil).FindByID), ctx, id)
	return &MockEventHandlerFindByIDCall{Call: call}
}

// MockEventHandlerFindByIDCall wrap *gomock.Call
type MockEventHandlerFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventHandlerFindByIDCall) Return(arg0 domain.TaskExecution, arg1 error) *MockEventHandlerFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventHandlerFindByIDCall) Do(f func(context.Context, int64) (domain.TaskExecution, error)) *MockEventHandlerFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventHandlerFindByIDCall) DoAndReturn(f func(context.Context, int64) (domain.TaskExecution, error)) *MockEventHandlerFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateState mocks base method.
func (m *MockEventHandler) UpdateState(ctx context.Context, state domain.ExecutionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateState indicates an expected call of UpdateState.
func (mr *MockEventHandlerMockRecorder) UpdateState(ctx, state any) *MockEventHandlerUpdateStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateState", reflect.TypeOf((*MockEventHandler)(nil).UpdateState), ctx, state)
	return &MockEventHandlerUpdateStateCall{Call: call}
}

// MockEventHandlerUpdateStateCall wrap *gomock.Call
type MockEventHandlerUpdateStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventHandlerUpdateStateCall) Return(arg0 error) *MockEventHandlerUpdateStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventHandlerUpdateStateCall) Do(f func(context.Context, domain.ExecutionState) error) *MockEventHandlerUpdateStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventHandlerUpdateStateCall) DoAndReturn(f func(context.Context, domain.ExecutionState) error) *MockEventHandlerUpdateStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
