// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=terminationmocks -destination=./mocks/service.mock.go -typed
//

// Package terminationmocks is a generated GoMock package.
package terminationmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	termination "github.com/Duke1616/etask/internal/service/termination"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockService) Attach(ctx context.Context, execution domain.TaskExecution) (domain.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, execution)
	ret0, _ := ret[0].(domain.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attach indicates an expected call of Attach.
func (mr *MockServiceMockRecorder) Attach(ctx, execution any) *MockServiceAttachCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockService)(nil).Attach), ctx, execution)
	return &MockServiceAttachCall{Call: call}
}

// MockServiceAttachCall wrap *gomock.Call
type MockServiceAttachCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAttachCall) Return(arg0 domain.TaskExecution, arg1 error) *MockServiceAttachCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAttachCall) Do(f func(context.Context, domain.TaskExecution) (domain.TaskExecution, error)) *MockServiceAttachCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAttachCall) DoAndReturn(f func(context.Context, domain.TaskExecution) (domain.TaskExecution, error)) *MockServiceAttachCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeliverPending mocks base method.
func (m *MockService) DeliverPending(ctx context.Context, limit int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliverPending", ctx, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeliverPending indicates an expected call of DeliverPending.
func (mr *MockServiceMockRecorder) DeliverPending(ctx, limit any) *MockServiceDeliverPendingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliverPending", reflect.TypeOf((*MockService)(nil).DeliverPending), ctx, limit)
	return &MockServiceDeliverPendingCall{Call: call}
}

// MockServiceDeliverPendingCall wrap *gomock.Call
type MockServiceDeliverPendingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeliverPendingCall) Return(arg0 error) *MockServiceDeliverPendingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeliverPendingCall) Do(f func(context.Context, int) error) *MockServiceDeliverPendingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeliverPendingCall) DoAndReturn(f func(context.Context, int) error) *MockServiceDeliverPendingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Request mocks base method.
func (m *MockService) Request(ctx context.Context, request termination.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockServiceMockRecorder) Request(ctx, request any) *MockServiceRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockService)(nil).Request), ctx, request)
	return &MockServiceRequestCall{Call: call}
}

// MockServiceRequestCall wrap *gomock.Call
type MockServiceRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceRequestCall) Return(arg0 error) *MockServiceRequestCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceRequestCall) Do(f func(context.Context, termination.Request) error) *MockServiceRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceRequestCall) DoAndReturn(f func(context.Context, termination.Request) error) *MockServiceRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RequestExecution mocks base method.
func (m *MockService) RequestExecution(ctx context.Context, executionID int64, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestExecution", ctx, executionID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestExecution indicates an expected call of RequestExecution.
func (mr *MockServiceMockRecorder) RequestExecution(ctx, executionID, reason any) *MockServiceRequestExecutionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestExecution", reflect.TypeOf((*MockService)(nil).RequestExecution), ctx, executionID, reason)
	return &MockServiceRequestExecutionCall{Call: call}
}

// MockServiceRequestExecutionCall wrap *gomock.Call
type MockServiceRequestExecutionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceRequestExecutionCall) Return(arg0 error) *MockServiceRequestExecutionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceRequestExecutionCall) Do(f func(context.Context, int64, string) error) *MockServiceRequestExecutionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceRequestExecutionCall) DoAndReturn(f func(context.Context, int64, string) error) *MockServiceRequestExecutionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
