// Code generated by MockGen. DO NOT EDIT.
// Source: ./codebook.go
//
// Generated by this command:
//
//	mockgen -source=./codebook.go -package=codebookmocks -destination=./mocks/codebook.mock.go -typed
//

// Package codebookmocks is a generated GoMock package.
package codebookmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ArchiveProject mocks base method.
func (m *MockService) ArchiveProject(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveProject", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArchiveProject indicates an expected call of ArchiveProject.
func (mr *MockServiceMockRecorder) ArchiveProject(ctx, id any) *MockServiceArchiveProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveProject", reflect.TypeOf((*MockService)(nil).ArchiveProject), ctx, id)
	return &MockServiceArchiveProjectCall{Call: call}
}

// MockServiceArchiveProjectCall wrap *gomock.Call
type MockServiceArchiveProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceArchiveProjectCall) Return(arg0 int64, arg1 error) *MockServiceArchiveProjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceArchiveProjectCall) Do(f func(context.Context, int64) (int64, error)) *MockServiceArchiveProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceArchiveProjectCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockServiceArchiveProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Children mocks base method.
func (m *MockService) Children(ctx context.Context, projectID, parentID int64) ([]domain.Codebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Children", ctx, projectID, parentID)
	ret0, _ := ret[0].([]domain.Codebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Children indicates an expected call of Children.
func (mr *MockServiceMockRecorder) Children(ctx, projectID, parentID any) *MockServiceChildrenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Children", reflect.TypeOf((*MockService)(nil).Children), ctx, projectID, parentID)
	return &MockServiceChildrenCall{Call: call}
}

// MockServiceChildrenCall wrap *gomock.Call
type MockServiceChildrenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceChildrenCall) Return(arg0 []domain.Codebook, arg1 error) *MockServiceChildrenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceChildrenCall) Do(f func(context.Context, int64, int64) ([]domain.Codebook, error)) *MockServiceChildrenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceChildrenCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.Codebook, error)) *MockServiceChildrenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, req domain.Codebook) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, req any) *MockServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, req)
	return &MockServiceCreateCall{Call: call}
}

// MockServiceCreateCall wrap *gomock.Call
type MockServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateCall) Return(arg0 int64, arg1 error) *MockServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateCall) Do(f func(context.Context, domain.Codebook) (int64, error)) *MockServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateCall) DoAndReturn(f func(context.Context, domain.Codebook) (int64, error)) *MockServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateProject mocks base method.
func (m *MockService) CreateProject(ctx context.Context, req domain.CodebookProject) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockServiceMockRecorder) CreateProject(ctx, req any) *MockServiceCreateProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockService)(nil).CreateProject), ctx, req)
	return &MockServiceCreateProjectCall{Call: call}
}

// MockServiceCreateProjectCall wrap *gomock.Call
type MockServiceCreateProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateProjectCall) Return(arg0 int64, arg1 error) *MockServiceCreateProjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateProjectCall) Do(f func(context.Context, domain.CodebookProject) (int64, error)) *MockServiceCreateProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateProjectCall) DoAndReturn(f func(context.Context, domain.CodebookProject) (int64, error)) *MockServiceCreateProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateVersion mocks base method.
func (m *MockService) CreateVersion(ctx context.Context, req domain.CodebookVersionCreate) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVersion", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVersion indicates an expected call of CreateVersion.
func (mr *MockServiceMockRecorder) CreateVersion(ctx, req any) *MockServiceCreateVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVersion", reflect.TypeOf((*MockService)(nil).CreateVersion), ctx, req)
	return &MockServiceCreateVersionCall{Call: call}
}

// MockServiceCreateVersionCall wrap *gomock.Call
type MockServiceCreateVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateVersionCall) Return(arg0 int64, arg1 error) *MockServiceCreateVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateVersionCall) Do(f func(context.Context, domain.CodebookVersionCreate) (int64, error)) *MockServiceCreateVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateVersionCall) DoAndReturn(f func(context.Context, domain.CodebookVersionCreate) (int64, error)) *MockServiceCreateVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id any) *MockServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
	return &MockServiceDeleteCall{Call: call}
}

// MockServiceDeleteCall wrap *gomock.Call
type MockServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeleteCall) Return(arg0 int64, arg1 error) *MockServiceDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeleteCall) Do(f func(context.Context, int64) (int64, error)) *MockServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeleteCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockService) GetByID(ctx context.Context, id int64) (domain.Codebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Codebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(ctx, id any) *MockServiceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), ctx, id)
	return &MockServiceGetByIDCall{Call: call}
}

// MockServiceGetByIDCall wrap *gomock.Call
type MockServiceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetByIDCall) Return(arg0 domain.Codebook, arg1 error) *MockServiceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetByIDCall) Do(f func(context.Context, int64) (domain.Codebook, error)) *MockServiceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetByIDCall) DoAndReturn(f func(context.Context, int64) (domain.Codebook, error)) *MockServiceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProjectByID mocks base method.
func (m *MockService) GetProjectByID(ctx context.Context, id int64) (domain.CodebookProject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", ctx, id)
	ret0, _ := ret[0].(domain.CodebookProject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockServiceMockRecorder) GetProjectByID(ctx, id any) *MockServiceGetProjectByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockService)(nil).GetProjectByID), ctx, id)
	return &MockServiceGetProjectByIDCall{Call: call}
}

// MockServiceGetProjectByIDCall wrap *gomock.Call
type MockServiceGetProjectByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetProjectByIDCall) Return(arg0 domain.CodebookProject, arg1 error) *MockServiceGetProjectByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetProjectByIDCall) Do(f func(context.Context, int64) (domain.CodebookProject, error)) *MockServiceGetProjectByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetProjectByIDCall) DoAndReturn(f func(context.Context, int64) (domain.CodebookProject, error)) *MockServiceGetProjectByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetVersionByID mocks base method.
func (m *MockService) GetVersionByID(ctx context.Context, id int64) (domain.CodebookVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersionByID", ctx, id)
	ret0, _ := ret[0].(domain.CodebookVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersionByID indicates an expected call of GetVersionByID.
func (mr *MockServiceMockRecorder) GetVersionByID(ctx, id any) *MockServiceGetVersionByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersionByID", reflect.TypeOf((*MockService)(nil).GetVersionByID), ctx, id)
	return &MockServiceGetVersionByIDCall{Call: call}
}

// MockServiceGetVersionByIDCall wrap *gomock.Call
type MockServiceGetVersionByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetVersionByIDCall) Return(arg0 domain.CodebookVersion, arg1 error) *MockServiceGetVersionByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetVersionByIDCall) Do(f func(context.Context, int64) (domain.CodebookVersion, error)) *MockServiceGetVersionByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetVersionByIDCall) DoAndReturn(f func(context.Context, int64) (domain.CodebookVersion, error)) *MockServiceGetVersionByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, offset, limit int64) ([]domain.Codebook, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Codebook)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, offset, limit any) *MockServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, offset, limit)
	return &MockServiceListCall{Call: call}
}

// MockServiceListCall wrap *gomock.Call
type MockServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListCall) Return(arg0 []domain.Codebook, arg1 int64, arg2 error) *MockServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListCall) Do(f func(context.Context, int64, int64) ([]domain.Codebook, int64, error)) *MockServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.Codebook, int64, error)) *MockServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListProjects mocks base method.
func (m *MockService) ListProjects(ctx context.Context, query domain.CodebookProjectListQuery) ([]domain.CodebookProject, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, query)
	ret0, _ := ret[0].([]domain.CodebookProject)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockServiceMockRecorder) ListProjects(ctx, query any) *MockServiceListProjectsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockService)(nil).ListProjects), ctx, query)
	return &MockServiceListProjectsCall{Call: call}
}

// MockServiceListProjectsCall wrap *gomock.Call
type MockServiceListProjectsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListProjectsCall) Return(arg0 []domain.CodebookProject, arg1 int64, arg2 error) *MockServiceListProjectsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListProjectsCall) Do(f func(context.Context, domain.CodebookProjectListQuery) ([]domain.CodebookProject, int64, error)) *MockServiceListProjectsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListProjectsCall) DoAndReturn(f func(context.Context, domain.CodebookProjectListQuery) ([]domain.CodebookProject, int64, error)) *MockServiceListProjectsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListReferenceProjects mocks base method.
func (m *MockService) ListReferenceProjects(ctx context.Context, keyword string, offset, limit int64) ([]domain.CodebookProject, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReferenceProjects", ctx, keyword, offset, limit)
	ret0, _ := ret[0].([]domain.CodebookProject)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListReferenceProjects indicates an expected call of ListReferenceProjects.
func (mr *MockServiceMockRecorder) ListReferenceProjects(ctx, keyword, offset, limit any) *MockServiceListReferenceProjectsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReferenceProjects", reflect.TypeOf((*MockService)(nil).ListReferenceProjects), ctx, keyword, offset, limit)
	return &MockServiceListReferenceProjectsCall{Call: call}
}

// MockServiceListReferenceProjectsCall wrap *gomock.Call
type MockServiceListReferenceProjectsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListReferenceProjectsCall) Return(arg0 []domain.CodebookProject, arg1 int64, arg2 error) *MockServiceListReferenceProjectsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListReferenceProjectsCall) Do(f func(context.Context, string, int64, int64) ([]domain.CodebookProject, int64, error)) *MockServiceListReferenceProjectsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListReferenceProjectsCall) DoAndReturn(f func(context.Context, string, int64, int64) ([]domain.CodebookProject, int64, error)) *MockServiceListReferenceProjectsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListVersions mocks base method.
func (m *MockService) ListVersions(ctx context.Context, nodeID int64) ([]domain.CodebookVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVersions", ctx, nodeID)
	ret0, _ := ret[0].([]domain.CodebookVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVersions indicates an expected call of ListVersions.
func (mr *MockServiceMockRecorder) ListVersions(ctx, nodeID any) *MockServiceListVersionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVersions", reflect.TypeOf((*MockService)(nil).ListVersions), ctx, nodeID)
	return &MockServiceListVersionsCall{Call: call}
}

// MockServiceListVersionsCall wrap *gomock.Call
type MockServiceListVersionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListVersionsCall) Return(arg0 []domain.CodebookVersion, arg1 error) *MockServiceListVersionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListVersionsCall) Do(f func(context.Context, int64) ([]domain.CodebookVersion, error)) *MockServiceListVersionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListVersionsCall) DoAndReturn(f func(context.Context, int64) ([]domain.CodebookVersion, error)) *MockServiceListVersionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RestoreProject mocks base method.
func (m *MockService) RestoreProject(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreProject", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreProject indicates an expected call of RestoreProject.
func (mr *MockServiceMockRecorder) RestoreProject(ctx, id any) *MockServiceRestoreProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreProject", reflect.TypeOf((*MockService)(nil).RestoreProject), ctx, id)
	return &MockServiceRestoreProjectCall{Call: call}
}

// MockServiceRestoreProjectCall wrap *gomock.Call
type MockServiceRestoreProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceRestoreProjectCall) Return(arg0 int64, arg1 error) *MockServiceRestoreProjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceRestoreProjectCall) Do(f func(context.Context, int64) (int64, error)) *MockServiceRestoreProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceRestoreProjectCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockServiceRestoreProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Sort mocks base method.
func (m *MockService) Sort(ctx context.Context, id, targetParentID, targetPosition int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sort", ctx, id, targetParentID, targetPosition)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sort indicates an expected call of Sort.
func (mr *MockServiceMockRecorder) Sort(ctx, id, targetParentID, targetPosition any) *MockServiceSortCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sort", reflect.TypeOf((*MockService)(nil).Sort), ctx, id, targetParentID, targetPosition)
	return &MockServiceSortCall{Call: call}
}

// MockServiceSortCall wrap *gomock.Call
type MockServiceSortCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSortCall) Return(arg0 error) *MockServiceSortCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSortCall) Do(f func(context.Context, int64, int64, int64) error) *MockServiceSortCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSortCall) DoAndReturn(f func(context.Context, int64, int64, int64) error) *MockServiceSortCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SystemChildren mocks base method.
func (m *MockService) SystemChildren(ctx context.Context, rootID, parentID int64) ([]domain.Codebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemChildren", ctx, rootID, parentID)
	ret0, _ := ret[0].([]domain.Codebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemChildren indicates an expected call of SystemChildren.
func (mr *MockServiceMockRecorder) SystemChildren(ctx, rootID, parentID any) *MockServiceSystemChildrenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemChildren", reflect.TypeOf((*MockService)(nil).SystemChildren), ctx, rootID, parentID)
	return &MockServiceSystemChildrenCall{Call: call}
}

// MockServiceSystemChildrenCall wrap *gomock.Call
type MockServiceSystemChildrenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSystemChildrenCall) Return(arg0 []domain.Codebook, arg1 error) *MockServiceSystemChildrenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSystemChildrenCall) Do(f func(context.Context, int64, int64) ([]domain.Codebook, error)) *MockServiceSystemChildrenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSystemChildrenCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.Codebook, error)) *MockServiceSystemChildrenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, req domain.Codebook) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, req any) *MockServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, req)
	return &MockServiceUpdateCall{Call: call}
}

// MockServiceUpdateCall wrap *gomock.Call
type MockServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateCall) Return(arg0 int64, arg1 error) *MockServiceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateCall) Do(f func(context.Context, domain.Codebook) (int64, error)) *MockServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateCall) DoAndReturn(f func(context.Context, domain.Codebook) (int64, error)) *MockServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProject mocks base method.
func (m *MockService) UpdateProject(ctx context.Context, req domain.CodebookProject) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockServiceMockRecorder) UpdateProject(ctx, req any) *MockServiceUpdateProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockService)(nil).UpdateProject), ctx, req)
	return &MockServiceUpdateProjectCall{Call: call}
}

// MockServiceUpdateProjectCall wrap *gomock.Call
type MockServiceUpdateProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateProjectCall) Return(arg0 int64, arg1 error) *MockServiceUpdateProjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateProjectCall) Do(f func(context.Context, domain.CodebookProject) (int64, error)) *MockServiceUpdateProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateProjectCall) DoAndReturn(f func(context.Context, domain.CodebookProject) (int64, error)) *MockServiceUpdateProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UseVersion mocks base method.
func (m *MockService) UseVersion(ctx context.Context, nodeID, versionID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseVersion", ctx, nodeID, versionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UseVersion indicates an expected call of UseVersion.
func (mr *MockServiceMockRecorder) UseVersion(ctx, nodeID, versionID any) *MockServiceUseVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseVersion", reflect.TypeOf((*MockService)(nil).UseVersion), ctx, nodeID, versionID)
	return &MockServiceUseVersionCall{Call: call}
}

// MockServiceUseVersionCall wrap *gomock.Call
type MockServiceUseVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUseVersionCall) Return(arg0 int64, arg1 error) *MockServiceUseVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUseVersionCall) Do(f func(context.Context, int64, int64) (int64, error)) *MockServiceUseVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUseVersionCall) DoAndReturn(f func(context.Context, int64, int64) (int64, error)) *MockServiceUseVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
