// Code generated by MockGen. DO NOT EDIT.
// Source: ./import.go
//
// Generated by this command:
//
//	mockgen -source=./import.go -package=codebookmocks -destination=./mocks/project_file_repository.mock.go -typed
//

// Package codebookmocks is a generated GoMock package.
package codebookmocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	codebook "github.com/Duke1616/etask/internal/service/codebook"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectFileRepository is a mock of ProjectFileRepository interface.
type MockProjectFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectFileRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectFileRepositoryMockRecorder is the mock recorder for MockProjectFileRepository.
type MockProjectFileRepositoryMockRecorder struct {
	mock *MockProjectFileRepository
}

// NewMockProjectFileRepository creates a new mock instance.
func NewMockProjectFileRepository(ctrl *gomock.Controller) *MockProjectFileRepository {
	mock := &MockProjectFileRepository{ctrl: ctrl}
	mock.recorder = &MockProjectFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectFileRepository) EXPECT() *MockProjectFileRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockProjectFileRepository) Delete(ctx context.Context, id int64) (domain.CodebookDeleteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(domain.CodebookDeleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectFileRepositoryMockRecorder) Delete(ctx, id any) *MockProjectFileRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectFileRepository)(nil).Delete), ctx, id)
	return &MockProjectFileRepositoryDeleteCall{Call: call}
}

// MockProjectFileRepositoryDeleteCall wrap *gomock.Call
type MockProjectFileRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectFileRepositoryDeleteCall) Return(arg0 domain.CodebookDeleteResult, arg1 error) *MockProjectFileRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectFileRepositoryDeleteCall) Do(f func(context.Context, int64) (domain.CodebookDeleteResult, error)) *MockProjectFileRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectFileRepositoryDeleteCall) DoAndReturn(f func(context.Context, int64) (domain.CodebookDeleteResult, error)) *MockProjectFileRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockProjectFileRepository) GetByID(ctx context.Context, id int64) (domain.Codebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Codebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProjectFileRepositoryMockRecorder) GetByID(ctx, id any) *MockProjectFileRepositoryGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProjectFileRepository)(nil).GetByID), ctx, id)
	return &MockProjectFileRepositoryGetByIDCall{Call: call}
}

// MockProjectFileRepositoryGetByIDCall wrap *gomock.Call
type MockProjectFileRepositoryGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectFileRepositoryGetByIDCall) Return(arg0 domain.Codebook, arg1 error) *MockProjectFileRepositoryGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectFileRepositoryGetByIDCall) Do(f func(context.Context, int64) (domain.Codebook, error)) *MockProjectFileRepositoryGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectFileRepositoryGetByIDCall) DoAndReturn(f func(context.Context, int64) (domain.Codebook, error)) *MockProjectFileRepositoryGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetNodeByID mocks base method.
func (m *MockProjectFileRepository) GetNodeByID(ctx context.Context, id int64) (domain.Codebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeByID", ctx, id)
	ret0, _ := ret[0].(domain.Codebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeByID indicates an expected call of GetNodeByID.
func (mr *MockProjectFileRepositoryMockRecorder) GetNodeByID(ctx, id any) *MockProjectFileRepositoryGetNodeByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeByID", reflect.TypeOf((*MockProjectFileRepository)(nil).GetNodeByID), ctx, id)
	return &MockProjectFileRepositoryGetNodeByIDCall{Call: call}
}

// MockProjectFileRepositoryGetNodeByIDCall wrap *gomock.Call
type MockProjectFileRepositoryGetNodeByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectFileRepositoryGetNodeByIDCall) Return(arg0 domain.Codebook, arg1 error) *MockProjectFileRepositoryGetNodeByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectFileRepositoryGetNodeByIDCall) Do(f func(context.Context, int64) (domain.Codebook, error)) *MockProjectFileRepositoryGetNodeByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectFileRepositoryGetNodeByIDCall) DoAndReturn(f func(context.Context, int64) (domain.Codebook, error)) *MockProjectFileRepositoryGetNodeByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProjectByID mocks base method.
func (m *MockProjectFileRepository) GetProjectByID(ctx context.Context, id int64) (domain.CodebookProject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", ctx, id)
	ret0, _ := ret[0].(domain.CodebookProject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockProjectFileRepositoryMockRecorder) GetProjectByID(ctx, id any) *MockProjectFileRepositoryGetProjectByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockProjectFileRepository)(nil).GetProjectByID), ctx, id)
	return &MockProjectFileRepositoryGetProjectByIDCall{Call: call}
}

// MockProjectFileRepositoryGetProjectByIDCall wrap *gomock.Call
type MockProjectFileRepositoryGetProjectByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectFileRepositoryGetProjectByIDCall) Return(arg0 domain.CodebookProject, arg1 error) *MockProjectFileRepositoryGetProjectByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectFileRepositoryGetProjectByIDCall) Do(f func(context.Context, int64) (domain.CodebookProject, error)) *MockProjectFileRepositoryGetProjectByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectFileRepositoryGetProjectByIDCall) DoAndReturn(f func(context.Context, int64) (domain.CodebookProject, error)) *MockProjectFileRepositoryGetProjectByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Import mocks base method.
func (m *MockProjectFileRepository) Import(ctx context.Context, request domain.CodebookImport) (domain.CodebookImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", ctx, request)
	ret0, _ := ret[0].(domain.CodebookImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockProjectFileRepositoryMockRecorder) Import(ctx, request any) *MockProjectFileRepositoryImportCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockProjectFileRepository)(nil).Import), ctx, request)
	return &MockProjectFileRepositoryImportCall{Call: call}
}

// MockProjectFileRepositoryImportCall wrap *gomock.Call
type MockProjectFileRepositoryImportCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectFileRepositoryImportCall) Return(arg0 domain.CodebookImportResult, arg1 error) *MockProjectFileRepositoryImportCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectFileRepositoryImportCall) Do(f func(context.Context, domain.CodebookImport) (domain.CodebookImportResult, error)) *MockProjectFileRepositoryImportCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectFileRepositoryImportCall) DoAndReturn(f func(context.Context, domain.CodebookImport) (domain.CodebookImportResult, error)) *MockProjectFileRepositoryImportCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProjectFileService is a mock of ProjectFileService interface.
type MockProjectFileService struct {
	ctrl     *gomock.Controller
	recorder *MockProjectFileServiceMockRecorder
	isgomock struct{}
}

// MockProjectFileServiceMockRecorder is the mock recorder for MockProjectFileService.
type MockProjectFileServiceMockRecorder struct {
	mock *MockProjectFileService
}

// NewMockProjectFileService creates a new mock instance.
func NewMockProjectFileService(ctrl *gomock.Controller) *MockProjectFileService {
	mock := &MockProjectFileService{ctrl: ctrl}
	mock.recorder = &MockProjectFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectFileService) EXPECT() *MockProjectFileServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockProjectFileService) Delete(ctx context.Context, nodeID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, nodeID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectFileServiceMockRecorder) Delete(ctx, nodeID any) *MockProjectFileServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectFileService)(nil).Delete), ctx, nodeID)
	return &MockProjectFileServiceDeleteCall{Call: call}
}

// MockProjectFileServiceDeleteCall wrap *gomock.Call
type MockProjectFileServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectFileServiceDeleteCall) Return(arg0 int64, arg1 error) *MockProjectFileServiceDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectFileServiceDeleteCall) Do(f func(context.Context, int64) (int64, error)) *MockProjectFileServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectFileServiceDeleteCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockProjectFileServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Import mocks base method.
func (m *MockProjectFileService) Import(ctx context.Context, request codebook.ImportRequest) (domain.CodebookImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", ctx, request)
	ret0, _ := ret[0].(domain.CodebookImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockProjectFileServiceMockRecorder) Import(ctx, request any) *MockProjectFileServiceImportCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockProjectFileService)(nil).Import), ctx, request)
	return &MockProjectFileServiceImportCall{Call: call}
}

// MockProjectFileServiceImportCall wrap *gomock.Call
type MockProjectFileServiceImportCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectFileServiceImportCall) Return(arg0 domain.CodebookImportResult, arg1 error) *MockProjectFileServiceImportCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectFileServiceImportCall) Do(f func(context.Context, codebook.ImportRequest) (domain.CodebookImportResult, error)) *MockProjectFileServiceImportCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectFileServiceImportCall) DoAndReturn(f func(context.Context, codebook.ImportRequest) (domain.CodebookImportResult, error)) *MockProjectFileServiceImportCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Open mocks base method.
func (m *MockProjectFileService) Open(ctx context.Context, nodeID int64) (domain.Codebook, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, nodeID)
	ret0, _ := ret[0].(domain.Codebook)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Open indicates an expected call of Open.
func (mr *MockProjectFileServiceMockRecorder) Open(ctx, nodeID any) *MockProjectFileServiceOpenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockProjectFileService)(nil).Open), ctx, nodeID)
	return &MockProjectFileServiceOpenCall{Call: call}
}

// MockProjectFileServiceOpenCall wrap *gomock.Call
type MockProjectFileServiceOpenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectFileServiceOpenCall) Return(arg0 domain.Codebook, arg1 io.ReadCloser, arg2 error) *MockProjectFileServiceOpenCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectFileServiceOpenCall) Do(f func(context.Context, int64) (domain.Codebook, io.ReadCloser, error)) *MockProjectFileServiceOpenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectFileServiceOpenCall) DoAndReturn(f func(context.Context, int64) (domain.Codebook, io.ReadCloser, error)) *MockProjectFileServiceOpenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
