// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ecodeclub/mq-api (interfaces: MQ,Producer)
//
// Generated by this command:
//
//	mockgen -package=eventmocks -destination=./mocks/mq.mock.go -typed github.com/ecodeclub/mq-api MQ,Producer
//

// Package eventmocks is a generated GoMock package.
package eventmocks

import (
	context "context"
	reflect "reflect"

	mq "github.com/ecodeclub/mq-api"
	gomock "go.uber.org/mock/gomock"
)

// MockMQ is a mock of MQ interface.
type MockMQ struct {
	ctrl     *gomock.Controller
	recorder *MockMQMockRecorder
	isgomock struct{}
}

// MockMQMockRecorder is the mock recorder for MockMQ.
type MockMQMockRecorder struct {
	mock *MockMQ
}

// NewMockMQ creates a new mock instance.
func NewMockMQ(ctrl *gomock.Controller) *MockMQ {
	mock := &MockMQ{ctrl: ctrl}
	mock.recorder = &MockMQMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMQ) EXPECT() *MockMQMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMQ) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMQMockRecorder) Close() *MockMQCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMQ)(nil).Close))
	return &MockMQCloseCall{Call: call}
}

// MockMQCloseCall wrap *gomock.Call
type MockMQCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMQCloseCall) Return(arg0 error) *MockMQCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMQCloseCall) Do(f func() error) *MockMQCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMQCloseCall) DoAndReturn(f func() error) *MockMQCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Consumer mocks base method.
func (m *MockMQ) Consumer(topic, groupID string) (mq.Consumer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consumer", topic, groupID)
	ret0, _ := ret[0].(mq.Consumer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consumer indicates an expected call of Consumer.
func (mr *MockMQMockRecorder) Consumer(topic, groupID any) *MockMQConsumerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consumer", reflect.TypeOf((*MockMQ)(nil).Consumer), topic, groupID)
	return &MockMQConsumerCall{Call: call}
}

// MockMQConsumerCall wrap *gomock.Call
type MockMQConsumerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMQConsumerCall) Return(arg0 mq.Consumer, arg1 error) *MockMQConsumerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMQConsumerCall) Do(f func(string, string) (mq.Consumer, error)) *MockMQConsumerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMQConsumerCall) DoAndReturn(f func(string, string) (mq.Consumer, error)) *MockMQConsumerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateTopic mocks base method.
func (m *MockMQ) CreateTopic(ctx context.Context, topic string, partitions int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", ctx, topic, partitions)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockMQMockRecorder) CreateTopic(ctx, topic, partitions any) *MockMQCreateTopicCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockMQ)(nil).CreateTopic), ctx, topic, partitions)
	return &MockMQCreateTopicCall{Call: call}
}

// MockMQCreateTopicCall wrap *gomock.Call
type MockMQCreateTopicCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMQCreateTopicCall) Return(arg0 error) *MockMQCreateTopicCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMQCreateTopicCall) Do(f func(context.Context, string, int) error) *MockMQCreateTopicCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMQCreateTopicCall) DoAndReturn(f func(context.Context, string, int) error) *MockMQCreateTopicCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteTopics mocks base method.
func (m *MockMQ) DeleteTopics(ctx context.Context, topics ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range topics {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTopics", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopics indicates an expected call of DeleteTopics.
func (mr *MockMQMockRecorder) DeleteTopics(ctx any, topics ...any) *MockMQDeleteTopicsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, topics...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopics", reflect.TypeOf((*MockMQ)(nil).DeleteTopics), varargs...)
	return &MockMQDeleteTopicsCall{Call: call}
}

// MockMQDeleteTopicsCall wrap *gomock.Call
type MockMQDeleteTopicsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMQDeleteTopicsCall) Return(arg0 error) *MockMQDeleteTopicsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMQDeleteTopicsCall) Do(f func(context.Context, ...string) error) *MockMQDeleteTopicsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMQDeleteTopicsCall) DoAndReturn(f func(context.Context, ...string) error) *MockMQDeleteTopicsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Producer mocks base method.
func (m *MockMQ) Producer(topic string) (mq.Producer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Producer", topic)
	ret0, _ := ret[0].(mq.Producer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Producer indicates an expected call of Producer.
func (mr *MockMQMockRecorder) Producer(topic any) *MockMQProducerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Producer", reflect.TypeOf((*MockMQ)(nil).Producer), topic)
	return &MockMQProducerCall{Call: call}
}

// MockMQProducerCall wrap *gomock.Call
type MockMQProducerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMQProducerCall) Return(arg0 mq.Producer, arg1 error) *MockMQProducerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMQProducerCall) Do(f func(string) (mq.Producer, error)) *MockMQProducerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMQProducerCall) DoAndReturn(f func(string) (mq.Producer, error)) *MockMQProducerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProducer is a mock of Producer interface.
type MockProducer struct {
	ctrl     *gomock.Controller
	recorder *MockProducerMockRecorder
	isgomock struct{}
}

// MockProducerMockRecorder is the mock recorder for MockProducer.
type MockProducerMockRecorder struct {
	mock *MockProducer
}

// NewMockProducer creates a new mock instance.
func NewMockProducer(ctrl *gomock.Controller) *MockProducer {
	mock := &MockProducer{ctrl: ctrl}
	mock.recorder = &MockProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducer) EXPECT() *MockProducerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockProducer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProducerMockRecorder) Close() *MockProducerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProducer)(nil).Close))
	return &MockProducerCloseCall{Call: call}
}

// MockProducerCloseCall wrap *gomock.Call
type MockProducerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProducerCloseCall) Return(arg0 error) *MockProducerCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProducerCloseCall) Do(f func() error) *MockProducerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProducerCloseCall) DoAndReturn(f func() error) *MockProducerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Produce mocks base method.
func (m_2 *MockProducer) Produce(ctx context.Context, m *mq.Message) (*mq.ProducerResult, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Produce", ctx, m)
	ret0, _ := ret[0].(*mq.ProducerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Produce indicates an expected call of Produce.
func (mr *MockProducerMockRecorder) Produce(ctx, m any) *MockProducerProduceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockProducer)(nil).Produce), ctx, m)
	return &MockProducerProduceCall{Call: call}
}

// MockProducerProduceCall wrap *gomock.Call
type MockProducerProduceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProducerProduceCall) Return(arg0 *mq.ProducerResult, arg1 error) *MockProducerProduceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProducerProduceCall) Do(f func(context.Context, *mq.Message) (*mq.ProducerResult, error)) *MockProducerProduceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProducerProduceCall) DoAndReturn(f func(context.Context, *mq.Message) (*mq.ProducerResult, error)) *MockProducerProduceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProduceWithPartition mocks base method.
func (m_2 *MockProducer) ProduceWithPartition(ctx context.Context, m *mq.Message, partition int) (*mq.ProducerResult, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "ProduceWithPartition", ctx, m, partition)
	ret0, _ := ret[0].(*mq.ProducerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProduceWithPartition indicates an expected call of ProduceWithPartition.
func (mr *MockProducerMockRecorder) ProduceWithPartition(ctx, m, partition any) *MockProducerProduceWithPartitionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceWithPartition", reflect.TypeOf((*MockProducer)(nil).ProduceWithPartition), ctx, m, partition)
	return &MockProducerProduceWithPartitionCall{Call: call}
}

// MockProducerProduceWithPartitionCall wrap *gomock.Call
type MockProducerProduceWithPartitionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProducerProduceWithPartitionCall) Return(arg0 *mq.ProducerResult, arg1 error) *MockProducerProduceWithPartitionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProducerProduceWithPartitionCall) Do(f func(context.Context, *mq.Message, int) (*mq.ProducerResult, error)) *MockProducerProduceWithPartitionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProducerProduceWithPartitionCall) DoAndReturn(f func(context.Context, *mq.Message, int) (*mq.ProducerResult, error)) *MockProducerProduceWithPartitionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
