// Code generated by MockGen. DO NOT EDIT.
// Source: ./producer.go
//
// Generated by this command:
//
//	mockgen -source=./producer.go -package=eventmocks -destination=./mocks/publisher.mock.go -typed
//

// Package eventmocks is a generated GoMock package.
package eventmocks

import (
	context "context"
	reflect "reflect"

	execution "github.com/Duke1616/etask/internal/event/execution"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutionEventPublisher is a mock of ExecutionEventPublisher interface.
type MockExecutionEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionEventPublisherMockRecorder
	isgomock struct{}
}

// MockExecutionEventPublisherMockRecorder is the mock recorder for MockExecutionEventPublisher.
type MockExecutionEventPublisherMockRecorder struct {
	mock *MockExecutionEventPublisher
}

// NewMockExecutionEventPublisher creates a new mock instance.
func NewMockExecutionEventPublisher(ctrl *gomock.Controller) *MockExecutionEventPublisher {
	mock := &MockExecutionEventPublisher{ctrl: ctrl}
	mock.recorder = &MockExecutionEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionEventPublisher) EXPECT() *MockExecutionEventPublisherMockRecorder {
	return m.recorder
}

// PublishFinished mocks base method.
func (m *MockExecutionEventPublisher) PublishFinished(ctx context.Context, finished execution.Finished) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFinished", ctx, finished)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishFinished indicates an expected call of PublishFinished.
func (mr *MockExecutionEventPublisherMockRecorder) PublishFinished(ctx, finished any) *MockExecutionEventPublisherPublishFinishedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFinished", reflect.TypeOf((*MockExecutionEventPublisher)(nil).PublishFinished), ctx, finished)
	return &MockExecutionEventPublisherPublishFinishedCall{Call: call}
}

// MockExecutionEventPublisherPublishFinishedCall wrap *gomock.Call
type MockExecutionEventPublisherPublishFinishedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionEventPublisherPublishFinishedCall) Return(arg0 error) *MockExecutionEventPublisherPublishFinishedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionEventPublisherPublishFinishedCall) Do(f func(context.Context, execution.Finished) error) *MockExecutionEventPublisherPublishFinishedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionEventPublisherPublishFinishedCall) DoAndReturn(f func(context.Context, execution.Finished) error) *MockExecutionEventPublisherPublishFinishedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PublishLogs mocks base method.
func (m *MockExecutionEventPublisher) PublishLogs(ctx context.Context, batch execution.LogBatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishLogs", ctx, batch)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishLogs indicates an expected call of PublishLogs.
func (mr *MockExecutionEventPublisherMockRecorder) PublishLogs(ctx, batch any) *MockExecutionEventPublisherPublishLogsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishLogs", reflect.TypeOf((*MockExecutionEventPublisher)(nil).PublishLogs), ctx, batch)
	return &MockExecutionEventPublisherPublishLogsCall{Call: call}
}

// MockExecutionEventPublisherPublishLogsCall wrap *gomock.Call
type MockExecutionEventPublisherPublishLogsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExecutionEventPublisherPublishLogsCall) Return(arg0 error) *MockExecutionEventPublisherPublishLogsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExecutionEventPublisherPublishLogsCall) Do(f func(context.Context, execution.LogBatch) error) *MockExecutionEventPublisherPublishLogsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExecutionEventPublisherPublishLogsCall) DoAndReturn(f func(context.Context, execution.LogBatch) error) *MockExecutionEventPublisherPublishLogsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
