// Code generated by eiam permgen. DO NOT EDIT.

package model

import "github.com/Duke1616/eiam/pkg/web/capability"

var (
	// Artifact 脚本引擎/制品仓库 (task:artifact)
	Artifact = capability.Model{
		Service: "task",
		Name:    "artifact",
		Group:   "脚本引擎/制品仓库",
		Scope:   capability.ScopeTenant,
	}
	// CodeAssist 脚本引擎/AI 助手 (task:code_assist)
	CodeAssist = capability.Model{
		Service: "task",
		Name:    "code_assist",
		Group:   "脚本引擎/AI 助手",
		Scope:   capability.ScopeTenant,
	}
	// Codebook 脚本引擎/脚本模板 (task:codebook)
	Codebook = capability.Model{
		Service: "task",
		Name:    "codebook",
		Group:   "脚本引擎/脚本模板",
		Scope:   capability.ScopeTenant,
	}
	// ExecutionPool 资源池管理 (task:execution-pool)
	ExecutionPool = capability.Model{
		Service: "task",
		Name:    "execution-pool",
		Group:   "资源池管理",
		Scope:   capability.ScopeSystem,
	}
	// Manager 任务管理 (task:manager)
	Manager = capability.Model{
		Service: "task",
		Name:    "manager",
		Group:   "任务管理",
		Scope:   capability.ScopeTenant,
	}
	// Preview 脚本引擎/试运行 (task:preview)
	Preview = capability.Model{
		Service: "task",
		Name:    "preview",
		Group:   "脚本引擎/试运行",
		Scope:   capability.ScopeTenant,
	}
	// Resource 执行资源 (task:resource)
	Resource = capability.Model{
		Service: "task",
		Name:    "resource",
		Group:   "执行资源",
		Scope:   capability.ScopeTenant,
	}
	// Runner 执行单元 (task:runner)
	Runner = capability.Model{
		Service: "task",
		Name:    "runner",
		Group:   "执行单元",
		Scope:   capability.ScopeTenant,
	}
	// Variable 全局变量 (task:variable)
	Variable = capability.Model{
		Service: "task",
		Name:    "variable",
		Group:   "全局变量",
		Scope:   capability.ScopeTenant,
	}
)
